### ISSUE TITLE
Check function signature

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#1]
Checking the signature (and types of return values) of each function automatically makes it easy to debug type errors. There are three direction of design:

1. Simply add asserts to forward functions.
2. Use decorators.
3. Pass the type information to `Function.__init__`

It must follow DRY rule and should have flexibility to support "variadic" functions (such as `concat`).

**Comment by unnonouno** [comment]
We need to clarify the goal of this issue.

This is my idea:
- for developers who implement `Function`
  - suport to implement *correct* `Function`
- for users who make networks using `Function`
  - support to check correctness of network
  - support to know usage of `Function`
