### ISSUE TITLE
Suggestion: more general reduction kernel

### ISSUE THREAD

**Issue by ryotat** [pfnet/chainer#1006]
Hi,

Suppose I want to compute the weighted sum of a column along some axis. The weights are not normalized. In numpy/cupy, I would write something like
```python
out = (x * weight).sum(axis=-1) / weight.sum()
```

I don't know how this is currently done in cupy but I guess the most naive way of doing it would be to call (1) multiply (x * weight) (2) sum over the terms in the numerator, (3) sum over the weights, and (4) divide the first sum by the second sum. I was wondering if it would be more efficient, if I could write a kernel for doing this.

I was trying to do this by defining the following kernel
```python
weighted_sum=cupy.ReductionKernel('T x, T weight',
                                  'T out',
                                  'x * weight; total_weight += weight',
                                  'a + b',
                                  'out = a / total_weight',
                                  '0); T total_weight=(0',
                                  'weighted_sum',
                                  'T')
```
which seems to compile ok but does not work. Somehow `total_weight` at the end is zero and I get inf everywhere.

Is there a way to define reductions over multiple variables? In this case I would like to compute both the sum in the numerator and the sum in the denominator. If not, I think this would be a valuable feature for many users.

**Comment by okuta** [comment]
If you need ```out = (x * weight).sum(axis=-1) / weight.sum(axis=-1)```,
you can use following code.
```python
_preamble = '''
struct sum_weight_st{
    T sum, total_weight;
    __device__ sum_weight_st() : sum(0), total_weight(0) { }
    __device__ sum_weight_st(T s, T t) : sum(s),total_weight(t) { }
};
__device__ sum_weight_st add(const sum_weight_st& a, const sum_weight_st& b) {
    return sum_weight_st(a.sum + b.sum, a.total_weight + b.total_weight);
}'''

weighted_sum=cupy.ReductionKernel(
        'T x, T weight',
        'T out',
        'sum_weight_st(x * weight, weight)',
        'add(a, b)',
        'out = a.sum / a.total_weight',
        'sum_weight_st()',
        'weighted_sum',
        'sum_weight_st',
        preamble=_preamble)
```

**Comment by ryotat** [comment]
This is awesome! Thank you very much.

**Comment by okuta** [comment]
It seems the problem has been resolved.
