### ISSUE TITLE
A dead link is found on the document

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1034]
"Edit on GitHub" links on the document are dead.

**Comment by unnonouno** [comment]
It is a problem on readthedocs.
https://github.com/rtfd/readthedocs.org/issues/1637

**Comment by tgpfeiffer** [comment]
I just wanted to report this issue. This still does not seem to be fixed upstream..

**Comment by mitmul** [comment]
@tgpfeiffer Thank you for reporting. I confirmed that it's still broken then re-open this issue.

**Comment by niboshi** [comment]
I seems it's fixed now. Please reopen if the issue reoccured.
