### ISSUE TITLE
Warning on python 3.5.0

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1111]
Chainer doesn't work on python 3.5.0. We need to check python version and show warning when a user uses python 3.5.0.

**Comment by neocxi** [comment]
We are seeing random segfaults on python 3.5.0 with Chainer 1.14 and 1.15. If the problem is widespread, maybe this should throw an exception rather than warning? We initially didn't pay attention to this warning and spent a lot of time trying to find what causes segfaults

**Comment by gwtnb** [comment]
Thank you for the great advice. We will fix.
