### ISSUE TITLE
Backpropagation error for F.concat on GPU

### ISSUE THREAD

**Issue by DianeBouchacourt** [pfnet/chainer#1119]
I used the F.concat function to concatenate 2 different outputs, X and Y, of 2 fully-connected layers and then feed (X,Y) to a last fully connected layer, turns out the backpropagation did not behave as expected (on GPU). I did not look into details of the reasons.

The solution I chose is to connect X and Y to their own fully connected layer, and then perform the sum (only one fully connected layer should have a bias then).

**Comment by unnonouno** [comment]
Do you have a minimum code to reproduce the bug?

**Comment by unnonouno** [comment]
Is this issue related to #1266?

**Comment by DianeBouchacourt** [comment]
Dear Yuya,

I am sorry I haven't get back to you earlier, I was rushing for the NIPS
deadline :)

Actually I will withdraw the issue. There was an error on my side, the back
propagation was not performed as expected because I was creating in the
middle of the chain a new chainer.Variable x from the data of another
variable, e.g. x = chainer.Variable(y.data) before concatenating.

Thank you for taking care of my concern, and please accept my apologies for
causing you trouble.

Best regards,

Diane Bouchacourt

**Comment by unnonouno** [comment]
Please reopen the issue when you encounter the same error. I'll close it.
