### ISSUE TITLE
Cupy compile error with the CUDA 

### ISSUE THREAD

**Issue by ZitengWang** [pfnet/chainer#1139]
I was trying to install chainer on a remote server. `pip` is not avaliable for no network connection. So I installed with  `easy_install -d /somedir chainer-1.6.0.tar.gz` and came across the same issue as #702 .
The `cupy/util.so, cupy/core/core.so` were not created. 
The log was:

    /nobackup/Pythonlibs/chainer-1.6.0/temp/tmpnB3tHo/a.cpp:5:15: error: ?.UDA_VERSION?.was not declared in this scope    
    printf("%d", CUDA_VERSION);    
               ^
    *** WARNING: Cannot check CUDA version

I suppose the `env` is correctly setup:

    CUDA_PATH=/usr/local/cuda-6.5
    SHELL=/bin/bash
    LIBRARY_PATH=/nobackup/Pythonlibs/cudnn-6.5-linux-x64-v2/lib:
    SSH_TTY=/dev/pts/10
    LC_ALL=en_US.UTF-8
    LD_LIBRARY_PATH=/usr/local/cuda-6.5/lib64:/nobackup/Pythonlibs/cudnn-6.5-linux-x64-v2:
    CPATH=/nobackup/Pythonlibs/cudnn-6.5-linux-x64-v2/include:
    PATH=/nobackup/anaconda2/bin:/usr/local/cuda-6.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PWD=/nobackup/Pythonlibs/chainer-1.6.0
    PYTHONPATH=:/nobackup/anaconda2/bin:/nobackup/s1/fesp/wangziteng/Pythonlibs

It seems that compile does not occur. So I manually added the `CUDA_VERSION=6050` in `chainer_setup_build.py`. Now the compile log is

    Processing .
    Writing /nobackup/Pythonlibs/chainer-1.6.0/setup.cfg
    Running setup.py -q bdist_egg --dist-dir /nobackup/Pythonlibs/chainer-1.6.0/egg-dist-tmp-y3d9Ld
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    Include directories: ['/usr/local/cuda-6.5/include', '/nobackup/anaconda2/lib/python2.7/site-packages/numpy/core/include']
    Library directories: ['/usr/local/cuda-6.5/lib64', '/usr/local/cuda-6.5/lib']
    cc1plus: warning: command line option ?.Wstrict-prototypes?.is valid for C/ObjC but not for C++
    Include directories: ['/usr/local/cuda-6.5/include', '/nobackup/anaconda2/lib/python2.7/site-packages/numpy/core/include']
    Library directories: ['/usr/local/cuda-6.5/lib64', '/usr/local/cuda-6.5/lib']
    cython path:/nobackup/anaconda2/lib/python2.7/site-packages
    cc1plus: warning: command line option ?.Wstrict-prototypes?.is valid for C/ObjC but not for C++
    cupy/core/core.cpp: In function ?._pyx_obj_4cupy_4core_4core_ndarray*      __pyx_f_4cupy_4core_4core_7ndarray__transpose(__pyx_obj_4cupy_4core_4core_ndarray*, std::vector<long int>, int)?.
    cupy/core/core.cpp:8166:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_7 = ((__pyx_v_axes.size() != __pyx_v_ndim) != 0);
                                     ^
    cupy/core/core.cpp: In function ?._pyx_obj_4cupy_4core_4core_ndarray* 
    cc1plus: warning: command line option ?.Wstrict-prototypes?.is valid for C/ObjC but not for C++
    
     ...
    
    cupy/cuda/cublas.cpp: In function ?.ize_t __pyx_f_4cupy_4cuda_6cublas_create(int)?.
    cupy/cuda/cublas.cpp:1256:3: error: ?.ublasHandle_t?.was not declared in this scope
    cublasHandle_t __pyx_v_handle;
       ^
    cupy/cuda/cublas.cpp:1273:35: error: ?._pyx_v_handle?.was not declared in this scope
     __pyx_v_status = cublasCreate((&__pyx_v_handle));
                                   ^
    cupy/cuda/cublas.cpp:1273:50: error: ?.ublasCreate?.was not declared in this scope
    __pyx_v_status = cublasCreate((&__pyx_v_handle));
                                                  ^
     cupy/cuda/cublas.cpp: In function ?.oid __pyx_f_4cupy_4cuda_6cublas_destroy(size_t, int)?.
    cupy/cuda/cublas.cpp:1380:36: error: ?.ublasHandle_t?.was not declared in this scope
     __pyx_v_status = cublasDestroy(((cublasHandle_t)__pyx_v_handle));
                                     ^
    cupy/cuda/cublas.cpp:1380:51: error: expected ?.?.before ?._pyx_v_handle?
    __pyx_v_status = cublasDestroy(((cublasHandle_t)__pyx_v_handle));
                                                   ^
    cupy/cuda/cublas.cpp: In function ?.nt __pyx_f_4cupy_4cuda_6cublas_getVersion(size_t, int)?.
    
     ...
    
    error: Setup script exited with error: command 'gcc' failed with exit status 1

Is the error related to the `g++` version or maybe the `CUDA` ?

    Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

The gcc version on the server is
    `gcc version 4.9.2 (Debian 4.9.2-10)`

**Comment by delta2323** [comment]
Hi thank you for reporting. Is there any reason why you use Chainer v1.6.0? If not, could you try with the latest version (v1.8.0)?

**Comment by ZitengWang** [comment]
Yes, I tried with the latest version but got the same result. Both the CUDA_VERSION and .pyx compile error. Now considering to compile the cupy/cuda/*.pyx files separately

**Comment by unnonouno** [comment]
`CUDA_VERSION` is defined in `/usr/local/cuda/include/cudnn.h` and `setup.py` checks the header file. This log suggests that the compiler couldn't find the header file.

Did you install Chainer with `sudo`?

**Comment by ZitengWang** [comment]
I checked the `env` again. It turned out to be the `PATH` error. The code is correctly compile now.
