### ISSUE TITLE
Error when installing chainer without numpy

### ISSUE THREAD

**Issue by papower1** [pfnet/chainer#1156]
My pip's log is attached.

When I install numpy first, It is good.

If you guys want to get more information, touch me.

[pip_log.txt](https://github.com/pfnet/chainer/files/251539/pip_log.txt)

**Comment by unnonouno** [comment]
Can you try the newest version? When we made chainer 1.6.1, the newest version of numpy was 1.10.  And the newest numpy 1.11 behaves differently on setup.

**Comment by papower1** [comment]
It's good with latest version of chainer. Thank you.
