### ISSUE TITLE
Mix CPU mode and GPU mode in one network

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1157]
I want to use CPU mode for some functions and GPU mode for others in one network.
When I use a large number of vocabulary in EmbedID about >=1,000,000 words, it consumes large size of memory in GPU. In this situation, I need to use EmbedID in CPU, and to use other functions like LSTMs in GPU.

**Comment by cemoody** [comment]
Might be interesting to do an EmbedID that keeps an LRU cache on the GPU but is backed by a large store on the CPU?

**Comment by unnonouno** [comment]
Oh, it's a cool idea!

#1158 is a simple patch containing a function which simply transport data from CPU to GPU.
