### ISSUE TITLE
Flexible weight initialization of Parametrized Functions

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#118]
I would like to change the way `chainer.functions.Linear` is initialized, especially weight initialization. In current implementation, initialization by Gaussian is hard-coded in `Linear.__init__`.

This problem is generalized how to initialize parametrized functions.

**Comment by EdwardRaff** [comment]
Is there anyone working on this / plans for this? This is particularly important for LSTMs, where the forget bias terms are usually initialized to a value >= 1, and all other bias terms initialized to 0. Its also common to initialize the internal activation in a manner different from the initialization of the input weights. 

There are some compatibility licensed initialization schemes in the keras library that could be used to significantly reduce the effort in this.

**Comment by delta2323** [comment]
Thank you for suggestion on the initialization on LSTM. For now, we do not have any concrete plan to implement this feature. I think we need to design the interface first. Thank you.

**Comment by EdwardRaff** [comment]
If the Keras style of doing it works for you (constructor arguments with default values) I'd be willing to work on merging in the Keras code and adding appropriate initializers.

**Comment by delta2323** [comment]
Although it is vague for now, we also have requirements on initialization scheme. So how about making a WIP (work in progress) PR and discussing the design? Since changes will be huge, I would recommend implement step by step (e.g. first apply change to `Linear Link`).

**Comment by EdwardRaff** [comment]
Sure, I'll make a pull soon.
