### ISSUE TITLE
cuDNN activation functions on non-contiguous arrays cause error

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#1192]
Some activation functions use cuDNN if available by default, e.g. F.sigmoid, F.tanh, and F.relu. They do not consider non-contiguous input arrays, while cuDNN activation functions do not accept them. We should check the contiguity and either copy the arrays to contiguous space before calling cuDNN APIs or avoid using cuDNN when the input is non-contiguous.

**Comment by beam2d** [comment]
Note: a workaround that can be used now is disabling cuDNN by passing use_cudnn=False to each activation function.

**Comment by unnonouno** [comment]
Call `ascontiguousarray` in these functions. See `convolution_2d`.
