### ISSUE TITLE
installation problem: windows7 + chainer1.8.2

### ISSUE THREAD

**Issue by hengck23** [pfnet/chainer#1197]
When i run "python train_mnist.py -g 0", error is

Traceback (most recent call last):
  File "train_mnist.py", line 68, in <module>
    cuda.get_device(args.gpu).use()
  File "C:\Anaconda\lib\site-packages\chainer\cuda.py", line 161, in get_device
    check_cuda_available()
  File "C:\Anaconda\lib\site-packages\chainer\cuda.py", line 82, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).cannot import name core

my install command:
pip uninstall chainer
pip install chainer==1.8.2 --no-cache-dir -vvv

there is no error except:

---

```
*** WARNING: Cannot check CUDA version
*** WARNING: Cannot build a stub file.
Original error: command 'C:\\Users\\win7\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\x64\\mt.exe' failed with exit status 31
**************************************************
```

[log1.txt](https://github.com/pfnet/chainer/files/274943/log1.txt)
 log file is as attached:

**Comment by unnonouno** [comment]
I'm not familiar with Windows environment, but it looks that `mt.exe` command couldn't make a dummy executable file with CUDA due to an error 31.
