### ISSUE TITLE
Ubuntu 16.04 + Chainer 1.6.0 + Anaconda3

### ISSUE THREAD

**Issue by gshreekant** [pfnet/chainer#1205]
When I try to import cupy, I get "ImportError: cannot import name 'core' ". How do I resolve this ? I have cuda 7.5 installed correctly I can see that it's on system path.

**Comment by unnonouno** [comment]
Please reinstall chainer and show me all error log:
```
$ pip uninstall chainer
$ pip install chainer -vvvv --no-cache-dir
```

**Comment by unnonouno** [comment]
Did you solve the problem? I recommend you ubuntu 14.04 because 16.04 is not supported in cuda 7.5. http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements
I'll close this issue. If you still have the problem, please reopen the issue.
