### ISSUE TITLE
Make Chainer.Function objects correspond to stacking functions.

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#1280]
- [x] `F.stack`
- [ ] `F.vstack`
- [x] `F.hstack`
- [ ] `F.dstack`

We need to create corresponding CuPy functions if necessary.

**Comment by delta2323** [comment]
`F.stack` is already implemented as #1262 and #1276.

**Comment by niboshi** [comment]
I think all of the functions above have been implemented.
