### ISSUE TITLE
Use code formatter

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1300]
How about using code formatter such as autopep8?

https://pypi.python.org/pypi/autopep8

**Comment by delta2323** [comment]
Who is the target of your suggestion? Are you thinking that we should encourage developers to use autopep8 (instead of flake8, hacking etc.), for example, by writing it to the contribution guide?

**Comment by unnonouno** [comment]
I want to encourage developers to use it because using autopep8 is as easy as using flake8. We first need to review quality of result of autopep8.

**Comment by delta2323** [comment]
OK. I understand it.

**Comment by unnonouno** [comment]
We are now using autopep8. I'll close this issue.
