### ISSUE TITLE
Is it possible to import caffe model on Python 3?

### ISSUE THREAD

**Issue by chenzhekl** [pfnet/chainer#1314]
As stated in the documentation, `chainer.functions.caffe.CaffeFunction` only supports Python 2.7. However in the "Install Chainer" section, it says

    Caffe model support

    Protocol Buffers
    protobuf>=3.0.0 is required for Py3

Thus I am curious whether caffe model import is supported in Python 3. 

Thank you very much for your help.

**Comment by unnonouno** [comment]
Sorry, the document is wrong. You can use caffe model with protobuf 3 (it is now beta3) on Python3. 
https://pypi.python.org/pypi/protobuf

protobuf 2 is not supported on Python3.

**Comment by chenzhekl** [comment]
Thank you so so much for your reply at this time!
