### ISSUE TITLE
testing.parameterize cannot take dictionary whose values are functions

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#1337]
testing.parameterize takes a list of dictionaries and add assign each element to attributes of the decorated class. But we cannot use functions as the value of the dictionaries as the functions will be registered as the methods of the decorated class and implicitly be fed with `self` as the first argument on their execution.

As a workaround, we should make a class that wraps this function and execute it in its `__call__` method.
Related to #1286

**Comment by unnonouno** [comment]
Is it really required? I think boolean parameters and `if` statements solve this problem.

**Comment by delta2323** [comment]
Could you tell me your solution in detail?

**Comment by unnonouno** [comment]
For example:
```
@parameterize(
  {'use_evaulator': True},
  {'use_evaulator': False},
)
...
        if self.use_evaluator:
            self.link = links.Classifier(chainer.Link(),
                                         evaluator=accuracy_withIgnore_label)
        else:
            self.link = links.Classifier(chainer.Link())
```

**Comment by delta2323** [comment]
Yes, that is one of the solution for my case. But it is counterintuitive that we cannot use functions here, while functions are first-class objects in Python. If there is a way to broaden the acceptable objects with relatively low cost, I would like to adopt it.

**Comment by unnonouno** [comment]
Yes, of course it can. Be aware of readability of test codes. When an error occurs, `str` representation of parameters are shown. This information is important.
Elegance is not so important in test codes, but readability and simplicity is more important because test codes don't have their own test codes.

**Comment by delta2323** [comment]
@unnonouno  I tried implementing `testing.parameterize` that can accept functions as well. Can you take a look at it?
