### ISSUE TITLE
Possibly wrong doc or code for deconvolution cover_all

### ISSUE THREAD

**Issue by LukasDrude** [pfnet/chainer#1341]
The documentation says:

```
cover_all (bool): If True, all spatial locations are convoluted into
            some output pixels. It may make the output size larger.
```

However, when I prepare a small toy example, the output is larger when `cover_all=True`. I feel like either the code or the documentation needs to be inverted.

See an [gist notebook](https://gist.github.com/LukasDrude/8a9ebbaa3a6ba4ae0e2bef611afefd5a) for the toy example or the attached screenshot. I had set the weight matrices to ones and disabled normalization for clarity.

![screen shot 2016-07-01 at 14 54 08](https://cloud.githubusercontent.com/assets/1886882/16522122/fa0d9554-3f9b-11e6-8f2c-3ea75a9b0a5b.png)

**Comment by delta2323** [comment]
Thank you for pointing out the problem. I think this is documentation bug. In `Convolution2D`, It is true that `cover_all=True` option makes the output larger than `False` case. As deconvolution is the inverse operation of convolution, this option should the output smaller.
