### ISSUE TITLE
Mean values of Chainer Variable

### ISSUE THREAD

**Issue by iaroslav-ai** [pfnet/chainer#1350]
Hi,
this might be something very trivial, but I cannot find the function in chainer.functions which would compute the mean of values in Chainer variable. Maybe related to #1102 .
Having such function is very useful for defining custom objectives.

**Comment by delta2323** [comment]
Hi.
Does `chainer.functions.sum()` help for your goal? You can get the number of elements of the array by size. So I believe the following code will work.

```
from chainer import functions as F
# v is an instance of chainer.Variable
s = F.sum(v)
mean = s / len(v)  # len(v) is the number of elements of the underlying array
# mean = s / len(v.data)  # if we want to take the mean of the minibatch represented by v
```

**Comment by iaroslav-ai** [comment]
Ah I see now. I thought the len behave same as in numpy. Thanks for clarification!
