### ISSUE TITLE
Is array[None] correct?

### ISSUE THREAD

**Issue by orihime-akami** [pfnet/chainer#1393]
日本語で失礼します。
https://github.com/pfnet/chainer/blob/master/chainer/dataset/convert.py#L94

arrayの引数にNoneを与えるというのは、良いのでしょうか？

手元のコードで、これに起因した

```
    return xp.concatenate([array[None] for array in arrays])
TypeError: list indices must be integers, not NoneType
```

というエラーが起きています。

**Comment by orihime-akami** [comment]
すみません、自己解決できそうです。

**Comment by unnonouno** [comment]
`array` is `xp.ndarray` here. `array[None]` represents `array[xp.newaxis]`, that means this code changes shape of the array before `concatenate`.

ここの`array`は`xp.ndarray`です。`array[None]`は`array[xp.newaxis]`のことで、`concatenate`する前に`shape`を変えています。
