### ISSUE TITLE
FileExistsError at first epoch finished

### ISSUE THREAD

**Issue by danpansa** [pfnet/chainer#1394]
I try the Chainer v1.11.0 on windows 10(64bit). My python is python3.5 on anaconda. I tested the MNIST sample code was obtained from  http://qiita.com/_329_/items/bcc306194d52f7b81b5a. The code was good working at start. However, it stopped when the first epoch had been finished.  The error message is below. Is this error global or depend on windows 10?
---------------------------------------------------------------------------
FileExistsError                           Traceback (most recent call last)
<ipython-input-49-a920a1206cd1> in <module>()
     33 trainer.extend(extensions.ProgressBar())
     34 
---> 35 trainer.run()

C:\Anaconda3\lib\site-packages\chainer\training\trainer.py in run(self)
    266                     for name, entry in extensions:
    267                         if entry.trigger(self):
--> 268                             entry.extension(self)
    269         finally:
    270             for _, entry in extensions:

C:\Anaconda3\lib\site-packages\chainer\training\extensions\log_report.py in __call__(self, trainer)
     92                 with os.fdopen(fd, 'w') as f:
     93                     json.dump(self._log, f, indent=4)
---> 94                 os.rename(path, os.path.join(trainer.out, log_name))
     95             # reset the summary for the next output
     96             self._init_summary()

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\name\\chainer1.11\\result\\logq7tunkxu' -> 'result\\log'

**Comment by td2sk** [comment]
On windows (only windows?), os.rename cannot override file that already exists.
I now use work-around below.

94  log_path = os.path.join(os.path.join(trainer.out, log_name))
95  if os.path.exists(log_path):
96     os.remove(log_path)
97  os.rename(path, log_path)

**Comment by danpansa** [comment]
Thank you very much for quick response, and I'm sorry for my late reply.

I fixed the "log_report.py" according to  your reply, I found that the problem had fixed.

Thank you for your help! I'm closing this issue.

**Comment by delta2323** [comment]
Thank you for reporting the problem. I sent the PR that fixes this problem, although this issue is closed.

**Comment by delta2323** [comment]
I fixed the implementation in #1412 . As I do not have Windows environment, so does anyone check it with Windows?

**Comment by okuta** [comment]
I checked #1412 on Windows 10.
