### ISSUE TITLE
Console log does not display correctly in windows7

### ISSUE THREAD

**Issue by yizumi1012xxx** [pfnet/chainer#1396]
ANSI escape code (ex. \033[J) is used in logging function (ex. progress_bar), and the text which contains ANSI escape code cannot display correctly in windows (except windows10) console view.

if you have counter-measure, please fix this problem.

thank you for reading, and hope my english mistake haven't put you off.

**Comment by fquivira** [comment]
+1 . The logging function fails to display properly in Windows 8.1 (running mnist example)

![mnist-output](https://cloud.githubusercontent.com/assets/1800870/16974768/f95d2388-4e0d-11e6-86e6-e9f241fbd096.png)

Thanks for your support!

**Comment by niboshi** [comment]
I think this issue has been solved in #1730. Please reopen if it persists.
