### ISSUE TITLE
SerialIterator's shuffle does not work under certain batch sizes

### ISSUE THREAD

**Issue by iwiwi** [pfnet/chainer#1416]
When we give `shuffle=True` to `SerialIterator`, re-shuffling after an epoch is skipped if `len(dataset)` is divisible by `batch_size`.

![image](https://cloud.githubusercontent.com/assets/469803/17083083/f55bbc30-51ce-11e6-86e7-66853674b898.png)

https://github.com/pfnet/chainer/blob/master/chainer/iterators/serial_iterator.py#L65

Variable `_order` is never re-shuffled if `rest` > 0 (i.e., `len(dataset)` is divisible by `batch_size`).

(If it is okay, I'm interested in working on this issue at the development meeting tomorrow.)

**Comment by zori** [comment]
confirmed, also on the MNIST example
