### ISSUE TITLE
Errors in numpy-cupy comparison tests are ignored if accept_error=True by default

### ISSUE THREAD

**Issue by muupan** [pfnet/chainer#1419]
`cupy.testing` has decorators for comparing results from numpy and cupy functions such as `numpy_cupy_array_equal`. In these decorators, `accept_error=True` by default, so even if test code has typo or access to undefined names, they would pass. Such decorators are used everywhere without specifying `accept_error=False`: https://github.com/pfnet/chainer/search?utf8=%E2%9C%93&q=numpy_cupy_array_equal&type=Code 

For example, https://github.com/pfnet/chainer/pull/1404 has typo in test code, calling `xp.fill_diag` instead of `xp.fill_diagonal`, but the tests pass. I suppose errors should not be ignored by default. It would be better to have users to specify which type of errors should be accepted.

**Comment by unnonouno** [comment]
It is a good suggestion. How about making default value `False`, or adding an argument specifying acceptable error type?
