### ISSUE TITLE
LogReport might fail to overwrite a log file

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#1431]
When the log name is fixed, LogReport try to rename a temporary file to that file name, but it might be failed in some environment (e.g. Windows). https://github.com/pfnet/chainer/blob/master/chainer/training/extensions/log_report.py#L94

**Comment by tamamu** [comment]
I think it is the same as #1394 .

**Comment by beam2d** [comment]
Oh, thank you, I didn't notice that.
