### ISSUE TITLE
Indexing cupy with list of slices fails where tuple of slices works

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#1433]
Cupy doesn't like indexing with lists of slices, but is ok with tuples of slices. Numpy works with either one. 

```
import numpy as np
import cupy as cp
a = cp.ones((2,3))
b = np.ones((2,3))
l = [slice(None), slice(None)]
a[l]  # TypeError: Invalid index type: <type 'list'>
b[l]  # ok
l = (slice(None), slice(None))
a[l] # ok
b[l] # ok
```

**Comment by delta2323** [comment]
Thank you for reporting the issue. Currently, CuPy automatically triggers basic indexing when the indexing object of `__getitem__` is a list. But actually, there are cases in which NumPy triggers basic indexing although the indexing object is a list. So, we should support such cases.

By the way, according to the [NumPy document](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#advanced-indexing), non-tuple sequence objects should trigger basic indexing. Is it the inconsistency between the document and the implementation?

**Comment by muupan** [comment]
It seems already resolved.
