### ISSUE TITLE
Lightweight type-check

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1437]
The current type check mechanism is heavy because it creates syntactic tree with Python. It can be bottleneck. We need simpler method to check types of input variables.

**Comment by jekbradbury** [comment]
But at least it can be easily disabled when not debugging. During runtime, if typecheck is disabled, there is still a lot of Python overhead, especially in creating new Variables (25 microseconds each) or checking for function hooks even if none exist (also around 20 microseconds). Those would probably be better immediate candidates for serious optimization (cython?) than a mechanism which is needed only for debugging.

**Comment by unnonouno** [comment]
Thank you for a comment. Yes that's write. CPython interpreter is too slow, and as you say we consider cython is a candidate for improving CPU performance.

**Comment by unnonouno** [comment]
I implemented lazy-typecheck in #2136
