### ISSUE TITLE
Is it possible to merge two different input layers into one?

### ISSUE THREAD

**Issue by loofahcus** [pfnet/chainer#1439]
Keras provide [Merge Layer](http://keras.io/layers/core/#merge) for this, is it possible in chainer?

**Comment by muupan** [comment]
You can merge two tensors to one by using chainer functions. `chainer.functions.concat` for concatenation, `+` operator for element-wise addition, `*` operator for element-wise multiplication, for example.

**Comment by loofahcus** [comment]
Thanks a lot!
