### ISSUE TITLE
use cpu in forward/ use gpu in backprop 

### ISSUE THREAD

**Issue by etienne87** [pfnet/chainer#1441]
Hello!

I love your API, however i have a small issue.
I have a online-training problem where i would like to do _multiple forwards_ and at some point, ask for _a backprop to happen in the GPU_. Right now it throws an error with this small code :

```
def test_long_backward(use_gpu=1):
    L = Variable((np.zeros(1, dtype=np.float32)))
    for j in range(2,5):
        niter = int(10**j)
        for i in range(niter):
            x_data = np.array([i], dtype=np.float32)
            x = Variable(x_data)
            y = x**2 - 2 * x + 1
            L += y
            
        t = time.time()
        if use_gpu:
            L.to_gpu()
        print('start backprop...')
        L.backward()
        L.unchain_backward()
        print((time.time()-t)*1000, ' ms @backward with batchsize = ',niter)     
```

> File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 368, in backward
    _check_grad_type(func, x, gx)
  File "/usr/local/lib/python2.7/dist-packages/chainer/variable.py", line 40, in _check_grad_type
    raise TypeError(make_message(msg))
TypeError: Function `Add` (_ + _) has a bug.

> Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/pfnet/chainer/issues/new.
Type of data and grad mismatch
<type 'numpy.ndarray'> != <type 'cupy.core.core.ndarray'>

Is it realistic to think the computational graph could automagically transfer everything into the GPU ?

**Comment by delta2323** [comment]
Hi, thank you for reporting the problem. Currently, Chainer does not have such a feature, we need to transfer variables manually to GPU and raises error if the input variables of a `chainer.Function` and output variables are both in host memory or not in the same device.

For example, the code will raise the same error as yours.

```
from chainer import Variable
import numpy as np

x = Variable(np.zeros(1))
y = x + 1
# x.to_gpu()
y.to_gpu()
y.backward()
```
Uncommented the above line will remove the error.

Although it is not a expected usage, `Link.to_gpu` transfers all variables registered to specified GPU. So if you register `x` and `y` in the above example to the same link (by e.g. `Link.add_param`) and call `Link.to_gpu`, Chainer transfers both `x` and `y`.

**Comment by etienne87** [comment]
Hello @delta2323 !

Thanks a lot for your answer. I think this feature is desirable in online setting experiments, such  as reinforcement learning for example, where forward of small cnn for 1 image is not so useful to happen on the gpu.

Do you think I can access the data in the computational graph inside the Variable & apply to_gpu to each one ?
