### ISSUE TITLE
Merge Dockerfile into repo

### ISSUE THREAD

**Issue by Skylion007** [pfnet/chainer#1458]
I came across another [repo](https://github.com/pfnet/chainer-mnist-docker) where a Dockerfile was created to install chainer. It would be nice to have an official Dockerfile to use and if kept in the main repo, it would be more likely to be kept up to date.

**Comment by unnonouno** [comment]
I made a draft version of Dockerfile with CUDA 7.5 and cuDNN v5.  Please give us any comments!
