### ISSUE TITLE
Bug in chainer/cupy/core/carray.cuh float16 /=

### ISSUE THREAD

**Issue by boeddeker** [pfnet/chainer#1495]
in the implemention of float16 the operator /= calculates +
 ``` template<typename T>
  inline __device__ float16& operator/=(const T& rhs)
  {
    *this = *this + rhs;
    return *this;
  }```

**Comment by delta2323** [comment]
Thank you for reporting the issue. We fixed the problem. Could you try that?

**Comment by boeddeker** [comment]
Thanks, I have no application, where I use float16. I have only recognized the Bug, while I was modifying the code for complex numbers.

**Comment by delta2323** [comment]
OK, I understand it.
