### ISSUE TITLE
Chainer failed to find CUDA on Ubuntu 16

### ISSUE THREAD

**Issue by greenlakegithub** [pfnet/chainer#1509]
Dear Chainer Dev. I have installed cuda 7.5 on ubuntu successfully. I can use it with torch framework. But my chainer failed to find my cuda included file even I have add all the path to $PATH, $LD_LIBRARY_PATH, $CPATH
Here is some install console output:
----------------------------------------------------------------------
    running build_ext
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    **************************************************
    *** WARNING: nvcc path != CUDA_PATH
    *** WARNING: nvcc path: /usr
    *** WARNING: CUDA_PATH: /usr/local/cuda-7.5
    **************************************************
    Include directories: ['/usr/local/cuda-7.5/include']
    Library directories: ['/usr/local/cuda-7.5/lib64', '/usr/local/cuda-7.5/lib']
    creating /tmp/tmpkKKb6j/tmp
    creating /tmp/tmpkKKb6j/tmp/tmpkKKb6j
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-7.5/include -c /tmp/tmpkKKb6j/a.cpp -o /tmp/tmpkKKb6j/tmp/tmpkKKb6j/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpkKKb6j/tmp/tmpkKKb6j/a.o -o /tmp/tmpkKKb6j/liba.so
    unable to execute 'c++': No such file or directory
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CPATH environment variable
    **************************************************
    Include directories: ['/usr/local/cuda-7.5/include']
    Library directories: ['/usr/local/cuda-7.5/lib64', '/usr/local/cuda-7.5/lib']
    creating /tmp/tmp4rcYPF/tmp
    creating /tmp/tmp4rcYPF/tmp/tmp4rcYPF
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-7.5/include -c /tmp/tmp4rcYPF/a.cpp -o /tmp/tmp4rcYPF/tmp/tmp4rcYPF/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmp4rcYPF/tmp/tmp4rcYPF/a.o -o /tmp/tmp4rcYPF/liba.so
    unable to execute 'c++': No such file or directory
 
-------------------------------------------------------------------------------------------

Here are the PATH :
--------------------------------------------------------------------------------------------------------
mark@mark-ThinkPad-Yoga-14:~$ echo $CPATH
/usr/local/cuda-7.5/include:
mark@mark-ThinkPad-Yoga-14:~$ echo $LD_LIBRARY_PATH 
/usr/local/cuda/lib64:/home/mark/torch/install/lib:/usr/local/cuda/lib64:/home/mark/torch/install/lib:/home/mark/torch/install/lib:
mark@mark-ThinkPad-Yoga-14:~$ echo $PATH
/usr/local/cuda/bin:/home/mark/torch/install/bin:/usr/local/cuda/bin:/home/mark/torch/install/bin:/home/mark/torch/install/bin:/home/mark/bin:/home/mark/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

--------------------------------------------------------------------------------------------
All the missing files are actually in the included directory:
------------------------------------------------------------------
ls /usr/local/cuda-7.5/include/
builtin_types.h            curand_precalc.h                          nppi_threshold_and_compare_operations.h
channel_descriptor.h       curand_uniform.h                          npps_arithmetic_and_logical_operations.h
CL                         cusolver_common.h                         npps_conversion_functions.h
common_functions.h         cusolverDn.h                              npps_filtering_functions.h
crt                        cusolverRf.h                              npps.h
cublas_api.h               cusolverSp.h                              npps_initialization.h
cublas.h                   cusolverSp_LOWLEVEL_PREVIEW.h             npps_statistics_functions.h
cublas_v2.h                cusparse.h                                npps_support_functions.h
cublasXt.h                 cusparse_v2.h                             nppversion.h
cuComplex.h                cuviddec.h                                nvblas.h
cuda_device_runtime_api.h  device_atomic_functions.h                 nvcuvid.h
__cudaFatFormat.h          device_atomic_functions.hpp               nvfunctional
cuda_fp16.h                device_double_functions.h                 nvrtc.h
cudaGL.h                   device_double_functions.hpp               nvToolsExtCuda.h
cuda_gl_interop.h          device_functions_decls.h                  nvToolsExtCudaRt.h
cuda.h                     device_functions.h                        nvToolsExt.h
cudalibxt.h                device_functions.hpp                      nvToolsExtMeta.h
cuda_occupancy.h           device_launch_parameters.h                sm_20_atomic_functions.h
cuda_profiler_api.h        device_types.h                            sm_20_atomic_functions.hpp
cudaProfiler.h             driver_functions.h                        sm_20_intrinsics.h
cuda_runtime_api.h         driver_types.h                            sm_20_intrinsics.hpp
cuda_runtime.h             fatBinaryCtl.h                            sm_30_intrinsics.h
cuda_surface_types.h       fatbinary.h                               sm_30_intrinsics.hpp
cuda_texture_types.h       host_config.h                             sm_32_atomic_functions.h
cudaVDPAU.h                host_defines.h                            sm_32_atomic_functions.hpp
cuda_vdpau_interop.h       math_constants.h                          sm_32_intrinsics.h
cudnn.h                    math_functions_dbl_ptx3.h                 sm_32_intrinsics.hpp
cufft.h                    math_functions_dbl_ptx3.hpp               sm_35_atomic_functions.h
cufftw.h                   math_functions.h                          sm_35_intrinsics.h
cufftXt.h                  math_functions.hpp                        sobol_direction_vectors.h
curand_discrete2.h         nppcore.h                                 surface_functions.h
curand_discrete.h          nppdefs.h                                 surface_functions.hpp
curand_globals.h           npp.h                                     surface_indirect_functions.h
curand.h                   nppi_arithmetic_and_logical_operations.h  surface_indirect_functions.hpp
curand_kernel.h            nppi_color_conversion.h                   surface_types.h
curand_lognormal.h         nppi_compression_functions.h              texture_fetch_functions.h
curand_mrg32k3a.h          nppi_computer_vision.h                    texture_fetch_functions.hpp
curand_mtgp32dc_p_11213.h  nppi_data_exchange_and_initialization.h   texture_indirect_functions.h
curand_mtgp32.h            nppi_filtering_functions.h                texture_indirect_functions.hpp
curand_mtgp32_host.h       nppi_geometry_transforms.h                texture_types.h
curand_mtgp32_kernel.h     nppi.h                                    thrust
curand_normal.h            nppi_linear_transforms.h                  vector_functions.h
curand_normal_static.h     nppi_morphological_operations.h           vector_functions.hpp
curand_philox4x32_x.h      nppi_statistics_functions.h               vector_types.h
curand_poisson.h           nppi_support_functions.h

-----------------------------------------------------------------------------------------------------------

So I guess I installed chainer, but without CUDA support. But all these files: 'cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h are in the PATH. Please help.

Thanks!

**Comment by unnonouno** [comment]
It looks that setup script tries to run `c++` command, and it is not found. I don't know whey this error occurs.
Check your `$CC` environment variable.

**Comment by greenlakegithub** [comment]
Hi @unnonouno 

Thank you for backing to me. Yeah, I checked my $CC, there is nothing there. But I have gcc 4.8 installed.

**Comment by unnonouno** [comment]
:+1:
I'll close the issue. Please ask us if you find another problem.

**Comment by alistairewj** [comment]
Just had the same issue which I fixed. I don't think it had to do with the path. I remember installing CUDA 7.5 on Ubuntu required switching to gcc-4.9 rather than the default gcc-5.4, and somewhere along the process of dealing with this the `c++` command was unbound. I ran `sudo apt-get install --reinstall g++` and it's working great now.
