### ISSUE TITLE
Confusion about the data-parallel computation on multiple GPUs without Trainer

### ISSUE THREAD

**Issue by ycjing** [pfnet/chainer#1512]
I'm a newer to Chainer and learn how to use it. When I read the part of data-parallel computation on multiple GPUs without Trainer, I'm confused about the following code.
        x0 = Variable(cuda.to_gpu(x_batch[:batchsize//2], 0))
        t0 = Variable(cuda.to_gpu(y_batch[:batchsize//2], 0))
        x1 = Variable(cuda.to_gpu(x_batch[batchsize//2:], 1))
        t1 = Variable(cuda.to_gpu(y_batch[batchsize//2:], 1))
        loss_0 = model_0(x0, t0)
        loss_1 = model_1(x1, t1)
I think it actually uses GPU 0 and GPU 1 sequentially but not parallelly. How could that be data-parallel computation? 
Since I'm totally a newer, if this question is too simple, I apologize. Any answer is welcomed and I will appreciate your help. Thanks ahead of time!

**Comment by ycjing** [comment]
Further, if I have the following code:
       with cuda.get_device(0):
            feature = vgg(xc)
        with cuda.get_device(1):
            feature_hat = vgg(y)
Will the second row and the fourth row be executed parallelly?

**Comment by delta2323** [comment]
Hi

Thank you for trying Chainer.

Kernel launches are done in asynchronous way, meaning that once you launch the kernels, the following codes are executed right away. So if you do not perform any operation that involves synchronization of GPU (e.g. copy the resulting array from GPU to CPU), calls of `model_0` and `model_1` will be performed in parallel.

If you use profiling tools like nvvp, you can check the execution timing of kernels.

**Comment by ycjing** [comment]
@delta2323 Thank you very much! It seems I need to learn knowledge about CUDA architectures to further understand parallelism. Thanks again!
