### ISSUE TITLE
Allow to mark unit tests as slow

### ISSUE THREAD

**Issue by zori** [pfnet/chainer#1514]
It would be useful to introduce a policy for slower tests, in order to avoid running them during the development phase.

**Comment by unnonouno** [comment]
It is good suggestion. We can introduce `@attr.slow` attribute like `@attr.gpu`.
Now, we need to discuss the number of test levels and policy of the levels. I think two test level is enough:

- Normal tests (no attribute): Jenkins tests always them.
- Slow tests (`@attr.slow`): Jenkins tests them weekly (on sunday?).
