### ISSUE TITLE
Do you have plans to support advanced slicing in `get_item` function?

### ISSUE THREAD

**Issue by kaniblu** [pfnet/chainer#1555]
Currently, `get_item` function only supports indexing through slices or integers but not `numpy` or `cupy` arrays. But our recent project requires the latter functionality. If you guys have no plans to implement the functionality yet, we would be happy to do so. Please give us a heads up.

**Comment by delta2323** [comment]
Sorry for late response, we do not have any concrete plan to implement (backpropable) advanced indexing, although we know it is desired. We are happy if you work on the feature.

**Comment by muupan** [comment]
This is resolved by #2203 .
