### ISSUE TITLE
cannot uninstall chainer 1.14.0

### ISSUE THREAD

**Issue by cvDreamer** [pfnet/chainer#1560]
installed chainer on Ubuntu 14.04 using

pip install chainer

and after that I would like to uninstall chainer, when typing 
pip uninstall chainer

it shows
"Can't uninstall 'chainer'. No files were found to uninstall."

however, when i do 
pip show chainer

it shows
"---
Name: chainer
Version: 1.14.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: filelock, nose, numpy, protobuf, six"

Any idea?

**Comment by unnonouno** [comment]
I sometimes faced the same problem. I always remove the directory under `dist-packages` though I'm not familiar with pip.
I found the same prolem in stackoverflow:
http://stackoverflow.com/questions/13136060/why-cant-pip-uninstall-pysqlite
Maybe it is problem of pip and package manager.

**Comment by unnonouno** [comment]
Is this problem solved?

**Comment by mindcont** [comment]
same error as chainer 1.18.0


> pi@DEEPMIND:~$ pip show chainer
> "---
> Name: chainer
> Version: 1.18.0
> Location: /usr/local/lib/python2.7/dist-packages
> Requires: filelock, nose, numpy, protobuf, six"
> 
> pi@DEEPMIND:~$ sudo pip uninstall chainer
> Can't uninstall 'chainer'. No files were found to uninstall

**Comment by unnonouno** [comment]
@mindcont Can you find chainer in `/usr/local/lib/python2.7/dist-packages`? 

I'll close this issue. If you have the problem, please reopen this issue @cvDreamer
