### ISSUE TITLE
Build Error (Ubuntu 16.04, CUDA 8.0, CUDNN 5.1, GCC 5.4)

### ISSUE THREAD

**Issue by duschendestroyer** [pfnet/chainer#1609]
versions: Ubuntu 16.04, CUDA 8.0, CUDNN 5.1, GCC 5.4, Chainer 1.15

My cuda environment is not broken, because Theano works just fine.
Even though it seems to be unrelated I don't understand why it warns about nvcc not being in path, because it is.

I'm getting the following compile error:

>   running build_ext
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    **************************************************
    *** WARNING: nvcc not in path.
    *** WARNING: Please set path to nvcc.
    **************************************************
    Include directories: ['/usr/local/cuda/include']
    Library directories: ['/usr/local/cuda/lib64']
    creating /tmp/tmpuhks5z/tmp
    creating /tmp/tmpuhks5z/tmp/tmpuhks5z
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpuhks5z/a.cpp -o /tmp/tmpuhks5z/tmp/tmpuhks5z/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpuhks5z/tmp/tmpuhks5z/a.o -o /tmp/tmpuhks5z/liba.so
    creating /tmp/tmpP_YXIk/tmp
    creating /tmp/tmpP_YXIk/tmp/tmpP_YXIk
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmpP_YXIk/a.cpp -o /tmp/tmpP_YXIk/tmp/tmpP_YXIk/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpP_YXIk/tmp/tmpP_YXIk/a.o -L/usr/local/cuda/lib64 -lcublas -lcuda -lcudart -lcurand -o /tmp/tmpP_YXIk/liba.so
    creating /tmp/tmpWuq6v0/tmp
    creating /tmp/tmpWuq6v0/tmp/tmpWuq6v0
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpWuq6v0/a.cpp -o /tmp/tmpWuq6v0/tmp/tmpWuq6v0/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread /tmp/tmpWuq6v0/tmp/tmpWuq6v0/a.o -o /tmp/tmpWuq6v0/a
    Include directories: ['/usr/local/cuda/include']
    Library directories: ['/usr/local/cuda/lib64']
    creating /tmp/tmpIcY4GP/tmp
    creating /tmp/tmpIcY4GP/tmp/tmpIcY4GP
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpIcY4GP/a.cpp -o /tmp/tmpIcY4GP/tmp/tmpIcY4GP/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpIcY4GP/tmp/tmpIcY4GP/a.o -o /tmp/tmpIcY4GP/liba.so
    creating /tmp/tmpFZ0gHg/tmp
    creating /tmp/tmpFZ0gHg/tmp/tmpFZ0gHg
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmpFZ0gHg/a.cpp -o /tmp/tmpFZ0gHg/tmp/tmpFZ0gHg/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpFZ0gHg/tmp/tmpFZ0gHg/a.o -L/usr/local/cuda/lib64 -lcudnn -o /tmp/tmpFZ0gHg/liba.so
    creating /tmp/tmpJXbWUe/tmp
    creating /tmp/tmpJXbWUe/tmp/tmpJXbWUe
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpJXbWUe/a.cpp -o /tmp/tmpJXbWUe/tmp/tmpJXbWUe/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread /tmp/tmpJXbWUe/tmp/tmpJXbWUe/a.o -o /tmp/tmpJXbWUe/a
    cython path:/usr/local/lib/python2.7/dist-packages
    building 'cupy.core.core' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/cupy
    creating build/temp.linux-x86_64-2.7/cupy/core
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -I/usr/include/python2.7 -c cupy/core/core.cpp -o build/temp.linux-x86_64-2.7/cupy/core/core.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cupy/core/core.cpp: In function ‘__pyx_obj_4cupy_4core_4core_ndarray* __pyx_f_4cupy_4core_4core_7ndarray__transpose(__pyx_obj_4cupy_4core_4core_ndarray*, std::vector<long int>, int)’:
    cupy/core/core.cpp:8588:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_7 = ((__pyx_v_axes.size() != __pyx_v_ndim) != 0);
                                         ^
    cupy/core/core.cpp: In function ‘__pyx_obj_4cupy_4core_4core_ndarray* __pyx_f_4cupy_4core_4core_7ndarray_squeeze(__pyx_obj_4cupy_4core_4core_ndarray*, int, __pyx_opt_args_4cupy_4core_4core_7ndarray_squeeze*)’:
    cupy/core/core.cpp:10280:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_7 = ((__pyx_v_j < __pyx_v_vec_axis.size()) != 0);
                                 ^
    cupy/core/core.cpp:10286:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         __pyx_t_7 = ((__pyx_v_i == (__pyx_v_vec_axis[__pyx_v_j])) != 0);
                                 ^
    cupy/core/core.cpp: In function ‘__pyx_obj_4cupy_4core_4core_ndarray* __pyx_f_4cupy_4core_4core_7ndarray_reduced_view(__pyx_obj_4cupy_4core_4core_ndarray*, int, __pyx_opt_args_4cupy_4core_4core_7ndarray_reduced_view*)’:
    cupy/core/core.cpp:23704:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_6 = ((__pyx_v_ndim == __pyx_v_shape.size()) != 0);
                                  ^
    cupy/core/core.cpp: In function ‘PyObject* __pyx_f_4cupy_4core_4core__reduce_dims(PyObject*, PyObject*, PyObject*, int)’:
    cupy/core/core.cpp:29474:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_9 = 0; __pyx_t_9 < __pyx_t_8; __pyx_t_9+=1) {
                                       ^
    cupy/core/core.cpp: In function ‘int __pyx_pf_4cupy_4core_4core_9broadcast___init__(__pyx_obj_4cupy_4core_4core_broadcast*, PyObject*)’:
    cupy/core/core.cpp:51375:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (((__pyx_t_6 > __pyx_t_7) != 0)) {
                         ^
    cupy/core/core.cpp:51458:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (__pyx_t_9 = 0; __pyx_t_9 < __pyx_t_8; __pyx_t_9+=1) {
                                       ^
    cupy/core/core.cpp:51468:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           __pyx_t_5 = ((__pyx_v_i < (__pyx_v_shape_arr[__pyx_v_j]).size()) != 0);
                                   ^
    cupy/core/core.cpp: In function ‘PyObject* __pyx_f_4cupy_4core_4core__mat_to_cublas_contiguous(__pyx_obj_4cupy_4core_4core_ndarray*, Py_ssize_t, int)’:
    cupy/core/core.cpp:57521:15: error: ‘__pyx_t_4’ declared as reference but not initialized
       Py_ssize_t &__pyx_t_4;
                   ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

>  Rolling back uninstall of chainer
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5lEvep/chainer/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mmRafK-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5lEvep/chainer/
> sudo pip install --upgrade --force-reinstall chainer  19,53s user 1,59s system 86% cpu 24,350 total
>

**Comment by duschendestroyer** [comment]
Upgrading all pip packages did the trick. unsure which one was the outdated dependency.

**Comment by gwtnb** [comment]
This problem is caused when Cython<0.24 is installed. We must fix.
