### ISSUE TITLE
"nvcc not set in path"

### ISSUE THREAD

**Issue by DylanAlloy** [pfnet/chainer#1634]
I'm using Ubuntu 16.04, NVIDIA 367.44 Display Driver, CUDA 8.0 RC, a GTX 1080, and CUDnn 5.1

I cannot get chainer to see anything. I've tried setting my env vars and here they are:

export CUDA_PATH=/usr/local/cuda-8.0/bin:$CUDA_PATH
export PATH=/bin:/usr/bin:$PATH
export LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LIBRARY_PATH

I'm running as sudo and I've tried preserving env vars with '-E'. I've done 'source ~/.bashrc' plenty of times. 

This is what I get:

   Executing cythonize
      Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
      **************************************************
      *** WARNING: nvcc not in path.
      *** WARNING: Please set path to nvcc.
      **************************************************
      Include directories: ['/usr/local/cuda/include']
      Library directories: ['/usr/local/cuda/lib64']
...
    /usr/bin/ld: cannot find -lcublas
    /usr/bin/ld: cannot find -lcudart
    /usr/bin/ld: cannot find -lcurand
    collect2: error: ld returned 1 exit status
    **************************************************
    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your LIBRARY_PATH environment variable
    **************************************************

**UPDATE: on a whim I tried without sudo. Interesting results but not necessarily a step forward and of course installation failed due to not having privileges to certain directories:**

   Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    **************************************************
    *** WARNING: nvcc path != CUDA_PATH
    *** WARNING: nvcc path: /usr/local/cuda-8.0
    *** WARNING: CUDA_PATH: /usr/local/cuda-8.0:/usr/local/cuda-8.0:/usr/local/cuda-8.0
    **************************************************
    Include directories: ['/usr/local/cuda-8.0/include']
    Library directories: ['/usr/local/cuda-8.0/lib64']
    creating /tmp/tmpHeGxLb/tmp
    creating /tmp/tmpHeGxLb/tmp/tmpHeGxLb
...
    /usr/bin/ld: cannot find -lcublas
    /usr/bin/ld: cannot find -lcuda
    /usr/bin/ld: cannot find -lcudart
    /usr/bin/ld: cannot find -lcurand
    collect2: error: ld returned 1 exit status
    **************************************************
    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your LIBRARY_PATH environment variable
    **************************************************

**Comment by unnonouno** [comment]
It looks that the linker (`ld` command) couldn't find CUDA libraries (libcublas.so, libcuda.so and so on).
Check if `.so` files exist in `/usr/local/cuda-8.0/lib64` directory.

**Comment by DylanAlloy** [comment]
@unnonouno Hey, they do, I checked.

**Comment by unnonouno** [comment]
mmm. Is it possible to build other programs with CUDA such as sample programs of CUDA? I'm wondering why `ld` command doesn't work. 
These lines are output of `ld` command.
```
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: cannot find -lcuda
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: cannot find -lcurand
collect2: error: ld returned 1 exit status
```

**Comment by DylanAlloy** [comment]
http://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary

This link would imply it's not so much an 'ld' problem but that it cannot find libraries. All of those libraries it cannot find are CUDA-based which would make sense in the context of the other errors since it also cannot find NVCC.

I will check to see that CUDA runs in other situations today and update this thread.

I'd be willing to let someone remotely log in if I find out CUDA works on its own. This issue has frankly survived 3 clean installations so it's either my fault and a quick fix or it's something very nuanced but that maybe a fresh pair of eyes and a new brain could figure out. Right now, my whole project is halted on a chainer installation. Works on AWS EC2 but not on my own machine. No steps being changed.

**Comment by DylanAlloy** [comment]
An update.

I reinstalled Ubuntu and changed my GCC & G++ defaults from 5.4 to 4.8 because CUDA installation wouldn't run without it (even though they released a patch for this). After reading many guides and posts about the 8.0 RC update in CUDA, it seems that many things have broken or been confused.

Here is my latest error message during verbose installation after installing 367.44, CUDA 8.0 RC and CUDnn 5.1:

...

    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    Include directories: ['/usr/local/cuda-8.0/include']
    Library directories: ['/usr/local/cuda-8.0/lib64']
    creating /tmp/tmpnPQcVv/tmp
    creating /tmp/tmpnPQcVv/tmp/tmpnPQcVv
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpnPQcVv/a.cpp -o /tmp/tmpnPQcVv/tmp/tmpnPQcVv/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpnPQcVv/tmp/tmpnPQcVv/a.o -o /tmp/tmpnPQcVv/liba.so
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CPATH environment variable
    **************************************************
    Include directories: ['/usr/local/cuda-8.0/include']
    Library directories: ['/usr/local/cuda-8.0/lib64']
    creating /tmp/tmpPix9UC/tmp
    creating /tmp/tmpPix9UC/tmp/tmpPix9UC
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpPix9UC/a.cpp -o /tmp/tmpPix9UC/tmp/tmpPix9UC/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpPix9UC/tmp/tmpPix9UC/a.o -o /tmp/tmpPix9UC/liba.so
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    **************************************************
    *** WARNING: Include files not found: ['cudnn.h']
    *** WARNING: Skip installing cudnn support
    *** WARNING: Check your CPATH environment variable
    **************************************************

...lots of successful copying...

    running build_ext
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    Include directories: ['/usr/local/cuda-8.0/include']
    Library directories: ['/usr/local/cuda-8.0/lib64']
    creating /tmp/tmpHhJbMm/tmp
    creating /tmp/tmpHhJbMm/tmp/tmpHhJbMm
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpHhJbMm/a.cpp -o /tmp/tmpHhJbMm/tmp/tmpHhJbMm/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpHhJbMm/tmp/tmpHhJbMm/a.o -o /tmp/tmpHhJbMm/liba.so
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CPATH environment variable
    **************************************************
    Include directories: ['/usr/local/cuda-8.0/include']
    Library directories: ['/usr/local/cuda-8.0/lib64']
    creating /tmp/tmpMVUPdK/tmp
    creating /tmp/tmpMVUPdK/tmp/tmpMVUPdK
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda-8.0/include -c /tmp/tmpMVUPdK/a.cpp -o /tmp/tmpMVUPdK/tmp/tmpMVUPdK/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpMVUPdK/tmp/tmpMVUPdK/a.o -o /tmp/tmpMVUPdK/liba.so
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    c++: error: unrecognized command line option ‘-Wdate-time’
    c++: error: unrecognized command line option ‘-fstack-protector-strong’
    **************************************************
    *** WARNING: Include files not found: ['cudnn.h']
    *** WARNING: Skip installing cudnn support
    *** WARNING: Check your CPATH environment variable
    **************************************************
    running install_lib

...

And my .bashrc is:

export PATH=$PATH:/usr/local/cuda-8.0/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64
export CPATH=$CPATH:/usr/local/cuda-8.0/include

I'm once again at a loss unfortunately. I've manually checked installations. Everything has installed just fine as far as I know. A link that offered lots of insight was: https://github.com/BVLC/caffe/wiki/GeForce-GTX-1080,---CUDA-8.0,---Ubuntu-16.04,---Caffe as well as https://www.pugetsystems.com/labs/hpc/Install-Ubuntu-16-04-or-14-04-and-CUDA-8-and-7-5-for-NVIDIA-Pascal-GPU-825/

**Comment by DylanAlloy** [comment]
All problems were fixed by installing Ubuntu 14. Something about the compilation of dependencies in g++ 5+ messing everything up. Even after changing default compiler version. Oh well, thanks for the help.

**Comment by unnonouno** [comment]
Oh, that sounds good. Actually we don't test chainer on ubuntu 16.04.
