### ISSUE TITLE
List of external examples

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#168]
Some users have written helpful examples and notes on the web, though they are not accessible from the official site, repository, and documents. I want a list of helpful external examples for convenience of users and developers.

Related to #75.

**Comment by beam2d** [comment]
We should think about how to maintain the Chainer's version with which an example runs. IMO, it is OK to list up the examples with the version at the time the examples are publicized, and if the authors notify us that the examples are up to date, then we update the list.

**Comment by unnonouno** [comment]
I want to make an initial list. Please write links here.

**Comment by unnonouno** [comment]
I made a initial list of external examples by searching github. And, I found that it is difficult to check which version of chainer is supported.

**Comment by beam2d** [comment]
Hmm, it might be helpful to segment the list by implemented method names and sort each segment by last update time (or the first release date, which does not require updates of the list).

**Comment by unnonouno** [comment]
I made an initial list of external examples here: https://github.com/pfnet/chainer/wiki/External-examples

**Comment by beam2d** [comment]
It looks good!

**Comment by delta2323** [comment]
:+1:

**Comment by beam2d** [comment]
Closed. See https://github.com/pfnet/chainer/wiki/External-examples for the list of examples. Thank you @unnonouno!
