### ISSUE TITLE
Can't install Chainer with CUDA on Mac

### ISSUE THREAD

**Issue by bonzeboy** [pfnet/chainer#1700]
I tried to install Chainer with CUDA on Mac, but following errors were occurred.
How do I deal with followings, and install Chainer with CUDA?

[Environment]
- HW: MacBook Pro(Mid 2010) with NVIDIA GeForce 320M 256MB
- OS: OS X El Capitan(10.11.6)
- CUDA: CUDA 7.5
- Python: Python 2.7.12 |Anaconda 4.1.1 (x86_64)
- .bash_profile
  - export PATH="/Developer/NVIDIA/CUDA-7.5/bin:$PATH"                                                                                                                                                     
  - export LD_LIBRARY_PATH="/Developer/NVIDIA/CUDA-7.5/lib:/usr/local/cuda/lib/:$LD_LIBRARY_PATH"                                                                                                          
  - export CPATH="/Developer/NVIDIA/CUDA-7.5/include:$CPATH"                                                                                                                                               
  - export CUDA_INC_DIR="/Developer/NVIDIA/CUDA-7.5/bin:$CUDA_INC_DIR"                                                                                                                                     
  - export DYLD_LIBRARY_PATH="/usr/local/cuda/lib:$DYLD_LIBRARY_PATH"                                                                                                                               
- Chainer:1.16.0

[Error Message]
> pip install chainer --no-cache-dir -vvvv

    gcc -fno-strict-aliasing -I/Users/****/.pyenv/versions/anaconda2-4.0.0/envs/chainer/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/cuda/include -I/Users/****/.pyenv/versions/anaconda2-4.0.0/envs/chainer/include/python2.7 -c cupy/cuda/cublas.cpp -o build/temp.macosx-10.6-x86_64-2.7/cupy/cuda/cublas.o
    In file included from cupy/cuda/cublas.cpp:272:
    cupy/cuda/cupy_cuda.h:18:26: error: typedef redefinition with different types ('cublasDataType_t' vs 'enum cudaDataType_t')
    typedef cublasDataType_t cudaDataType;
                             ^
    /usr/local/cuda/include/library_types.h:66:3: note: previous definition is here
    } cudaDataType;
      ^
    cupy/cuda/cublas.cpp:5650:20: error: no matching function for call to 'cublasSgemmEx'
      __pyx_v_status = cublasSgemmEx(((cublasHandle_t)__pyx_v_handle), ((cublasOperation_t)__pyx_v_transa), ((cublasOperation_t)__pyx_v_transb), __pyx_v_m, __pyx_v_n, __pyx_v_k, (&__pyx_v_alpha), ((void const *)__pyx_v_A), ((cudaDataType)__pyx_v_Atype), __pyx_v_lda, ((void const *)__pyx_v_B), ((cudaDataType)__pyx_v_Btype), __pyx_v_ldb, (&__pyx_v_beta), ((void *)__pyx_v_C), ((cudaDataType)__pyx_v_Ctype), __pyx_v_ldc);
                       ^~~~~~~~~~~~~
    /usr/local/cuda/include/cublas_api.h:1587:39: note: candidate function not viable: no known conversion from 'cudaDataType' (aka 'cudaDataType_t') to 'cublasDataType_t' for 9th argument
    CUBLASAPI cublasStatus_t CUBLASWINAPI cublasSgemmEx  (cublasHandle_t handle,
                                          ^
    2 errors generated.
    error: command 'gcc' failed with exit status 1

**Comment by bkvogel** [comment]
Hi,

According to this link:
https://devtalk.nvidia.com/default/topic/890545/cuda-programming-and-performance/is-the-320m-still-working-on-os-x-10-11-and-toolkit-7-5-/

Cuda 7.5 is not supported on your machine but version 6 should work. However, even if it works, I am not sure if 256 MB will be enough GPU memory to run many models. It might be better to use CPU only on that particular machine.

**Comment by bonzeboy** [comment]
> bkvogel
Thank you for your comment.
I will give up, and use it with CPU only.

**Comment by bkvogel** [comment]
Sure, no problem. I will close the issue.

**Comment by wkentaro** [comment]
Well, I sometimes use macOS also to develop neural networks, aside from training in parallel with large gpu system on Ubuntu computer.
Using [external GPU](https://bizon-tech.com/us/bizonbox2-egpu.html/), I can use Chainer v1.14.0 + Titan X + CUDA 7.5.26 + Macbook Pro 13-inch Late 2013 + OS X Yosemite.

![image](https://cloud.githubusercontent.com/assets/4310419/19836036/b51cc3a6-9ed8-11e6-8e35-15236377040c.png)

But with Chainer v1.17.0, I have same error as @bkvogel reports.

```
In file included from cupy/cuda/cublas.cpp:414:
cupy/cuda/cupy_cuda.h:20:26: error: typedef redefinition with different types ('cublasDataType_t' vs 'enum cudaDataType_t')
typedef cublasDataType_t cudaDataType;
                         ^
/usr/local/cuda/include/library_types.h:66:3: note: previous definition is here
} cudaDataType;
  ^
cupy/cuda/cublas.cpp:6430:26: error: no matching function for call to 'cublasSgemmEx'
        __pyx_v_status = cublasSgemmEx(((cublasHandle_t)__pyx_v_handle), ((cublasOperation_t)__pyx_v_transa), ((cublasOperation_t)__pyx_v_transb), __pyx_v_m, __pyx_v_n, __pyx_v_k, (&__pyx_v_alpha), ((void const *)__pyx_v_A), ((cudaDataType)__pyx_v_Atype), __pyx_v_lda, ((void const *)__pyx_v_B), ((cudaDataType)__pyx_v_Btype), __pyx_v_ldb, (&__pyx_v_beta), ((void *)__pyx_v_C), ((cudaDataType)__pyx_v_Ctype), __pyx_v_ldc);
                         ^~~~~~~~~~~~~
/usr/local/cuda/include/cublas_api.h:1587:39: note: candidate function not viable: no known conversion from 'cudaDataType' (aka 'cudaDataType_t') to 'cublasDataType_t' for 9th argument
CUBLASAPI cublasStatus_t CUBLASWINAPI cublasSgemmEx  (cublasHandle_t handle,
                                      ^
2 errors generated.
error: command 'clang' failed with exit status 1
```

@delta2323 
Now I'm working a bit to fix this, so could you please reopen this?

**Comment by wkentaro** [comment]
I found below from git log:

- Install Fail: 407e061
- Install Success: cae54cd24

**Comment by unnonouno** [comment]
MacOS CUDA uses `cublasDataType_t` though Linux CUDA uses `cudaDataType_T`?

**Comment by unnonouno** [comment]
Ah, OK i found this line in cublas_api.h in CUDA 8. It represents `cudablasDataType_t` is old type name. 
```
/* For backward compatibility purposes */
typedef cudaDataType cublasDataType_t;
```
And in my Mac environment, i can't find `/usr/local/cuda/include/library_types.h`.
