### ISSUE TITLE
Image zoom function 

### ISSUE THREAD

**Issue by nushio3** [pfnet/chainer#172]
I would like to have a zoom function in Chainer functions.
http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.interpolation.zoom.html

The zoom function enlarges the images into each spatial dimension, possibly with different multiplier.

Zoom has many usecase --- especially, a zoom is the (right-)inverse of pooling, so the zoom can be used to implement the autoencoder for layers that includes pooling. It can also be used to produce new images from the neural network. 

By the way, 2x zoom (and theoretically, any integer zoom) can already be implemented using existing Chainer primitives. Here is some tiny implementation together with tests.

https://gist.github.com/nushio3/d87c3bd1bd43eb034955

**Comment by delta2323** [comment]
Great! We would like to discuss and determine detailed specification of zoom function. Your reference code would certainly be useful for the discussion.

**Comment by beam2d** [comment]
We have now unpooling_2d (which does upsampling). http://docs.chainer.org/en/stable/reference/functions.html#unpooling-2d
