### ISSUE TITLE
ComputationalGraph make wrong graph around output value

### ISSUE THREAD

**Issue by Hiroshiba** [pfnet/chainer#1751]
``` python
import numpy
import chainer
import chainer.computational_graph as C

x = numpy.random.randn(10, 1).astype(numpy.float32)
h = chainer.links.Linear(1, 2)(x)

graph = C.build_computational_graph(h)
with open('graph.dot', 'w') as o:
    o.write(graph.dump())
```

and draw graph with `Graphviz`

``` sh
dot -Tpng graph.dot -o outfile.png
```

get like this image
![outfile](https://cloud.githubusercontent.com/assets/4987327/19213138/25e5c00c-8d9e-11e6-8195-54cc0e8e8ffa.png)

These 10 `GetItem` and `(2), float32` are not needed.

**Comment by delta2323** [comment]
Hi, thank you for trying Chainer.

`build_computational_graph` function expects its first argument to be an iterable (e.g. list) of `Variable`s. But as `Variable` has `__getitem__` method that returns `Variable`, the function can accept `Variable` itself unexpectedly. As `Variable.__getitem__` calls `F.GetItem` internally, the resulting graph has as many `GetItem` nodes as the length (i.e. Variable.data.shape[0]) of `Variable`.

**Comment by Hiroshiba** [comment]
I got it. Thank you for the detailed explanations.
