### ISSUE TITLE
__init__ style

### ISSUE THREAD

**Issue by boeddeker** [pfnet/chainer#1763]
Is there a reason, why the __init__.py has the style (concat is only an example)

```
from chainer.functions.array import concat

...

Concat = concat.Concat
concat = concat.concat
```

and not 

`
from chainer.functions.array.concat import Concat, concat
`
?

The reason, why I ask is, that PyCharm is not able to analyse this import style and therefore PyCharm says always: 'concat' is not callable and an jump to the function goes to the file and not to the function.

**Comment by beam2d** [comment]
We fixed this issue. Thank you for reporting it!
