### ISSUE TITLE
Inconsistent behavior of `__len__` between `Variable`  and `ndarray`

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1792]
`ndarray.__len__` returns the first dimension of the shape, but `Variable.__len__` returns the size of elements. It is confusing, and users need to use `x.shape[0]` to get the first dimension for compatible codes with both types.

**Comment by unnonouno** [comment]
How about adding future warning? I want to fix this behavior in the next major release.

**Comment by delta2323** [comment]
I agree with you. It is not only for this specific topic but it would be reasonable that the first step toward the next major version up would be to add future warning to what we would like to fix in Chainer 2.0.
