### ISSUE TITLE
Implement cupy.sort

### ISSUE THREAD

**Issue by takagi** [pfnet/chainer#1815]
NumPy has `numpy.sort` and `numpy.ndarray.sort` that sort an array non-destructively and destructively. Currently CuPy leaves operations for the tasks unimplemented.

**Comment by takagi** [comment]
`numpy.sort` has the following arguments other than an array to be sorted:

- axis: Axis along which to sort.
- kind: Sorting algoritm.
- order: When `a` is an array with fields defined, specifies which fields to compare.

It is needed to consider how to support these arguments in CuPy, especially `kind` argument.

**Comment by takagi** [comment]
Thrust has sort functions, `sort` and `stable_sort`, but they do not provide any switch that allows users to choose detail algorithm actually used as NumPy. I'm not sure what algorithms, or combination of algorithms, are used in thrust's sort functions.

**Comment by takagi** [comment]
There are the following possible approaches to implement `cupy.sort`:

**Approach A**
Implementing cupy.sort based on numpy.sort.

- First, implement merge sort without supporting `axis` and `kind` arguments.
- Then, support `axis` argument and other algorithms in `kind` argument.
- `order` argument would be left unsupported because CuPy does not support structured arrays.

**Approach B**
First using thrust quickly, then reimplementing based on numpy.sort later.

- First, support stable sort using thrust.
- Then, reimplement based on numpy with supporting `kind` and `axis`
- `order` argument would be left unsupported because CuPy does not support structured arrays.

Approach C
Using thrust.

- Support stable and unstable sort using thrust
- Not follow `kind` argument

**Comment by jekbradbury** [comment]
I suspect that many use cases for `cupy.sort` might actually be better served by something like `ndarray.top_k` (which can be implemented more efficiently) even though numpy doesn't have that natively. But there are presumably also reasons for sorting a whole array, so it's good to have that too.

**Comment by muupan** [comment]
One reason for sorting a whole array is to implement DNCs (differential neural computers) where argsort is needed to determine which memory column to write.

**Comment by takagi** [comment]
Thanks for comments, I would like to go with implementing `cupy.sort` here without putting the question if CuPy should support its `sort` operation or not, one of the reasons is CuPy's design philosophy that it should support operations NumPy supports as much as possible with some practical priorities. It would be nice that `top_k` operations mentioned above would be discussed as another topic.

**Comment by takagi** [comment]
I implemented a sample code to call Thrust via Cython:
https://github.com/takagi/cython-thrust
