### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by vzhong** [pfnet/chainer#1818]
Hi,

I really appreciate your work on Chainer. We have been using your framework for our research and would like to cite your work. Is there a preferred source you'd like us to cite?

**Comment by unnonouno** [comment]
here! https://github.com/pfnet/chainer#reference

**Comment by vzhong** [comment]
Great! Thanks!

**Comment by ZaydH** [comment]
There are now a few different citations for Chainer in the reference section.  I plan to use NeurIPS 2015 citation.  Is that what you prefer @unnonouno ?  

Would you also like a PR to change the [citation](https://github.com/chainer/chainer/blob/master/chainer_bibtex.txt) from the deprecated NIPS to the now standard NeurIPS?
