### ISSUE TITLE
Doc is not updated: Loading Caffe models

### ISSUE THREAD

**Issue by crcrpar** [pfnet/chainer#1820]
According to chainer document, we can load trained caffe models via `chainer.functions.caffe.CaffeFunction(model_path)`, and I followed the instruction only to get the following response.

> AttributeError                            Traceback (most recent call last)
<ipython-input-12-6cf1373458b9> in <module>()
----> 1 VGG16model = chainer.functions.caffe.CaffeFunction(VGG16)

> AttributeError: module 'chainer.functions' has no attribute 'caffe'  

where, VGG16 is the path to the model.

Yes, I know `CaffeFunction` is in `chainer.links.caffe`.
Would you mind your changing the doc: http://docs.chainer.org/en/stable/reference/caffe.html

**Comment by unnonouno** [comment]
Oh, sorry. You are right. I'll fix it.
