### ISSUE TITLE
number of optimizers for a sequence of neural networks?

### ISSUE THREAD

**Issue by weiHelloWorld** [pfnet/chainer#1827]
Hi,

Assume I have a bunch of neural networks N1, N2, N3, and the input dataset is x, and I chain these neural networks sequentially to get the output:

y = N3(N2(N1(x)))

Now if I would like to update the weights for all three networks, should I define three optimizers for all of them separately or I only need to define one optimizer and bind it to the last network?  I did a simple test and it seemed that three optimizers are needed but I just want to make sure.

Thanks!

**Comment by fabiencro** [comment]
This seems more a question for the mailing list, I think. But anyway, yes, AFAIUC, an optimizer can indeed only be attached to one Link at a time. But what you should probably do is to use a Chain class to merge your 3 networks in one.
```
class MyNetwork(chainer.Chain):
    def __init__(self):
          super(MyNetwork, self).__init__(
             N1 = chainer.links.Linear(4,6) , # for example
             N2 = .......... ,     # replace with whatever link you are using for N2
             N3 = ............ ,
            )
   def __call__(self, x):
          return self.N3(self.N2(self.N1(x)))
```
(Warning: untested code quickly written from memory, but that should give you the idea)

Then applying or training an object of the class MyNetwork will automatically apply and train its N1, N2 and N3 members.
