### ISSUE TITLE
ResNet's download URL is missing.

### ISSUE THREAD

**Issue by aonotas** [pfnet/chainer#1904]
In example code, ResNet's url is missing now. (download_model.py)
See this example page.
https://github.com/pfnet/chainer/blob/master/examples/modelzoo/download_model.py#L27

This url is missing.
http://research.microsoft.com/en-us/um/people/kahe/resnet/models.zip

Maybe we should set another model url.

**Comment by unnonouno** [comment]
fix via #2196
