### ISSUE TITLE
Ubuntu 16.04 + cupy 

### ISSUE THREAD

**Issue by tjgalvin** [pfnet/chainer#1962]
Hi all. Been banging my head agaisnt the wall trying to sort this out. 

I am trying to install Chainer/cupy with CUDA support. As far as I see my CUDA environment is set up correctly. `nvidia-smi` shows the correct output (ie. picking up the video card). 

My `PATH` is set up as well:

`/usr/src/miriad/linux64/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

and can pick up `nvcc` by invocation on the command line. 

Installing Chainer through `pip install --user -vvvv --no-cache-dir chainer` doesn't appear to show any problems. The beginning of the `pip` output below:

    Running setup.py (path:/tmp/pip-build-68qLGz/chainer/setup.py) egg_info for package chainer
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/chainer.egg-info
    writing requirements to pip-egg-info/chainer.egg-info/requires.txt
    writing pip-egg-info/chainer.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/chainer.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/chainer.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/chainer.egg-info/SOURCES.txt'
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
    Include directories: ['/usr/local/cuda/include']
    Library directories: ['/usr/local/cuda/lib64']
    creating /tmp/tmpR22XRu/tmp
    creating /tmp/tmpR22XRu/tmp/tmpR22XRu
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpR22XRu/a.cpp -o /tmp/tmpR22XRu/tmp/tmpR22XRu/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpR22XRu/tmp/tmpR22XRu/a.o -o /tmp/tmpR22XRu/liba.so
    creating /tmp/tmp0wp0Kb/tmp
    creating /tmp/tmp0wp0Kb/tmp/tmp0wp0Kb
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmp0wp0Kb/a.cpp -o /tmp/tmp0wp0Kb/tmp/tmp0wp0Kb/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmp0wp0Kb/tmp/tmp0wp0Kb/a.o -L/usr/local/cuda/lib64 -lcublas -lcuda -lcudart -lcurand -lnvToolsExt -o /tmp/tmp0wp0Kb/liba.so
    creating /tmp/tmpCV_ZU2/tmp
    creating /tmp/tmpCV_ZU2/tmp/tmpCV_ZU2
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmpCV_ZU2/a.cpp -o /tmp/tmpCV_ZU2/tmp/tmpCV_ZU2/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread /tmp/tmpCV_ZU2/tmp/tmpCV_ZU2/a.o -o /tmp/tmpCV_ZU2/a
    Include directories: ['/usr/local/cuda/include']
    Library directories: ['/usr/local/cuda/lib64']
    creating /tmp/tmptdiHao/tmp
    creating /tmp/tmptdiHao/tmp/tmptdiHao
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/local/cuda/include -c /tmp/tmptdiHao/a.cpp -o /tmp/tmptdiHao/tmp/tmptdiHao/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmptdiHao/tmp/tmptdiHao/a.o -o /tmp/tmptdiHao/liba.so
    creating /tmp/tmpw2rG0J/tmp
    creating /tmp/tmpw2rG0J/tmp/tmpw2rG0J
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmpw2rG0J/a.cpp -o /tmp/tmpw2rG0J/tmp/tmpw2rG0J/a.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security /tmp/tmpw2rG0J/tmp/tmpw2rG0J/a.o -L/usr/local/cuda/lib64 -lcudnn -o /tmp/tmpw2rG0J/liba.so

Looking in the `lib/python2.7/site-packages/cupy/core` directory I see that `core.so`,`flags.so` and `internal.so` have been compiled. 

Yet, when I try to import cupy, I get the following error:

`RuntimeError: CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
`

Any thoughts or suggestions on how to proceed would be very much appreciated. I don't understand what is wrong with my environment. I have managed to compile OpenCV with the cuda bindings without issue very recently.

**Comment by tjgalvin** [comment]
For reference to all, I think I have fixed it. I am still not sure what exactly I did that fixed it. I simply removed nvidia/cuda completely and reinstalled. I also reinstalled g++. Upon reinstalling CUDA I asked it to installed the package driver. A simply pip install --no-cache-dir --user chainer worked.

**Comment by wkentaro** [comment]
On my environment, I can use Cupy (Ubuntu 16.04, AWS p2.xlarge).
I've installed Chainer with `sudo pip install chainer`.

```bash
% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

% echo $PATH
/home/wkentaro/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

% echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:

% python -c 'import cupy; print cupy'
<module 'cupy' from '/usr/local/lib/python2.7/dist-packages/cupy/__init__.pyc'>
```

**Comment by unnonouno** [comment]
Sorry for late reply. It looks you successfully compiled the library. I can find no error.
Maybe it is a problem of your running environment. Can you check LD_LIBRARY_PATH?

**Comment by tjgalvin** [comment]
@ unnonouno - no problem. I ended up completely removing CUDA, and reinstalling with the .run file. Everything else was exactly the same, and cupy compiled correctly and is importable from python. Was at a loss because I don't think I edited by bash rc scripts (ie. the PATH and LD_LIBRARY_PATH were unchanged). I am not questioning it though as it works now!

**Comment by unnonouno** [comment]
Oh, great! Is it Ok to close this issue?

**Comment by tjgalvin** [comment]
Yes - no objections here. Big thanks for the package.
