### ISSUE TITLE
Uninitialized variable and parameter

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#1967]
I wrote a proposal of uninitialized variable and parameter. The uninitialized variable is a variable that does not have the data array. It can be used to represent an uninitialized parameter, which appears when using parameter shape placeholder (i.e., the weight matrix with unknown input size that will be inferred at the first iteration). It makes the handling of uninitialized parameters as easy as handling initialized parameters.

The details are explained in the following design document: https://docs.google.com/document/d/1-3fG8zs7jq3kM9jie1_No6beWn2jHtX1WqXWeXlhpCU/edit?usp=sharing. I don't think it breaks the compatibility, but it changes the way to implement parameter shape placeholder support, so it would be better to introduce it in v2.

**Comment by delta2323** [comment]
Solved by #2072
