### ISSUE TITLE
mean_absolute_error.py might be missing in chainer-1.18.0 pip package

### ISSUE THREAD

**Issue by tabetomo** [pfnet/chainer#1987]
It seems chainer/functions/loss/mean_absolute_error.py is missing at pip install ("the install command is pip install chainer -vvvv") at least for Mac.

1) Not included pip package
It seems the pip installs chainer package from  https://pypi.python.org/simple/chainer/. But chainer-1.18.0.tar.gz there doesn't contain the file mean_absolute_error.py.

2) Not included in Mac folder
In Mac, the chainer seems installed in /usr/local/lib/python3.5/site-packages/chainer/. But there are no file mean_absolute_error.py there too.

3) Cannot use mean_absolute_error
When I used F.mean_absolute_error(x_out, t_out), an error arose:

  File "/Users/xxxx/chainer/chainer-pix2pix/updater.py", line 26, in loss_enc
    loss_rec = lam1*(F.mean_absolute_error(x_out, t_out))
AttributeError: module 'chainer.functions' has no attribute 'mean_absolute_error'

**Comment by tabetomo** [comment]
I tried to manually install mean_absolute_error. What I did is the follows (I'm not sure it's the right way but it looks work).

1.  Add the following bold lines 
`in /usr/local/lib/python3.5/site-packages/chainer/functions/__init__.py`

from chainer.functions.loss import mean_squared_error
**from chainer.functions.loss import mean_absolute_error**

MeanSquaredError = mean_squared_error.MeanSquaredError
mean_squared_error = mean_squared_error.mean_squared_error
**MeanAbsoluteError = mean_absolute_error.MeanAbsoluteError
mean_absolute_error = mean_absolute_error.mean_absolute_error**

2. Copy **mean_absolute_error.py**
`in /usr/local/lib/python3.5/site-packages/chainer/functions/loss/`

3. Compile the .py file to get __pycache__/*.pyc file

python -m compileall /usr/local/lib/python3.5/site-packages/chainer/functions/loss/mean_absolute_error.py 

`mean_absolute_error.cpython-35.pyc` was generated in the __pycache__ folder.

**Comment by rezoo** [comment]
Hi tabetomo,
`mean_absolute_error()` is not included in chainer v1.18.0. Please wait until a next minor release, or directly clone a master branch on github.
