### ISSUE TITLE
Can not import chainer.functions.PReLU on 1.19.0

### ISSUE THREAD

**Issue by kamo-naoyuki** [pfnet/chainer#2007]
I can not import PReLU from chainer.functions on 1.19.0.

In https://github.com/pfnet/chainer/blob/master/chainer/functions/__init__.py,
the corresponding lines are comment-outed.
 
```
# Import for backward compatibility
# om chainer.links.activation.prelu import PReLU  # NOQA
```

Is there a reason?

**Comment by unnonouno** [comment]
Oh, sorry. This is a mistake.
