### ISSUE TITLE
Variable-wise update rule

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2008]
This is a proposal for v2 to modify Optimizer so that we can choose different update equations and hyperparameters for different parameter variables. In this proposal, UpdateRule class is introduced, which represents the update equations used for one parameter variable. An instance of it is set to a target parameter, and Optimizer uses it to update the parameter. Each variable in the target link has its own update rule, and so we can modify its hyperparameters and add a hook function dedicated to the update rule.

Here is the design document for this proposal: https://docs.google.com/document/d/1t1UrpsKzoDZGK7fHDbN0by93253V37Kkg-7qFpOTytc/edit#.

**Comment by delta2323** [comment]
Resolved by #2137
