### ISSUE TITLE
Remove deprecated cuda module functions

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2016]
There are many deprecated functions in chainer.cuda module, which were originally used for unified interface for numpy and pycuda. They can be removed in v2.

**Comment by delta2323** [comment]
I found `DummyDeviceType` is not used in `Chainer` nor `CuPy` [search result](https://github.com/pfnet/chainer/search?utf8=✓&q=DummyDeviceType&type=Code). Is it obsolete module?
