### ISSUE TITLE
Remove trigger option of snapshot and snapshot_object

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2017]
They have the same functionality as the trigger argument of Trainer.extend and are redundant. I think they confuse users and they might misunderstand the trigger feature, and so they should be removed in the next major update.

**Comment by unnonouno** [comment]
Do you think we need to remove trigger argument in `Trainer.extend` or `Extension.trigger` attribute?

**Comment by beam2d** [comment]
What I meant is to remove the trigger **argument** of `snapshot` and `snapshot_object`, not the trigger **attribute**. Sorry for the confusing title.

Note: the trigger argument of `Trainer.extend` and `Extension.trigger` have different purposes. The former is to customize the trigger, and the latter is the default value for the case when users don't pass a trigger to `Trainer.extend`. Therefore, neither of them should be removed.

**Comment by unnonouno** [comment]
fixed via #2204
