### ISSUE TITLE
Make bias vector enabled by default in ConvolutionND and DeconvolutionND

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2018]
In ConvolutionND and DeconvolutionND, the bias parameter is unexpectedly disabled by default. This should be fixed, but fixing it may break user codes. It can be fixed at least in v2.

**Comment by unnonouno** [comment]
I'm planning to add `bias` and `nobias` parameters to ConvolutionND same as Convolution2D. Is it OK?

**Comment by delta2323** [comment]
I think it is better to clean up the APIs of `Convolution2D` and `Linear` links, especially arguments related to `bias` (`bias`, `nobias` and `initial_bias`), as I discussed [here](https://github.com/pfnet/chainer/issues/2020#issuecomment-273647265). Could you discuss it with me?

**Comment by delta2323** [comment]
One option is to change the default value of `initial_bias` to `0` or `initializers.Constant(0)`.

**Comment by delta2323** [comment]
This issue has been solved by #2185. So I close it.
