### ISSUE TITLE
Remove wscale options

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2020]
Linear, Convolution2D, and many similar links have an initialization option `wscale`, which is used to scale the initial weight matrices relatively from the default initialization. This option is now just confusing, since we now have weight initializers that can effectively select arbitrary scaling of the initial parameters. This is even broken in some cases (see #1806). I think it's time to remove this option, and just use a non-default initializer to select the appropriate scaling.

**Comment by delta2323** [comment]
After removing `wscale` option, I would like to clean up the API of `Linear.__init__` etc., especially, `bias`, `nobias`, and `initial_bias` option.

**Comment by delta2323** [comment]
Do you think it is reasonable to remove `scale` option from `_get_initializer` as well?

**Comment by beam2d** [comment]
Yes, I think so.

**Comment by delta2323** [comment]
OK, I will try to do it, either in this PR or possibly as another one.
