### ISSUE TITLE
Make force_tuple True by default in split_axis

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2022]
F.split_axis has an option `force_tuple`, which is set to False by default. In many cases, one wants to assume that the return type of this function is always tuple, which requires explicitly setting `force_tuple=True`. The default behavior has the inconsistent return types (Variable for one output and Tuple[Variable] for multiple outputs). I want to make the default value of this option True so that it consistently returns a tuple of variables by default.

This is based on the original request by @jekbradbury (https://gist.github.com/beam2d/f7b817c3ce6ada32a1f9c8cc7dea4a5a#gistcomment-1932338).

**Comment by unnonouno** [comment]
fixed via #2187
