### ISSUE TITLE
Normalization flag not implemented correctly in softmax_cross_entropy

### ISSUE THREAD

**Issue by amrsharaf** [pfnet/chainer#2029]
When the ``normalize'' flag is set to False, the softmax_cross_entropy function still normalizes the scores by dividing by the total count! This behavior is totally different from similar flags in other deep learning frameworks like Torch (see ClassNLLCriterion). It seems like the normalize flag is currently used to either divide by the total count, or the count of unignored entries, which is really confusing and unexpected.

**Comment by niboshi** [comment]
Closing the issue; related discussion is taking place in #1565.
