### ISSUE TITLE
Softmax does not support non-contiguous arrays

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2034]
Functions related to softmax (softmax, log_softmax, softmax_cross_entorpy, etc.) cause an error when cuDNN is enabled and the input is non-contiguous. The problem looks same as #850, which was fixed for convolution_2d.

**Comment by unnonouno** [comment]
It seems to be solved. Do we need to make a test case? https://github.com/pfnet/chainer/blob/master/cupy/cudnn.py#L229
