### ISSUE TITLE
Support advanced indexing for chainer.Variable's __getitem__

### ISSUE THREAD

**Issue by yuyu2172** [pfnet/chainer#2042]
I would like to discuss how to support advanced indexing of `chainer.Variable` and some addition that is necessary for `cupy`'s API.

## Current Status
+ `chainer.Variable.__getitem__` supports basic indexing (combination of `slice(None)` (i.e. `:`), `None`, integer, slice, and Ellipsis).
+ It does not support integer array as index. So, `x[[1,2]]` is not supported. Also, it does not support multiple array as indexing. (e.g.. `x[[1, 2], [3, 1]]`)
+ It does not support boolean mask indexing.
+ It does not support combination of basic indexing and array indexing.

## What needs to be added
For forward pass, it is pretty much done because `cupy.__getitem__` supports most of the advanced indexing and combination of basic/adv indexing.

For backward pass, additional `cupy` function is necessary.
Putting the topic in context, here is an example for basic indexing. When we have forward pass as `y = x[0]`, then backward pass would be `gx = zeros_like(x); gx[0] = gy`. 

The basic indexing uses `__setitem__` to propagate gradients, however it is not the case when we use integer array index and the index has duplicate elements.
For example, `y = x[[1, 0, 1]]` has backward pass `gx[0] = gy[1]; gx[1] = gy[0] + gy[2]`, and it can not be expressed by `__setitem__`.
`gx` is calculated using `i=[1, 0, 1]` and `gy` by `gx[i[k]] += gy[k]` for `k=1,2,3`.
I would like to call a function that does the operation `scatter_add`, and this function is missing in `cupy`. 

The backward pass of `Variable.__getitem__` is calculated similarly in the case when there are multiple arrays or combination of basic/advanced indexing.
Here is a prototype for forward/backward pass for `Variable.__getitem__`.

```python
class GetItem(function.Fucntion): 
    def __init__(self, slices):
        self.slices = slices

    def forward(self, xs):
         ary = xs[0]
         return ary[self.slices],

    def backward(self, xs, gys):
         gy = gys[0]
         gx = zeros_like(xs[0])
         scatter_add(gx, self.slices, gy)
         return gx,
```

## Addition to CuPy API

In order to implement above functionality, `scatter_add` needs to be implemented. It should have identical interface as `__setitem__`, which takes tuple `slices` as an argument.

**Comment by muupan** [comment]
Resolved by #2203
