### ISSUE TITLE
Partial deserialization of links

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#2053]
We sometimes want to deserialize a link only partially, i.e. we want to load a smaller set of parameters to a larger link. It happens when we do some surgery to neural nets (e.g. fine-tuning), in which case the set of parameters in the source network does not match to the set of parameters in the target network.

One possible design is to introduce a `strict` option to the deserializer, and if that flag is False, any mismatch of the sets of parameters is ignored. I think it is safer to turn on this flag by default (I mean, we should not change the default behavior).

**Comment by unnonouno** [comment]
There are two types of mismatch.
- Some parameters in a model are not found in serialized data
- Some redundant parameters in serialized data are not required for a model

Is it OK to ignore both situation with `strict=False` option?

**Comment by unnonouno** [comment]
And I think we can implement this option before v2 because we can keep compatibility.
