### ISSUE TITLE
Bug in MeanSquaredError - Type of data and grad mismatch

### ISSUE THREAD

**Issue by AlexGonRo** [pfnet/chainer#2058]
Good morning, 

I'm not that confident with this library, but while working with it I got the following error message:

```
Traceback (most recent call last):
  File "$MY_RUTE_TO_THE_PROJECT$/__init__.py", line 87, in <module>
    optimizer.update(F.mean_squared_error, chainer.Variable(tmp), chainer.Variable(tmp2))
  File "/opt/anaconda2/lib/python2.7/site-packages/chainer/optimizer.py", line 397, in update
    loss.backward()
  File "/opt/anaconda2/lib/python2.7/site-packages/chainer/variable.py", line 398, in backward
    _check_grad_type(func, x, gx)
  File "/opt/anaconda2/lib/python2.7/site-packages/chainer/variable.py", line 41, in _check_grad_type
    raise TypeError(make_message(msg))
TypeError: Function `MeanSquaredError` (MeanSquaredError) has a bug.

Please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/pfnet/chainer/issues/new.
Type of data and grad mismatch
<type 'numpy.ndarray'> != <type 'numpy.float32'>

Process finished with exit code 1
```
You can get it executing this example code:

```
import numpy as np
import chainer
from chainer import optimizers
from chainer import Chain
import chainer.functions as F
import chainer.links as L


class MyNetwork(Chain):
    def __init__(self, n_units, n_out):
        super(MyNetwork, self).__init__(
            # the size of the inputs to each layer will be inferred
            l1=L.Linear(None, n_units),
            l2=L.Linear(None, n_units),
            l3=L.Linear(None, n_out),    
        )

    def __call__(self, x):
        h1 = F.relu(self.l1(x))
        h2 = F.relu(self.l2(h1))
        y = self.l3(h2)
        return y

myNet = MyNetwork(150, 4)
model = L.Classifier(myNet)  # the input size, is inferred
optimizer = optimizers.SGD()
optimizer.use_cleargrads()
optimizer.setup(model)

tmp = np.array(1, dtype='float32')
tmp2 = np.array(2, dtype='float32')

optimizer.update(F.mean_squared_error, chainer.Variable(tmp), chainer.Variable(tmp2))
```

As I said, I might be doing something wrong, due to my lack of experience, but that error message makes me wonder whether is my problem or not.

I run it using Python 2.7.12 and numpy 1.11.1

**Comment by delta2323** [comment]
Hi, thank you for trying Chainer.

In the code above. Variables are fed to `mean_squared_error` not `MyNetwork`, although `MyNetwork` is registered to `optimizer`. So, parameters in `MyNetwork` are not updated at all. Could you explain the expected behavior?

**Comment by AlexGonRo** [comment]
Thank you for the answer. Then, it might be my problem and not the library's.

I want to create a neural network that updates its weights after every prediction (I don't have the following inputs to the network because they depend on the output of this epoch). Thus, what I am trying to do here is to train the network using a batch of just one datapoint (so yes, I expect the network `MyNetwork ` to be updated). 

Let's suppose the value `tmp1` is the prediction of my network and `tmp2` is the expected value. Then, I want to calculate the `mean_squared_error` and update the network so I can minimize it in future iterations (that's what I thougth I was doing in `optimizer.update(F.mean_squared_error, chainer.Variable(tmp), chainer.Variable(tmp2))` ). The code I just posted should be inside a loop that continiously trains the network using batches of just 1 instance.

**Comment by delta2323** [comment]
I think it works if you wrap `MyNetwork` with another Chain that calculates the mean squared error, if my understanding is correct. The pseudo code is as follows:

```
class Evaluator(chainer.Chain):
    def __init__(self, my_network):
        super(Evaluate, self).__init__(my_network=my_network)

    def __call__(self, x, y):  # x is feature vector, y is target value
        y_pred = self.my_network(x)
        loss = F.mean_squared_error(y_pred, y)
        return loss

my_network = MyNetwork()
evaluator = Evaluator(my_network)

optimizer = O.SGD()
optimizer.setup(evaluator)

# prepare training minibatch
x = chainer.Variable(...)
y = chainer.Variable(...)

optimzier.update(evlaluator, x, y)
```
