### ISSUE TITLE
check_type_backward may be removed

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#209]
Current type-checking system allows one to define type checking on backward by `Function.check_type_backward`. Type checking at forward makes users easy to debug the type error in their network definition. On the other hand, almost all type errors on backward are not due to the users' failure but due to the bugs of Functions. I want to keep the type-checking system a debugging tool for users, not for developers. Writers of Function definition must write unit tests for its failures instead of type checking on backward.

There is only one exception for the above notion: a user can cause a type error on backward by setting wrong `grad` of the root variable (i.e., the variable whose `backward` the user calls). In such case, what we have to do is checking whether its dtype and shape match to those of `data`. This can be done at the setter of `grad`, which is far more helpful for the debugging.

As a consequence, I suggest to modify the interface as following:

* Remove `Function.check_type_backward`.
* Make the `Variable.grad` a property whose setter checks the dtype and shape of the argument.

Clarifying the types of outputs is future work. It may be done by document, though it cannot be verified automatically.

**Comment by beam2d** [comment]
This issue is based on an offline conversation with @unnonouno (thank you!).

**Comment by delta2323** [comment]
Now I am implementing type checking of various functions in #123. As discussed in this issue, we do not have to iplement `check_type_backward` from later on. Is my understanding correct?
