### ISSUE TITLE
Error when trying to install Chainer

### ISSUE THREAD

**Issue by ErikBachRyhl** [pfnet/chainer#2119]
Hi guys I tried to install chainer but I am getting the error below:

error: command 'C:\\Users\\Erik\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120

This is what happens when i run python setup.py egg_info:

a.cpp
a.cpp
a.cpp
a.cpp
a.cpp
a.cpp
Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
running egg_info
writing requirements to chainer.egg-info\requires.txt
writing chainer.egg-info\PKG-INFO
writing top-level names to chainer.egg-info\top_level.txt
writing dependency_links to chainer.egg-info\dependency_links.txt
reading manifest file 'chainer.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'chainer.egg-info\SOURCES.txt'

My OS is Windows 10...

**Comment by gwtnb** [comment]
CUDA 6.5 or later does not support Visual C++ for Python 2.7 (Visual Studio 2008). It is desirable to use Python 3 with [appropriate version of Visual Studio](https://wiki.python.org/moin/WindowsCompilers) when using Chainer with GPU on Windows.
