### ISSUE TITLE
mxm_handle_error / segfault 

### ISSUE THREAD

**Issue by undertherain** [pfnet/chainer#2133]
I’m getting a rather cryptic error while running Chainer. 
Segmentation fault happens when exiting the Python script (after the last line been executed). 

I’m having this issue on several systems with slightly different software setup. On one system it just reports “segmentation fault”, on other system it prints a bit of a backtrace as follows:

Caught signal 11 (Segmentation fault)

 2 0x00000000000672cc mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.4.3069/src/mxm/util/debug/debug.c:641
 3 0x000000000006781c mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.4.3069/src/mxm/util/debug/debug.c:616
 4 0x0000000000035670 killpg()  ??:0
 5 0x00000000001963ea cudbgApiDetach()  ??:0
 6 0x00000000000bcaa6 ??()  /usr/lib64/nvidia/libcuda.so.1:0
 7 0x00000000001f16c2 cuEventDestroy_v2()  ??:0
 8 0x0000000000374be4 cublasGemmEx()  ??:0
 9 0x00000000003a3484 cublasGemmEx()  ??:0
10 0x0000000000036437 ??()  /usr/local/cuda-8.0/lib64/libcublas.so.8.0:0
11 0x00000000000721bd cublasDestroy_v2()  ??:0
12 0x0000000000010f99 __pyx_f_4cupy_4cuda_6cublas_destroy()  /tmp/pip-build-nkpft4dh/chainer/cupy/cuda/cublas.cpp:1597
13 0x0000000000010f99 __pyx_f_4cupy_4cuda_6cublas_destroy()  /tmp/pip-build-nkpft4dh/chainer/cupy/cuda/cublas.cpp:1606
14 0x000000000000521b __pyx_pf_4cupy_4cuda_6device_6destroy_cublas_handles()  /tmp/pip-build-nkpft4dh/chainer/cupy/cuda/device.cpp:3134
15 0x000000000000521b __pyx_pw_4cupy_4cuda_6device_7destroy_cublas_handles()  /tmp/pip-build-nkpft4dh/chainer/cupy/cuda/device.cpp:3027
16 0x00000000000c25f1 PyCFunction_Call()  /work/alex/src/Python-3.5.2/Objects/methodobject.c:121
17 0x000000000006dfaa PyObject_Call()  /work/alex/src/Python-3.5.2/Objects/abstract.c:2165
18 0x00000000001d9e77 atexit_callfuncs()  /work/alex/src/Python-3.5.2/./Modules/atexitmodule.c:89
19 0x00000000001830e9 call_py_exitfuncs()  /work/alex/src/Python-3.5.2/Python/pylifecycle.c:1407
20 0x00000000001830e9 Py_Finalize()  /work/alex/src/Python-3.5.2/Python/pylifecycle.c:538
21 0x00000000001a51c2 Py_Main()  /work/alex/src/Python-3.5.2/Modules/main.c:788
22 0x0000000000400af1 main()  /work/alex/src/Python-3.5.2/./Programs/python.c:65
23 0x0000000000021b15 __libc_start_main()  ??:0
24 0x0000000000400b91 _start()  ??:0

Segmentation fault

It happens after running a trainer - if I just import chainer, create models etc but do not train - it's ok.
For example if I run a mnist example from Chainer repo: https://github.com/pfnet/chainer/blob/master/examples/mnist/train_mnist.py

Also, if I try own larger models - it does not even exit the script, but uses 100% CPU after the last line of Python code had been executed. 

From the backtrace it looks like there's some problem with Mellanox Infiniband drivers, but I'm not sure where to look further. 
Other CUDA and MPI apps seem to work fine, including deep learning Frameworks such as MXNet, Theano and Tensorflow.

The system is 
CentOS Linux release 7.2.1511 (Core) with  3.10.0-327.18.2.el7.x86_64  kernel
Cuda compilation tools release 8.0, V8.0.44
openmpi-1.8.8 (if it's relevant)
gcc version 5.4.0
Python 3.5.2
Chainer '1.20.0' (I think the same problem was with 1.19)
also tried with and without CuDNN with same effect 
and different GPUs ( Tesla P100-PCIE and GeForce GTX 980 Ti ) with same effect

only happens when training on GPU
also, error seems to be "floating" (race condition?) - one of about 5 runs finished normally.

**Comment by rampage644** [comment]
I'm also experiencing segfault on script exit, but i didn't do thorough investigation when exactly it happens. I suppose it started after 1.19 -> 1.20 upgrade.

    $ uname -a
    Linux dnn4 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ python3 --version
    Python 3.5.2
    $ nvcc --version
    Cuda compilation tools, release 8.0, V8.0.44
    $ head -n59 /usr/local/cuda/include/cudnn.h | tail -n3
    #define CUDNN_MAJOR      5
    #define CUDNN_MINOR      1
    #define CUDNN_PATCHLEVEL 5

**Comment by undertherain** [comment]
Indeed, I’ve rolled back to chainer==1.19.0 and it works fine, so the problem was introduced in 1.20.0 
although the code which was freezing on exit rather that seg-faulting is still doing so, but maybe that's my mistake somewhere, let me check...

**Comment by undertherain** [comment]
seems to be fixed in '1.20.0.1', whatever was the problem

**Comment by undertherain** [comment]
1.24 and 2.0 works ok, so looks like whatever was the problem - it had been fixed
