### ISSUE TITLE
How to add L2 regularization to the loss

### ISSUE THREAD

**Issue by houxianxu** [pfnet/chainer#214]
How can add L2 regularization and optimize with regularization gradient?

**Comment by beam2d** [comment]
You can use `Optimizer.weight_decay` for the L2 regularization.
http://docs.chainer.org/en/latest/reference/core/optimizer.html#chainer.Optimizer.weight_decay

BTW, would you put a question into the official forum from the next time? Thanks.
https://groups.google.com/forum/?hl=ja#!forum/chainer
