### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PlotReport'

### ISSUE THREAD

**Issue by ch3njust1n** [pfnet/chainer#2152]
I get this error when I install and run the example from the webpage:
```
$ wget https://github.com/pfnet/chainer/archive/v1.20.0.tar.gz
$ tar xzf v1.20.0.tar.gz
$ python chainer-1.20.0/examples/mnist/train_mnist.py
GPU: -1
# unit: 1000
# Minibatch-size: 100
# epoch: 20


Traceback (most recent call last):
  File "chainer-1.20.0/examples/mnist/train_mnist.py", line 115, in <module>
    main()
  File "chainer-1.20.0/examples/mnist/train_mnist.py", line 89, in main
    extensions.PlotReport(['main/loss', 'validation/main/loss'], 'epoch',
AttributeError: 'module' object has no attribute 'PlotReport'
```

**Comment by mitmul** [comment]
@ch3njust1n Did you install Chainer correctly? Just downloading the source doesn't mean installing it. Please check the instruction for how to install Chainer: https://github.com/pfnet/chainer#installation

**Comment by ch3njust1n** [comment]
@mitmul Thanks! For some reason that worked, but `sudo pip install chainer` didn't fully install it. Btw, about what percent of the Volatile GPU should the mnist example be using? I'm running it on a Titan X. I'm curious because `nvidia-smi` is showing only 5-6% util on the DQN-tensorflow code, so I'm not sure if it's because of something I did or if it's because of TensorFlow and Titan X. I Googled my issue and other people also seem to be having issues with TitanX and TF.
