### ISSUE TITLE
Wrong behavior of SerialIterator if dataset is numpy array.

### ISSUE THREAD

**Issue by LukasDrude** [pfnet/chainer#2160]
In `serial_iterator.py` lines [66](https://github.com/pfnet/chainer/blob/master/chainer/iterators/serial_iterator.py#L66) and [68](https://github.com/pfnet/chainer/blob/master/chainer/iterators/serial_iterator.py#L68) contain `+=` to extend lists.

Unfortunately, this does not crash for `numpy` arrays but produces undesired behavior. The dataset itself gets modified (see for `6` in the second example):

```
import numpy as np
from chainer.iterators.serial_iterator import SerialIterator

dataset = [1, 2, 3, 4, 5]
it = SerialIterator(dataset, batch_size=2, shuffle=False)

for _ in range(6):
    example = it.next()
    print(example)
```

```
[1, 2]
[3, 4]
[5, 1]
[2, 3]
[4, 5]
[1, 2]
```

```
dataset = np.asarray([1, 2, 3, 4, 5])
it = SerialIterator(dataset, batch_size=2, shuffle=False)

for _ in range(6):
    example = it.next()
    print(example)
```

```
[1 2]
[3 4]
[6]
[2 3]
[4 6]
[1 2]
```

When the two lines get changed to
```
batch.extend(list(self.dataset[:rest]))
```

and
```
batch.extend([self.dataset[index] for index in self._order[:rest]])
```

a useful error is raised.

**Comment by unnonouno** [comment]
Thank you for reporting problem. I'll make a patch.
BTW, I feel that we need to support numpy array as dataset.
