### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by fonnesbeck** [pfnet/chainer#22]
I attempted to install chainer on Python 3.4, but it failed due to incompatibility with Python 3. The entire Python scientific stack is Python 3 compatible these days, so I'm hoping there are plans to make chainer compatible as well. I'm looking forward to using it.

**Comment by beam2d** [comment]
Thank you for trying Chainer! We are aware that Python 3 has large share and supporting it involves more users. We still do not investigate Python 3 status of dependent packages (PyCUDA and scikits.cuda), but if they already support it, we will fix the code base for Python 3.

**Comment by icoxfog417** [comment]
PyCUDA and scikits.cuda almost supports Python3.

* PyCUDA: [Supports Python3](https://pypi.python.org/pypi/pycuda)
* scikits.cuda: [Some parts of the package may not work with Python3](http://scikit-cuda.readthedocs.org/en/latest/install.html#quick-installation). But in the development version, [all tests pass in Python3.4](https://github.com/lebedov/scikits.cuda/pull/78). And [next version (0.5.0) includes Python 3.4 compatibilities](http://scikit-cuda.readthedocs.org/en/latest/changes.html). 

So I think Chainer is able to support Python3 in the near future. I'm also waiting the time of that.

**Comment by beam2d** [comment]
That's great. Thank you for surveying.

**Comment by unnonouno** [comment]
I made a patch for this issue, but didn't tested it enough yet. Please try it!
