### ISSUE TITLE
Make a rule where to put a docstring for an __init__ method

### ISSUE THREAD

**Issue by muupan** [pfnet/chainer#2240]
Some classes in Chainer put docstrings for `__init__` methods into class docstrings. https://github.com/pfnet/chainer/blob/master/chainer/links/connection/linear.py

Some classes in Chainer put them into `__init__`'s own docstring. https://github.com/pfnet/chainer/blob/master/chainer/computational_graph.py

We should make a clear rule on which to prefer. Sphyinx's google style example says both are ok but should not be mixed. http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by unnonouno** [comment]
I prefer the former one. And we can check if docstrings follow this rule with checking `AClass.__init__.__doc__`.
