### ISSUE TITLE
In the implementation of LSTM, why don't you just use activation function's backward method?

### ISSUE THREAD

**Issue by speedcell4** [pfnet/chainer#2293]
I noticed in the [implementation](https://github.com/pfnet/chainer/blob/master/chainer/functions/activation/lstm.py#L14)  of `LSTM` activation function, ad hoc functions `_sigmoid`, `_grad_sigmoid ` and `_grad_tanh ` are used.

But, why not just use `chainer.functions.Sigmoid().forward()` and `chainer.functions.Sigmoid().backward()` to do this part? Is there any special reason makes you to avoid this?

I wonder this, because I am trying to write a chainer version TreeLSTM.

**Comment by unnonouno** [comment]
It is performance reason. As you say `chainer.functions.Sigmoid` works well. We optimized LSTM by making one large kernel. If performance is enough use `chainer.functions.Sigmoid`. It's easier.

BTW, one of the Tree-LSTM implementation is here.
https://github.com/pfnet/chainer/blob/master/chainer/functions/activation/slstm.py

**Comment by speedcell4** [comment]
Yeah, I know that, but what I am trying to implement is the special kind that you have mentioned in #402. Thank you for your answering.

**Comment by unnonouno** [comment]
Great! I recommend you to implement functions with combination of `chainer.functions` quickly. You need to optimize them only when performance is not enough.
