### ISSUE TITLE
Installing CuPy from source

### ISSUE THREAD

**Issue by alexbw** [pfnet/chainer#2351]
Hello, the docs say that doing `python setup.py install` in the CuPy source directory is sufficient for building CuPy from source. However, there is only the chainer project source, with cupy inside of it. a `python setup.py install` command from within the chainer source only seems to build chainer, as a call to `import cupy` fails after installation. 

How do I build CuPy from source and install it locally?

**Comment by unnonouno** [comment]
Currently CuPy is included in chainer repository. So `setup.py` in chainer installs both Chainer and CuPy. Please write log of setup.py.

**Comment by alexbw** [comment]
I made a mistake, it was installed. Thanks, closing!
