### ISSUE TITLE
when i use gpu train mnist,code runs error

### ISSUE THREAD

**Issue by mjiansun** [pfnet/chainer#2360]
ubuntu 14.04, 
pycharm , 
source code'chainer-master',
cupy 1.0.0a1

i modify parser.add_argument('--gpu', '-g', type=int, default=0,help='GPU ID (negative value indicates CPU)')

**So,the following problem comes up:**
/usr/bin/python2.7 /home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5005)
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20

Traceback (most recent call last):
  File "/home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py", line 125, in <module>
    main()
  File "/home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py", line 64, in main
    chainer.cuda.get_device(args.gpu).use()  # Make a specified GPU current
  File "/home/s/myproject/chainer/chainer-master/chainer/cuda.py", line 179, in get_device
    check_cuda_available()
  File "/home/s/myproject/chainer/chainer-master/chainer/cuda.py", line 84, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

original error: cannot import name core

Process finished with exit code 1

**Comment by unnonouno** [comment]
You failed to build CuPy. Please try to run `pip install chainer --no-cache-dir -vvvv` and paste install log.

**Comment by mjiansun** [comment]
s@s-pc:~$ sudo pip install chainer --no-cache-dir -vvvv
[sudo] password for s: 
Requirement already satisfied: chainer in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: filelock in /usr/local/lib/python2.7/dist-packages (from chainer)
Requirement already satisfied: nose in /usr/local/lib/python2.7/dist-packages (from chainer)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from chainer)
Requirement already satisfied: protobuf in /usr/local/lib/python2.7/dist-packages (from chainer)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from chainer)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf->chainer)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf->chainer)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools->protobuf->chainer)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools->protobuf->chainer)
Cleaning up...

**Then i run mnist...**

/usr/bin/python2.7 /home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5005)
GPU: 0
# unit: 1000
# Minibatch-size: 100
# epoch: 20

Traceback (most recent call last):
  File "/home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py", line 125, in <module>
    main()
  File "/home/s/myproject/chainer/chainer-master/examples/mnist/train_mnist.py", line 64, in main
    chainer.cuda.get_device(args.gpu).use()  # Make a specified GPU current
  File "/home/s/myproject/chainer/chainer-master/chainer/cuda.py", line 179, in get_device
    check_cuda_available()
  File "/home/s/myproject/chainer/chainer-master/chainer/cuda.py", line 84, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.

original error: cannot import name core

Process finished with exit code 1

**Comment by unnonouno** [comment]
Oh sorry. Before installing chainer, please uninstall chainer because pip do nothing if you already have chainer.

```
pip uninstall chainer
```

and then

```
pip install chainer --no-cache-dir -vvvv
```

**Comment by mjiansun** [comment]
**Why i have following problem?**
mw@mw-computer:~/smj/chainer$ python mnist.py 
GPU: -1
# unit: 1000
# Minibatch-size: 100
# epoch: 20

Traceback (most recent call last):
  File "mnist.py", line 123, in <module>
    main()
  File "mnist.py", line 94, in main
    if extensions.PlotReport.available():
AttributeError: type object 'PlotReport' has no attribute 'available'

**Comment by unnonouno** [comment]
> Firstly, i follow your steps, but when i run code in pycharm, problems also happen!

CUDA is a C-library and is not a Python library. So, to use CUDA from Python, Chainer setup script tries to build a C-extension using a C-compiler. It requires a C-compiler such as gcc and CUDA library. Users need to setup these tools and libraries correctly. And when an environment does not satisfy the condition, the setup script fails, and chainer shows this error message.
I think your environment does not satisfy requirements. I want to investigate its reason from the error log of installation. So show me the installation log.

> I run code in shell terminal.Why i have following problem?

Did you use the master branch? The example code in the master branch is newer than Chainer in pypi. The newest example uses latest API. Please use the same version of example:

```
wget https://github.com/pfnet/chainer/archive/v1.21.0.tar.gz
tar xzf v1.21.0.tar.gz
python chainer-1.21.0/examples/mnist/train_mnist.py
```

**Comment by mjiansun** [comment]
`ubuntu14.04     Python 2.7.6     GCC 4.8.4      numpy 1.12.0     six 1.10.0 
filelock 2.0.7     Pillow 4.0.0       h5py 2.6.0      mock 2.0.0          nose 1.3.7
cuda release 7.5, V7.5.17         cudnn-7.5-linux-x64-v5.0           chainer-master`

In my .bashrc ,my cuda path is 
`export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH `

It's my whole environment.What i also need install ?
