### ISSUE TITLE
Error in cupy's advanced indexing when an empty list is given

### ISSUE THREAD

**Issue by muupan** [pfnet/chainer#2366]
When an empty list is given as a selection object to numpy's advanced indexing, no item is selected for that axis.
```
>>> numpy.zeros((4,3,2))[[]]
array([], shape=(0, 3, 2), dtype=float64)
```

However, cupy's advanced indexing raises an error.
```
>>> cupy.zeros((4,3,2))[[]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1142, in cupy.core.core.ndarray.__getitem__ (cupy/core/core.cpp:23915)
    raise IndexError(
IndexError: arrays used as indices must be of integer or boolean type. (actual: <class 'numpy.float64'>)
```

**Comment by yuyu2172** [comment]
Related to this bug, I found more.

+ [[]]  (double nested list)
+ `numpy.array([], dtype=numpy.bool)`   (a boolean array of size 0)

**Comment by yuyu2172** [comment]
#2369 solved this issue, so I think we can close it.

**Comment by niboshi** [comment]
Confirmed that it's fixed now. Thank you for reporting!
