### ISSUE TITLE
Write and run a benchmark

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#24]
Deep learning framework must have enough performance for fast research and development. In order to decide which framework to use, benchmarks are useful to compare different frameworks before solving heavy learning tasks by oneself.

**Comment by adamist521** [comment]
One well known benchmark for convnet.
https://github.com/soumith/convnet-benchmarks

**Comment by beam2d** [comment]
Yeah, that is a great repository. The benchmark should support the same protocol used in this report.
