### ISSUE TITLE
How to build own train&test dataset?

### ISSUE THREAD

**Issue by mjiansun** [pfnet/chainer#2400]
How to build own train&test dataset?
Have help documention?

**Comment by unnonouno** [comment]
Does this document help you? http://docs.chainer.org/en/latest/reference/core/dataset.html
Simply make a list of tuples if you have enough memory. You can use it as a dataset. If you want to other type of storage such as file system and databases, try to make a custom dataset class using `DatasetMixin`.

**Comment by mjiansun** [comment]
Thank you very much
