### ISSUE TITLE
Validation batch size for ptb example

### ISSUE THREAD

**Issue by yobibyte** [pfnet/chainer#2453]
Why is it 1? Is there any specific reason for that? [This is the line](https://github.com/pfnet/chainer/blob/master/examples/ptb/train_ptb.py#L187).

**Comment by jekbradbury** [comment]
If you use a larger batch size for BPTT, the loader divides the data into batch_size independent pieces that the model can’t preserve recurrent state between. In order to get the best perplexity you want to preserve recurrent state over the whole dev/test data.

**Comment by yobibyte** [comment]
I get it. Thank you!
