### ISSUE TITLE
Install from the source code by 'python setup.py install', but cannot use gpu

### ISSUE THREAD

**Issue by jackieyung** [pfnet/chainer#2475]
I have installed the newest version of chainer by 'git clone https://github.com/pfnet/chainer.git' and ran 'python setup.py install'. Then I  ran my model,sadly, it printed out  like this:
![1](https://cloud.githubusercontent.com/assets/13002561/24395105/09e41c00-13d1-11e7-98bd-a959f882a209.png)

My computer have installed CUDA and I have done this:"https://github.com/pfnet/chainer#installation-with-cuda", like the picture:
![2](https://cloud.githubusercontent.com/assets/13002561/24395141/36372248-13d1-11e7-84a9-aecfcb0ddbc1.png)

When I install chainer from the command "pip install chainer",it completly can work.

So,could someone can help me the problem,because I want to use 'resize_images.py' in the source code,which didn't in the command "pip install chainer".

Thanks very much.
@yuyu2172 Thanks your code 'resize_images.py', could you help me solve this problem?

**Comment by bkvogel** [comment]
Hi. Depending on the way you installed CUDA, it is possible that the actual paths might be different. Could you describe which platform you are using? Could you also check that the directories in your picture actually contain CUDA files? For example, on my Ubuntu 16.04 system, some of the CUDA paths are different.

**Comment by jackieyung** [comment]
Thanks for your help.
My platform is Ubuntu 14.04 system. the CUDA path is actually '/usr/local/cuda', and there actually contain CUDA files.

**Comment by unnonouno** [comment]
Hum... Your environment looks like broken. The original error message says "cannot import name fusion". The fusion is the newest feature of chainer and is not available in the stable version in pypi. So, maybe chainer itself is newest but it refers different version of chainer. I'm suspecting you have various versions of chainer in your environment.

Can you uninstall chainer first and reinstall it? Sometimes various versions of chainers are installed. Please run `pip uninstall chainer` till `pip` command says nothing. And after that, please install chainer from the source.

**Comment by jackieyung** [comment]
Thanks a lot.
I have solved the problem just added the installed path before "import chainer",that is

import sys
sys.path.insert(0,'/usr/local/lib/python2.7/dist-packages/chainer-1.22.0-py2.7-linux-x86_64.egg/')

**Comment by bkvogel** [comment]
Good to hear you solved the problem. I'll close the issue.
