### ISSUE TITLE
Limit of number of elements in an array

### ISSUE THREAD

**Issue by kmaehashi** [pfnet/chainer#2531]
It seems that the number of elements in CuPy array is typed as `int`.

https://github.com/pfnet/chainer/blob/v1.23.0/cupy/core/carray.pxi#L10

It would be better if CuPy can handle arrays with more than `2^31` elements.

**Comment by beam2d** [comment]
Thank you for the report. The support of 64bit addressing is on-going at #2263.

**Comment by kmaehashi** [comment]
@beam2d Thanks, I overlooked that.
