### ISSUE TITLE
Shape of output value of `concat` is list in GPU

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#257]
`cuda.empty([1])` makes a `GPUArray` with `list` shape. It causes a type invalid error.

https://github.com/pfnet/chainer/blob/master/chainer/functions/concat.py#L69

**Comment by unnonouno** [comment]
This problem is already fixed in the newest version of pycuda.
https://github.com/inducer/pycuda/commit/53bcda2f825b3fc681907769318c33ed04c3b943#diff-c6f20a28105688a11d8983cd1fce702cL195

**Comment by nushio3** [comment]
Me too...

$ time ./train_zoom_autoencoder.py -g 0
rmsqerr_adj: 897.130696103
Traceback (most recent call last):
  File "./train_zoom_autoencoder.py", line 288, in <module>
    loss.backward()
  File "build/bdist.linux-x86_64/egg/chainer/variable.py", line 197, in backward
  File "build/bdist.linux-x86_64/egg/chainer/variable.py", line 116, in grad
ValueError: Shape of data and grad mismatch: [2, 4, 1024, 1024] != (2, 4, 1024, 1024)
This error is occured in two cases. The first case is when the user manually
sets the Variable.grad incorrectly. The second case is when some Function
implementation has a bug. If you do not manually set the Variable.grad in your
script, please report this error to the issue tracker with the stack trace,
the information of your environment, and your script:
https://github.com/pfnet/chainer/issues/new.


real    0m15.683s
user    0m15.095s
sys     0m5.572s

**Comment by nushio3** [comment]
I was able to fix the above error, by downloading the latest master repository of `pycuda` from
https://github.com/inducer/pycuda
and by manually installing it.

**Comment by unnonouno** [comment]
:+1:
