### ISSUE TITLE
`Function` which get no input cannot select `volatile`

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#259]
In `Function.__call__`, it checks `volatile` of all input variables, and the same value is used. But, `Function` which get not argument such as `Parameter`, always selects `volatile=False`. it may causes conflict of volatility.

https://github.com/pfnet/chainer/blob/master/chainer/function.py#L132
`Parameter` always returns `False` here.

**Comment by beam2d** [comment]
The simplest solution is defining `Parameter.__call__` with an optional argument `volatile`.

**Comment by unnonouno** [comment]
OK, i agree with you.
