### ISSUE TITLE
Cupy fusion bug

### ISSUE THREAD

**Issue by jekbradbury** [pfnet/chainer#2594]
(not sure if this is supposed to go in github.com/cupy/cupy yet or if this is still the right place)

This code works:
```python
@cupy.fuse()
def sigsbwd(gy, y1, y2):
    for y in (y1, y2):
        gy = gy * y * (1.0 - y)
    return gy
sigsbwd(gy, *ys) # ys is a list of 2 ndarrays
```
but this doesn't (the code generator makes two `v1` variables, one of which is a `&float` and the other a `float`, and nvcc throws an error):
```python
@cupy.fuse()
def sigsbwd(gy, *ys):
    for y in ys:
        gy = gy * y * (1.0 - y)
    return gy
sigsbwd(gy, *ys) # ys is a list of 2 ndarrays
```
I thought these were syntactically equivalent at the Python level, but I guess fusion is doing some fairly low-level Python manipulation and is tripped up by the varargs.

**Comment by niboshi** [comment]
Thank you for reporting the issue!
I made a PR for this issue: #2598
