### ISSUE TITLE
Unify coding style

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#26]
PEP8 is one of the most famous coding standard.
https://www.python.org/dev/peps/pep-0008/
And, we can also use style checker.
https://pypi.python.org/pypi/pep8

**Comment by delta2323** [comment]
There seems other alternatives of style checker like flake8, which is a wrapper of several tools including pep8. Some investigation may be needed.

**Comment by unnonouno** [comment]
Hum. Which one do you like? How about Google python style?

https://google-styleguide.googlecode.com/svn/trunk/pyguide.html

**Comment by beam2d** [comment]
FYI, the docstrings currently obey Google style.

**Comment by beam2d** [comment]
Following offline discussions, we will use PEP8 with [OpenStack Style Guidelines](http://docs.openstack.org/developer/hacking/) as our coding style.
