### ISSUE TITLE
Maybe there is a bug in chainer.optimizer.weight_decay(decay).

### ISSUE THREAD

**Issue by houxianxu** [pfnet/chainer#261]
In the [optimizer.py](https://github.com/pfnet/chainer/blob/30807b4f9f40177f592099663b86a6bb3eb1f867/chainer/optimizer.py) file,  `weight_decay` is implemented as following:
``` python
 def weight_decay(self, decay):
     for p, g, _ in self.tuples:
         g -= decay * p
```
However, the gradient is decayed, not the weight. So if we update the weights `param -= lr * grad`, because the grad becomes smaller, the param (weight) becomes larger, which is not we want. 

As far as I know the regularized gradient decent is `p = p * (1-decay) - lr * grad`, so I think the weight should be decayed not the gradient.

**Comment by beam2d** [comment]
Ah, you are right. It is a bug of Optimizer. We should **add** the decayed weights to the gradients instead of subtract them. I cannot believe that everyone except you has not noticed. Thank you for the catch!
