### ISSUE TITLE
download.py isn't found

### ISSUE THREAD

**Issue by massongit** [pfnet/chainer#2636]
Comment in `examples/word2vec/train_word2vec.py` indicates that we must download `ptb.train.txt` using  `examples/ptb/download.py`. But this script isn't found.

**Comment by ysekky** [comment]
(I am not member of authers.)

The function to download ptd data is already built in `chainer.datasets`.

https://github.com/pfnet/chainer/blob/master/chainer/datasets/ptb.py

In `examples/word2vec/train_word2vec.py` , the function is used.

Perhaps this comment is only old, I think you can execute this example.

**Comment by massongit** [comment]
Thank you for providing the information!
