### ISSUE TITLE
F.concate and np.concatenate do not have consistency

### ISSUE THREAD

**Issue by keisuke-umezawa** [pfnet/chainer#2673]
There are two problems:
  1. the names are different
    In numpy,  the array concatenating function is `concatenate`. 
    https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html
    But, in chainer, the name is `concat`.
  2. the default axis values are different
    In numpy, the value is 0. But, in chainer, the value is 1.

https://github.com/pfnet/chainer/blob/master/chainer/functions/array/concat.py

**Comment by jekbradbury** [comment]
These are reasonable differences. Cupy, not Chainer, is intended to be consistent with numpy, and `cupy.concatenate` is consistent with `numpy.concatenate` in all the ways you mention. Chainer is specialized for neural networks, where you typically work with batched data and don't want to concatenate on the batch (zeroth) dimension, so defaulting to axis 1 is reasonable.

**Comment by keisuke-umezawa** [comment]
Thank you for the comments! Now I know the reasons `chainer.functions.arrray` and `numpy` is not consistent. I will close the issue.
