### ISSUE TITLE
FunctionSet.copy_parameters_from()

### ISSUE THREAD

**Issue by rainerkelz** [pfnet/chainer#269]
Hi all!

The code in 'FunctionSet.copy_parameters_from()' does not work, when 'src' and 'dst' are both numpy.ndarrays?

```python
if isinstance(dst, numpy.ndarray):
    if isinstance(src, numpy.ndarray):
        dst.copy(src)  # this gives a ValueError
````
I think this should read
```python
if isinstance(dst, numpy.ndarray):
    if isinstance(src, numpy.ndarray):
        numpy.copyto(dst, src)
````

My numpy.version.full_version is 1.9.2, the 'copyto' method exists since 1.7.0.

Cheers,
-r

**Comment by unnonouno** [comment]
Thank you for reporting a bug. I'll check it and fix it.

**Comment by rainerkelz** [comment]
Thank you guys!

**Comment by unnonouno** [comment]
:+1:
