### ISSUE TITLE
LSTM states are not serialized

### ISSUE THREAD

**Issue by niboshi** [pfnet/chainer#2743]
The states of LSTM are expected to be saved/restored through serialization, but as the code below demostrates, they are not.

Code:
```
import numpy
import chainer
from chainer import links
from chainer import serializers


def run(with_serialization):
    print("=== {} ===".format(with_serialization))
    numpy.random.seed(0)

    x = chainer.Variable(numpy.arange(4, dtype=numpy.float32).reshape((1,4)))

    lstm = links.LSTM(4, 4)
    x = lstm(x)

    if with_serialization:
        serializers.npz.save_npz('a.npz', lstm)
        print("SAVE: {} {}".format(lstm.h, lstm.c))
        lstm = links.LSTM(4, 4)
        serializers.npz.load_npz('a.npz', lstm)
        print("LOAD: {} {}".format(lstm.h, lstm.c))

    x = lstm(x)

    print(x)
    print()


run(False)
run(True)
```

Result:
```
=== False ===
variable([[-0.17516686  0.11355757 -0.28198385  0.4149636 ]])

=== True ===
SAVE: variable([[-0.31524092 -0.00537899 -0.55981427  0.61798769]]) variable([[-0.41024509 -0.20147842 -0.7635532   0.83325958]])
LOAD: None None
variable([[-0.11382607  0.13462627 -0.07217097  0.14202254]])
```

**Comment by beam2d** [comment]
At least I intentionally dropped the state from the serialization, because it is not a part of the model. I think this behavior is consistent with the serialization of other links. How do you think about it?

**Comment by niboshi** [comment]
Ah, I didn't know that. Does this work well with snapshot?

**Comment by beam2d** [comment]
If the loss function does not reuse the state arrays between iterations, it does not matter. Otherwise, just taking a snapshot of the LSTM link does not recover the state arrays, which might be confusing... I guess most people do not want to save the state arrays into the model (it just increases the file size). We might have to distinguish taking snapshot from saving models, but we currently do not have a way to achieve this...

**Comment by niboshi** [comment]
OK, I understood at least this is no an issue of LSTM.

Btw, I encountered this problem in implementing automatic subgraph construction from a link (in the context of visualization).
For that to work, base `Link` class has to have a way to know state variables (like `h` and `c` in LSTM), because they are boundary of a subgraph.
I will raise (maybe a series of) proposals about them as issues.
