### ISSUE TITLE
PyCUDA installation fails when using sudo pip

### ISSUE THREAD

**Issue by hido** [pfnet/chainer#275]
When installing with ``pip``, PyCUDA requires ``/path/to/cuda/bin`` in the PATH, which is typically ``/usr/local/cuda/bin`` or ``/opt/nvidia/cuda/bin`` 

When trying it by  ``sudo pip install chainer-cuda-deps``, however, some Linux environments do not automatically pass nor allow to pass the current PATH to the sudo environment, so that ``setup.py`` of PyCUDA cannot find ``nvcc`` in the PATH. This happened both on Ubuntu 14.04.2 and Amazon Linux.

I think it is better to recommend users to use ``virtualenv`` or ``pyenv`` to avoid installation with ``sudo``. Or, if the users would like, ``sudo env "PATH=$PATH" pip install chainer-cuda-deps`` solves the problem.

We can note this on README and FAQ documents.

**Comment by unnonouno** [comment]
Or use `pip install --user chainer-cuda-deps`
