### ISSUE TITLE
layer freezing/ "trainable" attribute

### ISSUE THREAD

**Issue by undertherain** [pfnet/chainer#2765]
Chainer is currently missing explicit "layer freezing" functionality. I.e. the ability to to exclude given layers from training, i.e. keeping their weights from being updated.   

This is essential feature for, for example, using feature extraction layers from existing models and fine-tuning. 

There's is a discussion in https://groups.google.com/forum/#!msg/chainer/a3ezz_5_KhQ/3dmi6aK7AAAJ with some workarounds proposed, but they are far from being elegant.  Plus the thread have not been active since Feb. 

So I believe this deserves being a proper issue/ feature request on GitHub. 

Something like "trainable" property (as in many other frameworks) would be really convenient.

**Comment by beam2d** [comment]
Thank you for pushing this issue! From Chainer v2 (which is planned to be released next week), we will have a parameter-wise `update_rule` object which is responsible for the updates of the parameter. This object has `enabled` flag with which you can control whether or not the parameter will be updated. That is, a parameter with `enabled=False` is frozen. I hope this feature will help you.

**Comment by undertherain** [comment]
Thank you for quick reply! 
I've also noticed that there are enable_update() and disable_update() methods in links - sounds like something supposed to freeze layers... but not working currently - is it something we might see in the future? Would be even more convenient than resetting update_rule for all weights and biases individually. 

As for update_rule - should it be working in 2.0.0.b (current dev) version? I’m trying to make a short example:
     
```python
class CNN(chainer.Chain):
    def __init__(self, train=True):
        super(CNN, self).__init__(
            conv1=L.Convolution2D(1, 1, 1, initialW=np.array([[[[1]]]])) ,
            l1=L.Linear(None, 1, initialW=np.array([[1,1,1,1]]))  
        )
        self.train=train
        net.conv1.W.update_rule=chainer.optimizer.UpdateRule()
        net.conv1.W.update_rule.enabled=False
        net.conv1.b.update_rule=chainer.optimizer.UpdateRule()
        net.conv1.W.update_rule.enabled=False

    def __call__(self, x):
        h = F.relu(self.conv1(x))
        h = F.sigmoid(self.l1(h))
        return h


net = CNN()
net.cleargrads()
optimizer = chainer.optimizers.SGD()
optimizer.setup(net)
result = net(np.random.random((1,1,2,2)).astype(np.float32))
print("conv1 weights:",net.conv1.W.data)
print("l1 weigths:",net.l1.W.data)
loss = F.mean_absolute_error(result,np.array([[0.1]],dtype=np.float32))
loss.backward()
optimizer.update()
print("after update...")
#print("conv1 grad",net.conv1.W.grad)
print("conv1 weights:",net.conv1.W.data)
print("l1 weights:",net.l1.W.data)
```

producing 

> conv1 weights: [[[[ 1.]]]]
l1 weigths: [[ 1.  1.  1.  1.]]
after update...
conv1 weights: [[[[ 0.99887413]]]]
l1 weights: [[ 0.99972546  0.99977684  0.99968797  0.99968386]]

...apparently conv1 is still changing. Am I doing it correctly and should I just wait for the final release?  Can't wait for the 2.0 :)

**Comment by beam2d** [comment]
Maybe the documentation is bad, but you have to edit `update_rule.enabled` after calling `optimizer.setup`. The `optimizer.setup` sets up an implementation of `UpdateRule` (in this case `SGDRule`) to each parameter in the target link, so any changes made before this point are invalidated. You can edit the `enabled` flag of these update rule objects after calling `setup`. Could you try it?

**Comment by undertherain** [comment]
Just tried - working like a charm!
```python
optimizer.setup(net)
net.conv1.W.update_rule.enabled=False
net.conv1.W.update_rule.enabled=False
```
allows to individually freeze weights and biases

and actually 
```python
net.conv1.disable_update() 
```
is working too for the whole link

Thanks again! let's close this
