### ISSUE TITLE
cupy doesn't really support cudnn v6

### ISSUE THREAD

**Issue by Paosder** [pfnet/chainer#2777]
When I try to install with pip, it seems no problem, but the problem occurs when I use chainer v2.
So I checked every dependencies, and finally I found that cupy isn't installed successfully.

Here's my error code.

`cupy/cuda/cudnn.cpp:4035:20: error: use of undeclared identifier 'cudnnSetFilter4dDescriptor_v3'; did you mean 'cudnnGetFilterNdDescriptor'?
      __pyx_v_status = cudnnSetFilter4dDescriptor_v3(((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((cudnnDataType_t)__pyx_v_dataType), __pyx_v_k, __pyx_v_c, __pyx_v_h, __pyx_v_w);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnGetFilterNdDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:484:27: note: 'cudnnGetFilterNdDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnGetFilterNdDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:4035:134: error: cannot initialize a parameter of type 'cudnnDataType_t *' with an lvalue of type 'int'
      __pyx_v_status = cudnnSetFilter4dDescriptor_v3(((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((cudnnDataType_t)__pyx_v_dataType), __pyx_v_k, __pyx_v_c, __pyx_v_h, __pyx_v_w);
                                                                                                                                         ^~~~~~~~~
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:487:69: note: passing argument to parameter 'dataType' here
                                    cudnnDataType_t                    *dataType, // image data type
                                                                        ^
    cupy/cuda/cudnn.cpp:4209:20: error: use of undeclared identifier 'cudnnSetFilterNdDescriptor_v3'
      __pyx_v_status = cudnnSetFilterNdDescriptor_v3(((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((cudnnDataType_t)__pyx_v_dataType), __pyx_v_nbDims, ((int *)__pyx_v_filterDimA));
                       ^
    cupy/cuda/cudnn.cpp:4365:20: error: use of undeclared identifier 'cudnnSetFilter4dDescriptor_v4'; did you mean 'cudnnSetFilter4dDescriptor'?
      __pyx_v_status = cudnnSetFilter4dDescriptor_v4(((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((cudnnDataType_t)__pyx_v_dataType), ((cudnnTensorFormat_t)__pyx_v_format), __pyx_v_k, __pyx_v_c, __pyx_v_h, __pyx_v_w);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnSetFilter4dDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:457:27: note: 'cudnnSetFilter4dDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnSetFilter4dDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:4548:20: error: use of undeclared identifier 'cudnnSetFilterNdDescriptor_v4'; did you mean 'cudnnSetFilterNdDescriptor'?
      __pyx_v_status = cudnnSetFilterNdDescriptor_v4(((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((cudnnDataType_t)__pyx_v_dataType), ((cudnnTensorFormat_t)__pyx_v_format), __pyx_v_nbDims, ((int *)__pyx_v_filterDimA));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnSetFilterNdDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:477:27: note: 'cudnnSetFilterNdDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnSetFilterNdDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:4735:20: error: use of undeclared identifier 'cudnnGetFilterNdDescriptor_v4'; did you mean 'cudnnGetFilterNdDescriptor'?
      __pyx_v_status = cudnnGetFilterNdDescriptor_v4(((cudnnFilterDescriptor_t)__pyx_v_wDesc), __pyx_v_nbDimsRequested, (&__pyx_v_dataType), (&__pyx_v_format), (&__pyx_v_nbDims), (&(__pyx_v_filterDimA[0])));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnGetFilterNdDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:484:27: note: 'cudnnGetFilterNdDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnGetFilterNdDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:5118:20: error: no matching function for call to 'cudnnSetConvolution2dDescriptor'
      __pyx_v_status = cudnnSetConvolution2dDescriptor_v4(((cudnnConvolutionDescriptor_t)__pyx_v_convDesc), __pyx_v_pad_h, __pyx_v_pad_w, __pyx_v_u, __pyx_v_v, __pyx_v_upscalex, __pyx_v_upscaley, ((cudnnConvolutionMode_t)__pyx_v_mode));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cupy/cuda/cupy_cudnn.h:172:44: note: expanded from macro 'cudnnSetConvolution2dDescriptor_v4'
    #define cudnnSetConvolution2dDescriptor_v4 cudnnSetConvolution2dDescriptor
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:500:27: note: candidate function not viable: requires 9 arguments, but 8 were provided
    cudnnStatus_t CUDNNWINAPI cudnnSetConvolution2dDescriptor( cudnnConvolutionDescriptor_t convDesc,
                              ^
    cupy/cuda/cudnn.cpp:10232:20: error: use of undeclared identifier 'cudnnSetPooling2dDescriptor_v3'; did you mean 'cudnnGetPoolingNdDescriptor'?
      __pyx_v_status = cudnnSetPooling2dDescriptor_v3(((cudnnPoolingDescriptor_t)__pyx_v_poolingDesc), ((cudnnPoolingMode_t)__pyx_v_mode), __pyx_v_windowHeight, __pyx_v_windowWidth, __pyx_v_verticalPadding, __pyx_v_horizontalPadding, __pyx_v_verticalStride, __pyx_v_horizontalStride);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnGetPoolingNdDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:983:27: note: 'cudnnGetPoolingNdDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnGetPoolingNdDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:10232:136: error: cannot initialize a parameter of type 'cudnnPoolingMode_t *' with an lvalue of type 'int'
      __pyx_v_status = cudnnSetPooling2dDescriptor_v3(((cudnnPoolingDescriptor_t)__pyx_v_poolingDesc), ((cudnnPoolingMode_t)__pyx_v_mode), __pyx_v_windowHeight, __pyx_v_windowWidth, __pyx_v_verticalPadding, __pyx_v_horizontalPadding, __pyx_v_verticalStride, __pyx_v_horizontalStride);
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:986:69: note: passing argument to parameter 'mode' here
                                    cudnnPoolingMode_t                 *mode,
                                                                        ^
    cupy/cuda/cudnn.cpp:10424:20: error: use of undeclared identifier 'cudnnSetPooling2dDescriptor_v4'; did you mean 'cudnnSetPooling2dDescriptor'?
      __pyx_v_status = cudnnSetPooling2dDescriptor_v4(((cudnnPoolingDescriptor_t)__pyx_v_poolingDesc), ((cudnnPoolingMode_t)__pyx_v_mode), ((cudnnNanPropagation_t)__pyx_v_maxpoolingNanOpt), __pyx_v_windowHeight, __pyx_v_windowWidth, __pyx_v_verticalPadding, __pyx_v_horizontalPadding, __pyx_v_verticalStride, __pyx_v_horizontalStride);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnSetPooling2dDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:952:27: note: 'cudnnSetPooling2dDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnSetPooling2dDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:10625:20: error: use of undeclared identifier 'cudnnSetPoolingNdDescriptor_v3'
      __pyx_v_status = cudnnSetPoolingNdDescriptor_v3(((cudnnPoolingDescriptor_t)__pyx_v_poolingDesc), ((cudnnPoolingMode_t)__pyx_v_mode), __pyx_v_nbDims, ((int *)__pyx_v_windowDimA), ((int *)__pyx_v_paddingA), ((int *)__pyx_v_strideA));
                       ^
    cupy/cuda/cudnn.cpp:10799:20: error: use of undeclared identifier 'cudnnSetPoolingNdDescriptor_v4'; did you mean 'cudnnSetPoolingNdDescriptor'?
      __pyx_v_status = cudnnSetPoolingNdDescriptor_v4(((cudnnPoolingDescriptor_t)__pyx_v_poolingDesc), ((cudnnPoolingMode_t)__pyx_v_mode), ((cudnnNanPropagation_t)__pyx_v_maxpoolingNanOpt), __pyx_v_nbDims, ((int *)__pyx_v_windowDimA), ((int *)__pyx_v_paddingA), ((int *)__pyx_v_strideA));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                       cudnnSetPoolingNdDescriptor
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:974:27: note: 'cudnnSetPoolingNdDescriptor' declared here
    cudnnStatus_t CUDNNWINAPI cudnnSetPoolingNdDescriptor(
                              ^
    cupy/cuda/cudnn.cpp:13489:26: error: use of undeclared identifier 'cudnnActivationForward_v3'; did you mean 'cudnnActivationForward'?
            __pyx_v_status = cudnnActivationForward_v3(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationMode_t)__pyx_v_mode), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_dstDesc), ((void *)__pyx_v_dstData));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~
                             cudnnActivationForward
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1072:27: note: 'cudnnActivationForward' declared here
    cudnnStatus_t CUDNNWINAPI cudnnActivationForward(
                              ^
    cupy/cuda/cudnn.cpp:13489:85: error: cannot initialize a parameter of type 'cudnnActivationDescriptor_t' (aka 'cudnnActivationStruct *') with an rvalue of type 'cudnnActivationMode_t'
            __pyx_v_status = cudnnActivationForward_v3(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationMode_t)__pyx_v_mode), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_dstDesc), ((void *)__pyx_v_dstData));
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1074:69: note: passing argument to parameter 'activationDesc' here
                                    cudnnActivationDescriptor_t         activationDesc,
                                                                        ^
    cupy/cuda/cudnn.cpp:13714:26: error: use of undeclared identifier 'cudnnActivationForward_v4'; did you mean 'cudnnActivationForward'?
            __pyx_v_status = cudnnActivationForward_v4(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationDescriptor_t)__pyx_v_activationDesc), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_dstDesc), ((void *)__pyx_v_dstData));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~
                             cudnnActivationForward
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1072:27: note: 'cudnnActivationForward' declared here
    cudnnStatus_t CUDNNWINAPI cudnnActivationForward(
                              ^
    cupy/cuda/cudnn.cpp:13939:26: error: use of undeclared identifier 'cudnnActivationBackward_v3'; did you mean 'cudnnActivationBackward'?
            __pyx_v_status = cudnnActivationBackward_v3(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationMode_t)__pyx_v_mode), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((cudnnTensorDescriptor_t)__pyx_v_srcDiffDesc), ((void *)__pyx_v_srcDiffData), ((cudnnTensorDescriptor_t)__pyx_v_destDesc), ((void *)__pyx_v_destData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_destDiffDesc), ((void *)__pyx_v_destDiffData));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             cudnnActivationBackward
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1083:27: note: 'cudnnActivationBackward' declared here
    cudnnStatus_t CUDNNWINAPI cudnnActivationBackward(
                              ^
    cupy/cuda/cudnn.cpp:13939:86: error: cannot initialize a parameter of type 'cudnnActivationDescriptor_t' (aka 'cudnnActivationStruct *') with an rvalue of type 'cudnnActivationMode_t'
            __pyx_v_status = cudnnActivationBackward_v3(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationMode_t)__pyx_v_mode), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((cudnnTensorDescriptor_t)__pyx_v_srcDiffDesc), ((void *)__pyx_v_srcDiffData), ((cudnnTensorDescriptor_t)__pyx_v_destDesc), ((void *)__pyx_v_destData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_destDiffDesc), ((void *)__pyx_v_destDiffData));
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1085:69: note: passing argument to parameter 'activationDesc' here
                                    cudnnActivationDescriptor_t         activationDesc,
                                                                        ^
    cupy/cuda/cudnn.cpp:14200:26: error: use of undeclared identifier 'cudnnActivationBackward_v4'; did you mean 'cudnnActivationBackward'?
            __pyx_v_status = cudnnActivationBackward_v4(((cudnnHandle_t)__pyx_v_handle), ((cudnnActivationDescriptor_t)__pyx_v_activationDesc), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((cudnnTensorDescriptor_t)__pyx_v_srcDiffDesc), ((void *)__pyx_v_srcDiffData), ((cudnnTensorDescriptor_t)__pyx_v_destDesc), ((void *)__pyx_v_destData), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_destDiffDesc), ((void *)__pyx_v_destDiffData));
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             cudnnActivationBackward
    /Developer/NVIDIA/CUDA-8.0/include/cudnn.h:1083:27: note: 'cudnnActivationBackward' declared here
    cudnnStatus_t CUDNNWINAPI cudnnActivationBackward(
                              ^
    18 errors generated.
    error: command 'clang' failed with exit status 1
error
Cleaning up...`

As you can easily see that some functions doesn't exist in cudnn.h.
So I checked, and found that there's no function like `cudnnGetFilter4dDescriptor_v4` in cudnn.h v6021.
That function only exists in cudnn 5.1 or lower version, and newest cudnn doesn't have that named function. 
And I tried to install cupy(1.0.0b1) with cudnn 5.1, then it installed gracefully. MNIST tutorial for chainer (2.0.0b1) also works fine.

I tried this in MacOS 10.12,
GTX 1070
cuda 8.0.61.

+chainer v1.24 works fine without any error with chainer.cupy but I think there should be an error with cudnn because the installer automatically pass that conditions.

**Comment by unnonouno** [comment]
Yes, cupy 1.0.0b1 is based on chainer v1.22.0 and does not support cudnn v6. And the current master branch which merged v1.23.0 and v1.24.0 supports v6. Please install cupy from the source code on the master branch, or use cudnn v5.1.

**Comment by Paosder** [comment]
I thought newest version of cupy was 1.0.0b1.  :)
I'll try it. Thanks!
