### ISSUE TITLE
cannot import name 'cublas'

### ISSUE THREAD

**Issue by undertherain** [pfnet/chainer#2785]
I'm using chainer '2.0.0b1' (chainer 1.24 was working fine)
on CentOS Linux release 7.3.1611 (Core)
with CUDA release 8.0, V8.0.61
using gcc version 5.4.0 (GCC) and Python 3.6.1
chainer installed with pip3 install chainer --pre

I'm getting the following error message when calling `hainer.cuda.check_cuda_available()
`

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-14ec8f3756fb> in <module>()
----> 1 chainer.cuda.check_cuda_available()

/work/alex/opt/lib/python3.6/site-packages/chainer/cuda.py in check_cuda_available()
     73                '(see https://github.com/pfnet/chainer#installation).')
     74         msg += str(_resolution_error)
---> 75         raise RuntimeError(msg)
     76     if (not cudnn_enabled and
     77             not _cudnn_disabled_by_user and

RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).cannot import name 'cublas'
```
I see several similar issues being posted, but a bit different, for example people are experiencing exceptions on importing libcuda, not libcublas. 

On my CentOS libcublas.so is in 
`/usr/local/cuda-8.0/targets/x86_64-linux/lib`, symlinked to `/usr/local/cuda-8.0/lib64`, included in  my $LD_LIBRARY_PATH and  $LIBRARY_PATH variables.

**Comment by undertherain** [comment]
hm... I've tried adding `/usr/local/cuda-8.0/lib64/stubs/` to LD_LIBRARY_PATH, now I'm getting 

```You are running using the stub version of libcublas```

**Comment by unnonouno** [comment]
Did you install `cupy`? Maybe this is new problem because chainer 2.0.0 itself is not depend on CUDA. It just uses `cupy`, that is NumPy compatible matrix library using CUDA. So, i think it is cupy's problem.
Chainer 2.0.0 does not automatically install CuPy. So, you need to install cupy manually.

```
$ pip install cupy --pre
```

**Comment by undertherain** [comment]
forcing cupy uninstall/ installing new one solved the issue. 
thanks so much!
p.s.
BTW, installed (with --pre) version is cupy-1.0.0b1, not sure if it was supposed to be 2.x judging by your last comment
