### ISSUE TITLE
/usr/bin/ld: cannot find -lcuda

### ISSUE THREAD

**Issue by hoavt-54** [pfnet/chainer#2797]
Hi all, 

I don't know if it is the issue but I don't have root access so I install CUDA in my home directory. Then I added those paths to **PATH** and **LD_LIBRARY_PATH**:

```
export PATH="/my_local_path/cuda/bin:$PATH"
export LD_LIBRARY_PATH="/my_local_path/cuda/lib64:/my_local_path/cuda/lib:$LD_LIBRARY_PATH"
export CFLAGS=-I/my_local_path/cudnn/include
export LDFLAGS=-L/my_local_path/cudnn/lib64
```

I tried to install chainer from source and by `pip install chainer --no-cache-dir -vvvv` but they all failed to build with cuda:

Bellow are logs when I built chainer from source. Pip install outputs similar logs.

```
Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': False}
Include directories: ['/users/ud2017/hoavt/cuda/include']
Library directories: ['/users/ud2017/hoavt/cuda/lib64', '/users/ud2017/hoavt/cuda/lib']
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
Cannot build a stub file.
Original error: command 'c++' failed with exit status 1
**************************************************
*** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'nvToolsExt']
*** WARNING: Skip installing cuda support
*** WARNING: Check your LDFLAGS environment variable
**************************************************
Include directories: ['/users/ud2017/hoavt/cuda/include']
Library directories: ['/users/ud2017/hoavt/cuda/lib64', '/users/ud2017/hoavt/cuda/lib']
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/tmp/tmpHcwk2p/a.cpp:1:19: fatal error: cudnn.h: No such file or directory
 #include <cudnn.h>
                   ^
compilation terminated.
command 'x86_64-linux-gnu-gcc' failed with exit status 1
**************************************************
*** WARNING: Include files not found: ['cudnn.h']
*** WARNING: Skip installing cudnn support
*** WARNING: Check your CFLAGS environment variable
**************************************************
Include directories: ['/users/ud2017/hoavt/cuda/include']
Library directories: ['/users/ud2017/hoavt/cuda/lib64', '/users/ud2017/hoavt/cuda/lib']
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/tmp/tmpAvadWz/a.cpp:1:18: fatal error: nccl.h: No such file or directory
 #include <nccl.h>
                  ^
compilation terminated.
command 'x86_64-linux-gnu-gcc' failed with exit status 1
**************************************************
*** WARNING: Include files not found: ['nccl.h']
*** WARNING: Skip installing nccl support
*** WARNING: Check your CFLAGS environment variable
**************************************************
Include directories: ['/users/ud2017/hoavt/cuda/include']
Library directories: ['/users/ud2017/hoavt/cuda/lib64', '/users/ud2017/hoavt/cuda/lib']
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
running instal
```

It took me two days to fix this issue without any success. I would really appreciate any suggestion. 
I want to use chainer for my project but without cuda support, it is quite slow.  

OS: Ubuntu 14.04 
gcc 4.8.4
python 2.7.6
Cuda compilation tools, release 7.0, V7.0.27
cudnn:

> define CUDNN_MAJOR      4
> define CUDNN_MINOR      0
> define CUDNN_PATCHLEVEL 7
> --
> define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**Comment by Paosder** [comment]
Did you set FLAGS environment variables?
See : https://github.com/pfnet/chainer#installation-with-cuda

+ You can ignore `nccl.h not found` error if you're going to use only one gpu.

**Comment by hoavt-54** [comment]
Thank you @Paosder yes I did. I updated my first comment.

**Comment by hoavt-54** [comment]
I also tried Cuda compilation tools, release 7.0, V7.0.27 and it output the same errors.

**Comment by Paosder** [comment]
@hoavt-54, did you put -I or -L characters in front of your environment variables?
(LD_LIBRARY_PATH, CFLAGS...)

i.g. 
```
export CFLAGS=-I/Developer/NVIDIA/CUDA-8.0/include
export LDFLAGS=-L/Developer/NVIDIA/CUDA-8.0/lib
```

And you should also check that your cudnn path has -L characters(for lib directory).
`LD_LIBRARY_PATH=-L/Developer/NVIDIA/CUDA-8.0/lib:$LD_LIBRARY_PATH`

In my case, in MacOS, I put these characters so that I could fixed these link errors.

**Comment by hoavt-54** [comment]
Hi @Paosder Thank you. I did put those characters in the flags, also tried to put in the `LD_LIBRARY_PATH` but it doesn't work. 
The thing is that the installer already see my cuda( as you can see from the logs):
```
Include directories: ['/opt/cuda/include']
Library directories: ['/opt/cuda/lib64', '/opt/cuda/lib']
```
I really don't know why it doesn't work.

**Comment by Paosder** [comment]
@hoavt-54 , could you show your environment variables?
And did you checked your CUDA installed successfully?
(use nvcc --version to check your cuda)

**Comment by unnonouno** [comment]
Most important error message is this:
```
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
Cannot build a stub file.
```

It suggests that C compiler (`ld` command) cannot find `libcuda.so`. This is critical problem. `libcuda.so` is part of nvidia driver and is usually located at `/usr/lib/x86_64-linux-gnu`. For example in my ubuntu14.04 it is here:

```
% ls -la /usr/lib/x86_64-linux-gnu/libcuda.so
lrwxrwxrwx 1 root root 12  5月  9 21:08 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
```

How did you install NVIDIA driver and CUDA toolkit? I highly recommend to use `deb` package which you can download NVIDIA's site, and do not use `.run` file.

**Comment by hoavt-54** [comment]
@Paosder Thank you so much. Here is my environment variable 
```
$ echo $LD_LIBRARY_PATH
/users/ud2017/hoa/cudnn/lib64:/users/ud2017/hoa/cudnn:/opt/cuda/lib64:/opt/cuda/lib
```
It will be the same whether I put `-L` at the beginning or not

@unnonouno You're right but I thought putting instalation path to `$LD_LIBRARY_PATH` would help `ld`?
I ran `ld -lcuda --verbose` and `ld` said he couldn't find `cuda` in usual places, but he did not look into the places in `$LD_LIBRARY_PATH` :(
```
attempt to open /usr/x86_64-linux-gnu/lib64/libcuda.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libcuda.a failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libcuda.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libcuda.a failed
attempt to open //usr/local/lib64/libcuda.so failed
attempt to open //usr/local/lib64/libcuda.a failed
attempt to open //lib/x86_64-linux-gnu/libcuda.so failed
attempt to open //lib/x86_64-linux-gnu/libcuda.a failed
attempt to open //lib64/libcuda.so failed
attempt to open //lib64/libcuda.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libcuda.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libcuda.a failed
attempt to open //usr/lib64/libcuda.so failed
attempt to open //usr/lib64/libcuda.a failed
attempt to open //usr/local/lib/libcuda.so failed
attempt to open //usr/local/lib/libcuda.a failed
attempt to open //lib/libcuda.so failed
attempt to open //lib/libcuda.a failed
attempt to open //usr/lib/libcuda.so failed
attempt to open //usr/lib/libcuda.a failed
ld: cannot find -lcuda
```

**Comment by hoavt-54** [comment]
Anyway, the problem is I don't have root privileges and cannot link the lib to those usual places. 
I'm gonna close this. Thank you guys so much for your support.

**Comment by unnonouno** [comment]
No, usually a liker command uses `$LIBRARY_PATH`. `$LD_LIBRARY_PATH` is used only on runtime by `dlopen` system call. See http://man7.org/linux/man-pages/man3/dlopen.3.html
