### ISSUE TITLE
CaffeFunction cannot be pickled

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#297]
Some attributes (`forwards`, `layers` and `variables`) of CaffeFunction cannot be pickled directly. We have to provide a customized pickling methods (e.g. `__getstate__` and `__setstate__`).

(This bug is reported by [jellied_unagi](https://twitter.com/jellied_unagi) on Twitter. Thank you!)

**Comment by xternalz** [comment]
Do you mind showing any example of this? I am getting this error message, "ReferenceError: weakly-referenced object no longer exists".
