### ISSUE TITLE
LSTM: Multiply by 4 is counter-intuitive

### ISSUE THREAD

**Issue by jramapuram** [pfnet/chainer#306]
I understand you have 4 gates, but that logic should be within the implementation of the LSTM class.
All I want to do is have an LSTM that does 1->128->64->128->1 and it's pretty un-intuitive to do this.

Thoughts are:
  - implement Recurrent (where you have linear)
  - add logic to LSTM class to split internally
  - implement Split() or something similar that does this operation

Debugging these nets is even worse because you have to have this factor of 4 everywhere.

**Comment by beam2d** [comment]
Thank you for suggesting the improvement on LSTM interface. I agree that the current interface is unintuitive to write a simple stacked LSTM recurrent net. The current interface is designed for flexibility, though. It assumes nothing on the structure of connectivities (e.g. we can write LSTM RNN with convolutional connections).

Adding a wrapper for the current LSTM that includes the Linear functions is a possible solution. It should hide the factor of 4.

**Comment by jramapuram** [comment]
You are right though in that it is more general. Just wanted to point this out for people jumping into your library! Great work otherwise!

**Comment by unnonouno** [comment]
We implemented `chainer.links.LSTM` in #573, that helps you. Please check the new ptb example.
