### ISSUE TITLE
Deconvolution function

### ISSUE THREAD

**Issue by tnarihi** [pfnet/chainer#315]
Deconvolution function is missing in Chainer, which is used in [FCNs](http://arxiv.org/abs/1411.4038) etc.. I just implemented it into [my repo](https://github.com/tnarihi/tnarihi-chainer-ext/blob/master/tnarihi_chainer_ext/functions/deconvolution_2d.py) (not clean code). I didn't do any abstraction like the [implementation in Caffe](http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1DeconvolutionLayer.html) (BaseConvolutionLayer), this might makes codes hard to be read.

I could make a PR for this, but it is also welcome someone else takes my code, clean it and PR it.

JFYI: Another way of implementing a Deconv-like function is unpooling+convolution found in [this paper](http://arxiv.org/abs/1506.02753). Still we need to implement an unpooling (just upsampling) function, but much easier to implement than deconv.

**Comment by unnonouno** [comment]
Thank you for suggestion. I also think a deconvolution function is required. I'll check you branch.

**Comment by t-abe** [comment]
@tnarihi 
I updated your deconvolution implementation to make it working on current chainer, and added tests.
Can I send a PR although most of the lines are written by you.

**Comment by tnarihi** [comment]
Sorry that I missed this. No problem at all. Thanks!

**Comment by cemoody** [comment]
+1! Really excited about having a deconvolution function :)

**Comment by okuta** [comment]
The deconvolution function was implemented in v1.5.0 .
