### ISSUE TITLE
non-contiguous gpuarray issues

### ISSUE THREAD

**Issue by lukemetz** [pfnet/chainer#318]
Hello all, odd issue here.

When running the imagenet examples with a gpu i am getting errors all over the place of the form:
```
RuntimeError: elementwise kernel cannot deal with non-contiguous arrays
```

This is odd as chainer explicitly enforces variables to be contiguous. After tracking it down I found the source which is `gpuarray.to_gpu` function inside cuda.py `to_gpu`. The variables I am feeding into this are contiguous, (the forc flag is true), and some of the values I am getting out are not causing this crash whenever an element wise kernel is called.

I can't seem to find anything describing this behaviour on pycuda's documentation. It only appears to happen on arrays of interesting shapes, such as (1, 256, 1). As nobody else has reported this I would bet its environment specific. I have a custom compiled numpy using just openblas, and have tried both master pycuda and pip pycuda. Ubuntu 15.04 with cuda 7.0. 

Raving the array, allocating, and reshaping it seems to fix this issue for me. Code for my new function:

```python
def to_gpu(array, device=None):
    _check_cuda_available()
    if isinstance(array, GPUArray):
        return array
    with using_device(device):
        return gpuarray.to_gpu(array.ravel(), allocator=mem_alloc).reshape(array.shape)
```

Any ideas what is going on here? Is this a pycuda bug? I don't think my fix introduces any significant overhead but it feels like a hack...

Thanks!

**Comment by delta2323** [comment]
Thank you for your reporting! Now we had replaced PyCUDA with CuPy, or a new GPU array backend. Is the problem still remain unsolved?
