### ISSUE TITLE
Add tips on saving GPU-trained model for CPU-only environment

### ISSUE THREAD

**Issue by hido** [pfnet/chainer#325]
Some users failed on loading GPU-trained models on non-GPU environment, because the model contains GPUArray and pickling it means directly load the object back to GPU, which does not work on other environment.
However, `model.to_cpu()` before saving can solve the problem. This should be a kind of tips.

**Comment by unnonouno** [comment]
I will support official save/load method in the next release (see #363).

**Comment by unnonouno** [comment]
Serialization is supported now in #573. We don't need this tips.
