### ISSUE TITLE
Make Python code of CuPy faster

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#333]
While CuPy enables us to great flexibility and usability of using CUDA, it also adds great overheads due to the slow index manipulations and code generations written in pure Python. We must make it faster to improve the try-and-error cycle on small-scale networks.

There might be three options:

1. Make the pure Python code faster by finding bottlenecks and improve them.
2. Port some critical codes to Cython.
3. Reimplement the ndarray by C and add a Python C extension for it.

I have already tried the approach 1 a bit, and realized it is very hard and seems to be hopeless. Approach 3 is maybe ideal, since the resulting array implementation might be used by other languages as well, though this task is too heavy to complete shortly. Approach 2 is an intermediate solution and seems to be better as the first step of improving CuPy performance.

If we take the approach 2, we have to think about the installation process. Using Cython means we introduce C extensions for the CUDA-related code, which cannot be compiled (linked) in environments without CUDA. In order to support such environments, we have to do either of the following two:

A. Detect whether the CUDA is installed or not in setup.py, and if not, avoid the installation of CuPy.
B. Make CuPy an isolated package (like PyCUDA), and let users decide whether to install CuPy or not.

I recommend to choose the approach B, since it makes it clear which modules are installed from what the user did.

**Comment by bordingj** [comment]
maybe take a look at https://github.com/andersbll/cudarray ?

**Comment by beam2d** [comment]
CUDArray seems to be a fine example of Cython for CUDA array implementation. Thank you! (It cannot be directly used for our purpose, though, since it does not seem to support arbitrary striding yet.)

**Comment by bordingj** [comment]
The type-checking in chainer also creates a big overhead...

**Comment by beam2d** [comment]
@bordingj Yes, I noticed that when I took profiles to tune the CuPy. It seems about 7.35% of running time is consumed by type checking in MNIST example on my environment. We might have to provide "non-debugging mode" to skip such safety codes.

**Comment by tscohen** [comment]
"B. Make CuPy an isolated package (like PyCUDA), and let users decide whether to install CuPy or not."
Is this still planned for the upcoming Cythonization (#499)?

It seems like the right thing to do; CuPy could benefit many scientific computing projects, even those that have nothing to do with machine learning. Conversely, CuPy would benefit from a potentially greatly increased userbase, since users can submit bug reports, bug fixes, speed ups, further numpy compatibility improvements, etc.
