### ISSUE TITLE
Fill the initial gradients by NaN

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#335]
The gradient arrays are not initialized by each Function. User may forget to initialize the gradient before backprop, so it is desirable to notify the user that the gradients are not initialized. The simplest solution is initializing the gradients by NaN at the construction of parameterized functions.

**Comment by beam2d** [comment]
Or we might have to initialize the gradients by None and automatically allocate them at the zeroing. In this case, we might have to think the design.

**Comment by unnonouno** [comment]
How about using `zeros_like` instead of `empty_like`?

**Comment by beam2d** [comment]
I think filling by zero at construction might not help to find that they forgot to initialize the grads in the learning loop.

**Comment by entron** [comment]
Could someone explain why user has to set this boilerplate initial gradient? [autograd](https://github.com/HIPS/autograd)  seems to work without the need to set the initial gradient.
