### ISSUE TITLE
Disconnecting between Function and Optimizer when switching CPU/GPU

### ISSUE THREAD

**Issue by odashi** [pfnet/chainer#345]
Currently, each Function has only either CPU or GPU vectors, and switch them by calling to_cpu() or to_gpu().
On the other hand, Optimizers store references to those vectors at the time we call setup().
The problem is that if we switch the type of vectors after calling setup() for some reasons, the association between functions and the optimizer will be lost, and we cannot continue training using accumulated parameters (e.g. AdaGrad).

I think there are some options to avoid this:
* Add a method to repair association between Function(Set) and Optimizer.
* Function(Set) provide a method to make a copy of their own parameters

**Comment by beam2d** [comment]
Thank you for the suggestion. I agree that it is a large requirement to extract model structure with parameters without affecting the learning loop. FunctionSet.parameters could be used to just extract a sequence of parameters, though it does not preserve the model structure.

If your CPU/GPU have enough space, you can use `copy.deepcopy` to deeply copy the Function(Set). This option does not work if the model is on GPU and its copy cannot be stored simultaneously on the GPU memory. I want to add options to yours:
- Add a method to deeply copy the model structure with shallow copies of associated arrays. The copied Function(Set) can be moved to CPU/GPU without affecting the original one.
- Add a method to deeply copy the model directly to CPU.
- Add save/load methods to Function(Set). They will enable us to save the model without affecting the learning loop. The saved model should be directly read into the CPU memory.

BTW, Function/FunctionSet/Optimizer have many design issues other than the above one. I'm thinking about restructuring them to make the model definition clearer and more flexible to use. I will file an issue with some design docs, maybe after the next release.

**Comment by odashi** [comment]
Thanks.  I met this issue while just saving the model in each training epoch.
Introducing save/load methods into Function(Set) could directly solve it, and it is also desirable to reduce much redundant users' source code about accessing to the inside of the model.
Of course this is not fundamental solution for this issue, so I think at least adding any copying method is also needed for Function(Set) as well as save/load methods.

**Comment by beam2d** [comment]
See also #363

**Comment by beam2d** [comment]
This issue is resolved by #573. Now you can safely copy parameters/gradients between CPU and GPUs keeping consistency between the model and optimizer.
