### ISSUE TITLE
Report an error when cuda is not correctly initialized

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#356]
When cupy fails to initialize cuda, for example when .so files are not found, `cuda.py` cannot import `cupy`. In this case, user fails to import `cuda.cupy`, and get an error message "cupy is not found". It is confusing. https://github.com/pfnet/chainer/blob/master/chainer/cuda.py#L35

We need to notify a user an error, when a user try to use `cuda.cupy`.

**Comment by beam2d** [comment]
There are three levels of resolutions:

1. Notify users what is required at the execution of examples.
2. Enable user to write device-agnostic codes with helpful error messages.
3. Notify users what is required in arbitrary situations.

The first one can be resolved by adding check of CUDA availability to each example. It is made easy by exposing `_check_cuda_available` as an API. It also resolves the second one.

The third one is harder to resolve. I think we can achieve it by separating cupy from chainer as an independent Python package. The current error message is enough to tell users that cupy is not set up correctly. If cupy requires explicit installation, we can check CUDA availability at cupy installation and raises an error with helpful messages on installation if CUDA libraries are not found. I believe this check is simply done by trying `import cupy` at the installation.

**Comment by unnonouno** [comment]
How about using `cupy` instead of `chainer.cuda.cupy` in examples?

**Comment by beam2d** [comment]
I think using `cupy` directly makes non-GPU environment unable to run examples.
