### ISSUE TITLE
Non-parameterized linear without bias

### ISSUE THREAD

**Issue by nyuta1212** [pfnet/chainer#367]
Hello all. 

I'm sorry if this has been already reported.

According to the document, chainer looks to allow non-parameterized linear function call without bias (`b=None`), but when I try it, python raises an attribute error, which says "NoneType object has no attribute volatile."

This is because `chainer.functions.linear()` has `b=None` and `chainer.function.__call__()` tries to check `b.volatile` at line 132. 

A minor change in `chainer.functions.linear()` like:

    if b is None:
        return NonparameterizedLinear()(x, W)
    else:
        return NonparameterizedLinear()(x, W, b)

instead of just doing:

    return NonparameterizedLinear()(x, W, b)

may fix the problem.

**Comment by beam2d** [comment]
Thank you for the report! It seems a bug of type checking on the nonparameterized linear function. We will fix it.
