### ISSUE TITLE
cuda import bug?

### ISSUE THREAD

**Issue by chen1474147** [pfnet/chainer#368]

**Comment by chen1474147** [comment]
hi, all

If I use pip install chainer and cuda, when I import cuda using

from chainer import cuda

it report:
 ImportError: cannot import name install_headers.

But if I install by source code, it runs right.

 Is it a bug, or I did someting wrong?

**Comment by delta2323** [comment]
Hi. It seems to fail when installing CUDA-related modules installed by chainer-cuda-deps.
Current version of Chainer (v1.3.0) do not have to install chainer-cuda-deps, so could you try to update Chainer and uninstall chainer-cuda-deps?

Some users reported uninstalling pycuda and scikit-cuda explicitly works well. Although I do not check by myself, it might be helpful for you.

```
pip uninstall pycuda scikit-cuda chainer-cuda-deps
```

**Comment by chen1474147** [comment]
Thank you very much.

I will try it.
