### ISSUE TITLE
CuDNN v3

### ISSUE THREAD

**Issue by xternalz** [pfnet/chainer#384]
Has Chainer been updated to fully support CuDNN v3 yet?

**Comment by unnonouno** [comment]
No, officially we didn't support CuDNN v3 yet. Of course, we'll support it in near future.
If you want to try it, please run `nosetests` to run the unittest.
```
$ pip install nose
$ nosetests
```

**Comment by daikazoku** [comment]
Just to be sure I understand: if I have CuDNN v3, it will work and speed up my models even though it's not actually supported?

**Comment by unnonouno** [comment]
Sorry for late replay. We supported cuDNN v3 from v1.5. I mean, we now test Chainer with both cuDNN v3 and v2. It works well. Please update your environment.
Note that we don't use new APIs yet.
