### ISSUE TITLE
cannot use GPU

### ISSUE THREAD

**Issue by andyyuan78** [pfnet/chainer#39]
ubgpu@ubgpu:~/github/chainer$ python examples/mnist/train_mnist.py
fetch MNIST dataset
epoch 1
train mean loss=0.27774727401, accuracy=0.914516667798
test  mean loss=0.11268276395, accuracy=0.966000006199
epoch 2
train mean loss=0.136812622429, accuracy=0.958366669913
test  mean loss=0.0904840060783, accuracy=0.973000006676
epoch 3
train mean loss=0.108749408927, accuracy=0.966883340677
test  mean loss=0.073886228106, accuracy=0.976000006199
epoch 4
train mean loss=0.093579410448, accuracy=0.971016674836
test  mean loss=0.0809730870945, accur

it is fine!!!  but...

ubgpu@ubgpu:~/github/chainer$ python examples/mnist/train_mnist.py --gpu=0
fetch MNIST dataset
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 40, in <module>
    cuda.init(args.gpu)
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 107, in init
    'The original import error said: ' + str(_import_error))
RuntimeError: CUDA environment is not correctly set up. The original import error said: cannot import name intern
ubgpu@ubgpu:~/github/chainer$ which nvcc
/usr/local/cuda/bin/nvcc
ubgpu@ubgpu:~/github/chainer$ sudo pip install pyCUDA
[sudo] password for ubgpu: 
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): pyCUDA in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): pytools>=2011.2 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from pytools>=2011.2->pyCUDA)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python2.7/dist-packages (from pytest>=2->pyCUDA)
ubgpu@ubgpu:~/github/chainer$

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/chainer$ sudo pip install scikits.cuda
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting scikits.cuda
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading scikits.cuda-0.042.tar.gz (97kB)
    100% |████████████████████████████████| 98kB 846kB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): pycuda>=0.94.2 in /usr/local/lib/python2.7/dist-packages (from scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): pytools>=2011.2 in /usr/local/lib/python2.7/dist-packages (from pycuda>=0.94.2->scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2 in /usr/local/lib/python2.7/dist-packages (from pycuda>=0.94.2->scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.2.0 in /usr/local/lib/python2.7/dist-packages (from pycuda>=0.94.2->scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->pycuda>=0.94.2->scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pytools>=2011.2->pycuda>=0.94.2->scikits.cuda)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python2.7/dist-packages (from pytest>=2->pycuda>=0.94.2->scikits.cuda)
Building wheels for collected packages: scikits.cuda
  Running setup.py bdist_wheel for scikits.cuda
  Stored in directory: /home/ubgpu/.cache/pip/wheels/79/cf/aa/3f29ead4ee144d6b38b76a7986d1addbf77989eb5dd4e4e0ad
Successfully built scikits.cuda
Installing collected packages: scikits.cuda
Successfully installed scikits.cuda-0.42
ubgpu@ubgpu:~/github/chainer$ python examples/mnist/train_mnist.py --gpu=0
Traceback (most recent call last):
  File "examples/mnist/train_mnist.py", line 11, in <module>
    from chainer import cuda, Variable, FunctionSet, optimizers
  File "/usr/local/lib/python2.7/dist-packages/chainer/__init__.py", line 1, in <module>
    import cuda, cudnn
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 44, in <module>
    from scikits.cuda import cublas
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cublas.py", line 19, in <module>
    import cuda
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cuda.py", line 7, in <module>
    from cudart import *
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cudart.py", line 112, in <module>
    _libcudart.cudaGetErrorString.restype = ctypes.c_char_p
AttributeError: 'NoneType' object has no attribute 'cudaGetErrorString'
ubgpu@ubgpu:~/github/chainer$

**Comment by unnonouno** [comment]
Thank you for trying Chainer!
Please use `chainer-cuda-requirements` command which shows dependent libraries:
```
$ chainer-cuda-requirements
pycuda>=2014.1
scikits.cuda>=0.5.0b1,!=0.042
Mako
six>=1.9.0
```

So try to install them with `pip` command:
```
$ pip install `chainer-cuda-requirements`
```

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/chainer/scripts$ chainer-cuda-requirements
Traceback (most recent call last):
  File "/usr/local/bin/chainer-cuda-requirements", line 4, in <module>
    import chainer.requirements
  File "/usr/local/lib/python2.7/dist-packages/chainer/__init__.py", line 1, in <module>
    import cuda, cudnn
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 44, in <module>
    from scikits.cuda import cublas
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cublas.py", line 19, in <module>
    import cuda
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cuda.py", line 7, in <module>
    from cudart import *
  File "/usr/local/lib/python2.7/dist-packages/scikits/cuda/cudart.py", line 112, in <module>
    _libcudart.cudaGetErrorString.restype = ctypes.c_char_p
AttributeError: 'NoneType' object has no attribute 'cudaGetErrorString'
ubgpu@ubgpu:~/github/chainer/scripts$

**Comment by unnonouno** [comment]
Oh,  I see. Chainer requires scikits.cuda >= 0.5.0b1.
How about this?
```
$ pip install "scikits.cuda>=0.5.0b1,!=0.042"
```

**Comment by andyyuan78** [comment]
it successed once, but failed again!

ubgpu@ubgpu:~/github/chainer$ python examples/sentiment/train_sentiment.py --gpu=0
Traceback (most recent call last):
  File "examples/sentiment/train_sentiment.py", line 145, in <module>
    cuda.init()
  File "/usr/local/lib/python2.7/dist-packages/chainer/cuda.py", line 107, in init
    'The original import error said: ' + str(_import_error))
RuntimeError: CUDA environment is not correctly set up. The original import error said: cannot import name intern
ubgpu@ubgpu:~/github/chainer$

**Comment by beam2d** [comment]
It seems the `six` package is old. Upgrade it by `pip install -U six`.

**Comment by andyyuan78** [comment]
Great! 
how do you know this is the six issue?

BTW, I had check the six is update, my six is the newest! 
but it override by the python-six
so I fixed it by 'sudo apt-get remove python-six'

**Comment by beam2d** [comment]
Oh, that's a pitfall. I keep in mind the overriding case.
(I found this solution at http://choorucode.com/2015/02/24/pycuda-error-cannot-import-name-intern/)
