### ISSUE TITLE
Strange behavior of 'Linear' transform with shape (x, 1) in GPU mode

### ISSUE THREAD

**Issue by lightcaster** [pfnet/chainer#398]
I tried to make a linear transformation from x to 1 dimension using this code:

```python
from chainer import cuda, Variable
from chainer import functions as F

a = Variable(cuda.ones((100,5)))
l = F.Linear(5,1).to_gpu()

print  l(a).data
```
The 'strange' thing is that I'm getting different types of errors. For this particular snippet I got:

```
 ** On entry to SGEMV  parameter number 6 had an illegal value
Traceback (most recent call last):
  File "test_linear_to_1.py", line 7, in <module>
    print  l(a).data
  File "/home/light/prj/chainer/chainer/function.py", line 174, in __call__
    outputs = self.forward(in_data)
  File "/home/light/prj/chainer/chainer/functions/connection/linear.py", line 111, in forward
    Wx = x.dot(self.W.T)
  File "/home/light/prj/chainer/cupy/__init__.py", line 1016, in dot
    return dot(self, b, out)
  File "/home/light/prj/chainer/cupy/linalg/product.py", line 72, in dot
    return _tensordot_core(a, b, out, n, m, k, ret_shape)
  File "/home/light/prj/chainer/cupy/linalg/product.py", line 349, in _tensordot_core
    c.data.ptr, 1)
  File "/home/light/prj/chainer/cupy/cuda/cublas.py", line 238, in sgemv
    check_status(status)
  File "/home/light/prj/chainer/cupy/cuda/cublas.py", line 60, in check_status
    raise CUBLASError(status)
cupy.cuda.cublas.CUBLASError: CUBLAS_STATUS_INVALID_VALUE
```
And with different values of batch size and the size of the first dimension I get NANs or extremely large numbers. 

But if I change this
```python
l = F.Linear(5,1).to_gpu()
```
to this
```python
l = F.Linear(5,2).to_gpu()
```
the error disappears. 

ps I tried to dig deeper but with no luck. Still new to your lib. 
pps Great job btw, I really like the Chainer approach!

**Comment by jnory** [comment]
I met same error too. My chainer version is v1.3.0. 
In my environment, the shape of `a` (in your example) is also affect to the error.
When I changed the shape of `a`, the error disappears.

**Comment by delta2323** [comment]
Hi, thank you for reporting.
We have reproduced the error and now investigating it.

Different behaviors of the case `l.W.shape == (5, 1)` and `(5, 2)` is caused because these two cases pass through different code paths. While the former one enter here(https://github.com/pfnet/chainer/blob/master/cupy/linalg/product.py#L336), while the other enter here(https://github.com/pfnet/chainer/blob/master/cupy/linalg/product.py#L350).

**Comment by cemoody** [comment]
Hi, I believe I've seen similar issues where ndim=1 in the bilinear function too :)

**Comment by lightcaster** [comment]
Looks like the problem is [here](https://github.com/pfnet/chainer/blob/master/cupy/linalg/product.py#L340).
```python
if not transa:
```
should be
```python 
if transa:
```
The n,k should be swapped for F-contiguous array and be passed as is for C-contiguous. From the code, 
```
shape(A) = (k,n) 
shape(B) = (k,m)
```
but gemv invocation goes with n as leading dimension:
```python 
gemv(handle, transa, n, k, 1, a.data.ptr, lda, b.data.ptr, incb, 0,
             c.data.ptr, 1)
```
and this is incorrect. The dimensions should be swapped to (k,n) in this case.
For the C-contiguous case there is no transpose and (n,k) goes as is.  

Also the 'incb' should be always 1 for one-dimensional vector (but I can be wrong here).

**Comment by okuta** [comment]
Thank you for the detailed analysis @lightcaster.

**Comment by delta2323** [comment]
I added unit tests for Bilinear to confirm the problem reported by @cemoody is certainly resolved.
