### ISSUE TITLE
Implement LSTM for tree structures

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#402]
I found two types of LSTMs for tree structures for recursive neural network, S-LSTM and Tree-LSTM.

- Zhu et.al., Long Short-Term Memory Over Tree Structures. ICML2015.  http://arxiv.org/abs/1503.04881
- Tai et.al., Improved Semantic Representations From Tree-Structured Long Short-Term Memory Networks. ACL2015. http://arxiv.org/abs/1503.00075

**Comment by unnonouno** [comment]
This issue is fixed via #518 . If someone wants to implement other types of LSTMs, please reopen this issue.

**Comment by kurtespinosa** [comment]
Hi, does anyone know of a tree-lstm example in chainer? I can't seem to find one. Thanks!
