### ISSUE TITLE
How to train with CUDA in AWS

### ISSUE THREAD

**Issue by ukyou258847** [pfnet/chainer#42]
I tried to use GPU in AWS and failed.
I used g2.2xlarge with Amazon Linux AMI with NVIDIA GRID GPU Driver, which I think the easiest way to use cuda.

The commands I tried: 

#install Anaconda
wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh
bash Anaconda-2.2.0-Linux-x86_64.sh -b
echo 'export PATH=$HOME/anaconda/bin:$PATH' >> .bashrc
echo 'export PYTHONPATH=$HOME/anaconda/lib/python2.7/site-packages:$PYTHONPATH' >> .bashrc
source .bashrc
conda update conda -y
#install chainer
pip install chainer
sudo apt-get install git
git clone https://github.com/pfnet/chainer.git
pip install -r chainer/chainer/requirements/cuda-requirements.txt
python chainer/examples/mnist/train_mnist.py --gpu 1

The error I encountered:

Traceback (most recent call last):
  File "chainer/examples/mnist/train_mnist.py", line 40, in <module>
    cuda.init(args.gpu)
  File "/home/ec2-user/anaconda/lib/python2.7/site-packages/chainer/cuda.py", line 119, in init
    device  = Device(device)
pycuda._driver.LogicError: cuDeviceGet failed: invalid device

Could you help me? 
I think it is better to release the official chainer AMI for GPU instances.

**Comment by delta2323** [comment]
Hi.
Did you try device whose id is 0? If not, I recommend you try `--gpu 0` instead of 1.

**Comment by ukyou258847** [comment]
It worked! I should have noticed that id starts from zero. Thank you.

**Comment by delta2323** [comment]
Great! Thank you for trying Chainer!
