### ISSUE TITLE
Typecasting bug

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#421]
The result of multiplying a float32 cupy ndarray by a constant integer is a float64 array. This is not consistent with numpy.

    import numpy as np
    import cupy as cp
    a = np.zeros((2,)).astype('float32')
    b = cp.zeros((2,)).astype('float32')

    (2 * a).dtype  # float32
    (2 * b).dtype  # float64

**Comment by okuta** [comment]
Thank you for your report.
I will fix it.
