### ISSUE TITLE
Chainer 1.3.1 get 1.5x slower than 1.1.0

### ISSUE THREAD

**Issue by jnory** [pfnet/chainer#429]
Hi,

We recently upgrade chainer from 1.1.0 to 1.3.0.
But our internal benchmark shows that chainer 1.3.0 is 1.5x slower than 1.1.0.

I want to ask you several points:
* Do you encounter the same problem?
* Are there any ways to solve this issue?

Thank you in advance,

Jun-ya NORIMATSU

**Comment by beam2d** [comment]
Please ask questions about Chainer usage to the forum here https://groups.google.com/forum/#!forum/chainer. Thank you.

**Comment by beam2d** [comment]
(I recommend you to add more information about your Chainer usage to the forum post, e.g. which of CPU/GPU you are using:) ).

**Comment by jnory** [comment]
Thank you! I will post this to the forum!
