### ISSUE TITLE
Bug: Reshape() with -1 fails

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#467]
When calling the chainer function Reshape() with a -1 value (e.g. Reshape((-1, 10, 10))) I get an error: 

    InvalidType: Expect: prod(in_types[0].shape) == prod((-1, 10, 10))
    Actual: 2800 != -100

The cupy function reshape does support -1 arguments, so the error seems to be just the check in chainer's Reshape. The problematic check is:
   _type_check_prod(in_types[0].shape) == _type_check_prod(self.shape)

If a -1 argument is present, it should instead check if the size of in_types[0] is divisible by the product of the axis-lengths that are not -1. 

I would send a PR but I'm not exactly clear on the correct usage of type_check.expect, and had some issues with it in the past. Should be simple enough to fix though.

**Comment by unnonouno** [comment]
Thank you for reporting a problem. As you say, `Reshape` can easily support -1 value.
I'll fix its type check method.
