### ISSUE TITLE
Show a warning message on suspected usages of parameter GPU migration

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#47]
`Function.to_gpu` and `FunctionSet.to_gpu` involves array copying, while an Optimizer object does not know this event. Consequently, user must migrate parameters onto devices BEFORE passing them to the optimizer. Violating this rule does not emit any messages currently, which ends up to making the training code meaningless.

So how about show a warning message if `FunctionSet.collect_parameters` is called after `FunctionSet.to_gpu`?

**Comment by unnonouno** [comment]
I think it's enough.

**Comment by delta2323** [comment]
It is important what Chainer shows as a warning message. I think we should add not only the measures we should take when users are confronted with the warning but also the reason (that beam2d mentions in this issue) why they must take the measures. One of the solution would be to refer to this issue in the warning message.

**Comment by beam2d** [comment]
@delta2323 That's a good idea! Let's include into the message a reason why we show it (maybe with a pointer to this issue).

**Comment by beam2d** [comment]
Close since this issue is obsolete.
