### ISSUE TITLE
The behavior of Function#parameters= is inconsistent with FunctionSet#parameters=

### ISSUE THREAD

**Issue by wafrelka** [pfnet/chainer#502]
At aaf2aae14ad683734964590e6ceee9d775d9d7c5, an assertion was introduced into `Function#parameters=`, which requires the argument `values` to be a list-like object (implementing `__len__` method).
However, this assertion seems to be inconsistent with the behavior of `FunctionSet#parameters=`.
`FunctionSet#parameters=` passes the iterator of its argument `params` to its child functions through `Function#parameters=`, and it causes a TypeError exception.

```python
from chainer import FunctionSet
import chainer.functions as F
func_set = FunctionSet(f=F.Linear(10,10))
params = func_set.parameters
func_set.parameters = params # TypeError: object of type 'tuple_iterator' has no len()
```

**Comment by delta2323** [comment]
I fixed this issue. It is now under review.

**Comment by wafrelka** [comment]
Thank you!!!!
