### ISSUE TITLE
bug in ptb/download.py 

### ISSUE THREAD

**Issue by ywatanabex** [pfnet/chainer#515]
I found that example/ptb/download.py does not work in the following situations:

1. if python3, we get an error

```
Traceback (most recent call last):
  File "download.py", line 5, in <module>
    urllib.urlretrieve(
AttributeError: 'module' object has no attribute 'urlretrieve'
```

2. if under proxy, we can not get files ptb.*.txt correctly.
    (We get Request Error files.)

**Comment by unnonouno** [comment]
> py3
Oh, sorry. It's right. We'll fix it.

> proxy
Did you try to use `http_proxy` environment variable?
https://docs.python.org/2/library/urllib.html#module-urllib

**Comment by ywatanabex** [comment]
Thanks for quick response.

Yes, I've set `http_proxy` environment variable.
Actually, I can download it with `urlopen` method, but not with `urlretrieve`.

Some people are discussing on how to use proxy with `urlretrieve`
 http://stackoverflow.com/questions/22967084/urllib-request-urlretrieve-with-proxy
but it looks complicated...

**Comment by unnonouno** [comment]
Humm, did you set `https_proxy`? In my environment, `urlretrieve` also uses `http_proxy` and `https_proxy`.

**Comment by unnonouno** [comment]
Please try ``https_proxy``. I'll close this issue. If you cannot download the files with ``https_proxy``, please reopen the issue.
