### ISSUE TITLE
Convolution2D does not support 64 bit

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#519]
When I change dtype=numpy.float32 to dtype=numpy.float64 in the constructor of Convolution2D, and then run nosetests I get tons of errors. I think 64 bit is simply not supported, so we should raise a NotImplementedError.

**Comment by delta2323** [comment]
You mean you changed the default argument of `dtype` in `Convolution2D.__init__` from `numpy.float32` to `numpy.float64` ? Some unit tests assume the default value of `dtype` be `float32` (e.g. test_forward_consistency). So I think we cannot say that passing `float64` as the argument of `__init__` does not work only from the errors (although we cannot say it does work, neither because we do not have the test case where `dtype` equals to `float64`).

**Comment by tscohen** [comment]
Yes, that's what I did. You're right that this does not exclude other causes for the error, so I tried the following:
   
    import cupy as cp
    from chainer.functions.connection.convolution_2d import Convolution2D
    S32 = Convolution2D(in_channels=1, out_channels=2, ksize=5, dtype='float32', use_cudnn=True)
    S64 = Convolution2D(in_channels=1, out_channels=2, ksize=5, dtype='float64', use_cudnn=True)

    S32.to_gpu()
    S64.to_gpu()

    x_data32 = cp.random.randn(3, 1, 7, 7).astype('float32')
    x32 = Variable(x_data32)
    x64 = Variable(x_data32.astype('float64'))

    S32.W = cp.random.randn(*S32.W.shape).astype('float32')

    S64.W = S32.W.astype('float64')
    S64.b = S32.b.astype('float64')

    y32 = S32(x32)
    y64 = S64(x64)

    print 'difference', cp.abs(y32.data - y64.data).sum()

The output y64 is all zero. It works fine when I change use_cudnn to False for the 64 bit conv, so it seems like this is a problem with cudnn.

I looked at the Convolution2D code but could not find the error. One thing I did notice is that the workspace_size is multiplied by 4 (number of bytes in a float). I changed this 4 to self.dtype.itemsize, and also changed the line
   workspace = cuda.empty((max(workspace_size // 4, 1),), dtype=self.dtype)
in forward_gpu to divide by self.dtype.itemsize. Still results in zero output.

I'm not familiar with cudnn, so I don't know what could be causing this. For now I'm going to stick with the non-cudnn 64 bit version for my gradient checking.
