### ISSUE TITLE
CuPy.random.randn supports dtype parameter but numpy.random.randn does not

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#520]
^ 
This is a problem because we want 100% API compatibility; not only should numpy code always work in CuPy, CuPy code should also always work on numpy.

**Comment by beam2d** [comment]
Hmm, I added this option to provide an easy way to use the float32 support of cuRAND, which benefits for certain situations (see, for example, gaussian function). CuPy does not support 100% of the NumPy APIs (e.g. some CuPy functions lack options supported by NumPy), so I want to tolerate reverse situations.

**Comment by tscohen** [comment]
Ok I see. I guess we can leave this, since really numpy should add a dtype parameter for this.. In general though, shoudn't the end goal be to make cupy 100% compatible with numpy?

**Comment by beam2d** [comment]
Ideally, yes. I agree that the ultimate goal of the CuPy ndarray interface is the 100% compatibility with NumPy (of course except low-level features like custom kernel generation and ctypes support, which definitely must be different). Though, there might be situations that NumPy design is not suited to avoid overheads on GPU computation. In such case, we have to provide a more efficient way outside of the NumPy interface. It might be helpful for host/device-agnostic coding to provide wrapper functions for such case that can be used for both NumPy and CuPy (e.g. in the case of #522, providing add_dot that works both for numpy.ndarray and cupy.ndarray).
