### ISSUE TITLE
Deprecate bias parameter of Convolution2D?

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#525]
Currently, Convolution2D has a bias and initial_bias argument. The documentation of bias is "Initial bias value". So it seems like they are redundant. The code currently expects an array for initial_bias and a scalar for bias, but these could both be supported by initial_bias. Or alternatively, we could remove the nobias parameter as well and just have a bias parameter that can be a number, an array, or None (for no bias).

**Comment by beam2d** [comment]
I've found that duplication right now (we are unintentionally synchronized :)). I agree that `bias` is redundant and should be removed by allowing a scalar `initial_bias`. Linear has the same issue, too.

**Comment by tscohen** [comment]
Cool :) 

I just realized that an even cleaner implementation would not have a bias parameter for Linear or Convolution2D at all, but implement the Linear+Bias (called "Affine" by mathematicians) and Conv2D+Bias as a chain (using terminology of #363). The downside is that CUDNN combines conv and bias in one operation.

**Comment by delta2323** [comment]
I made a PR which fixes this issue. Although the change is minor, should defer until the discussion on the design comes to the conclusion?

I realized that `Bilinear` also accepts the keyword argument named `initial_bias`, but it should be tuple of `xp.ndarray` of length 3. It can be confusing, so should we change the name of the argument of `Bilinear` ?

**Comment by beam2d** [comment]
Sorry for the late reply. Go ahead on the PR!
