### ISSUE TITLE
Test behavior of functions with combination of different types

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#556]
We found a strange behavior of old CUDA in #551. We need to test combination of different types such as `int8` and `float64` for other functions.
However, a test with **all** combinations requires too long time. My idea is to test **random** combinations of types. When we found a bug, we manually add a specific combination to the test.

**Comment by tscohen** [comment]
Perhaps we can have two testing modes: 'fast' and 'full'. We could run the full mode maybe once a month. Even if it takes a month to run that would be fine.

**Comment by unnonouno** [comment]
Oh, it's a good idea! I'll make both modes.
