### ISSUE TITLE
Cupy indexing behaviour

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#574]
I mistakenly tried to perform the following indexing operation:

    import cupy as cp
    x = cp.random.randn(16, 1, 9, 9)
    y = x[:, :, (2,2):(7,7), (2,2):(7,7)]

This results in a y with shape (16, 1, 0, 0). In numpy an "IndexError: invalid slice" is raised. Maybe the cupy indexing should check for invalid slices of this kind?

**Comment by unnonouno** [comment]
Thank you for reporting a bug! We'll check the specification of numpy and fix it.
