### ISSUE TITLE
Stable SoftmaxCrossEntropy

### ISSUE THREAD

**Issue by bordingj** [pfnet/chainer#584]
The probabilities from the softmax function can become numerically zero. Hence,  for the forward method in the softmax_cross_entropy something like

 	numpy.log(numpy.maximum(1.0e-8,p))

and

	log(fmax(1.0E-8, y[_j * n_channel + t]) ) 

should be added for the cpu and gpu, respectively.

**Comment by unnonouno** [comment]
Thank you for reporting a problem.
How about using `log_sum_exp` to avoid under flow?

**Comment by delta2323** [comment]
Do you think we should add `logsumexp` to CuPy? `logsumexp` is in different situation from other functions in that `logsumexp` is not in numpy but in spicy (`spicy.misc.logsumexp`).

**Comment by bordingj** [comment]
I dont see how logsumexp solves the problem
