### ISSUE TITLE
Unpooling2D function?

### ISSUE THREAD

**Issue by wkentaro** [pfnet/chainer#597]
Do you have plan to implement unpooling2d function?

**Comment by wkentaro** [comment]
I'd like to use it to construct convolutional autoencoder like [here](https://github.com/mikesj-public/convolutional_autoencoder).

**Comment by wkentaro** [comment]
simple demo: https://gist.github.com/wkentaro/bb8300867a5ed6d53200

**Comment by mitmul** [comment]
Duplicate of https://github.com/pfnet/chainer/pull/301

**Comment by wkentaro** [comment]
I didn't notice that, but that is PR and not issue. So maybe we can keep this issue open.
