### ISSUE TITLE
Pair-wise model with Chainer

### ISSUE THREAD

**Issue by lglhuada** [pfnet/chainer#627]
Hi I am very new to chainer. The dataparallel is rather good. While do any guys of you know how to implement pair-wise model. You can find an example implemented by torch https://github.com/torch/nn/blob/master/doc/containers.md#nn.Parallel

Any help are more than welcome.

Best

**Comment by delta2323** [comment]
Hi. Thank you for trying Chainer. We collect general questions in [User Group](https://groups.google.com/forum/#!forum/chainer). So could you post this there? Thank you.
