### ISSUE TITLE
Error? AttributeError: 'numpy.int32' object has no attribute 'ctypes'

### ISSUE THREAD

**Issue by hengck23** [pfnet/chainer#634]
I am using windows 7 + cuda 7.5 on chainer 1.4.1.
I have this weird error when try to run example "train_mnist.py" : 

  File "C:\Anaconda\lib\site-packages\chainer-1.4.1-py2.7.egg\cupy\cuda\module.py", line 65, in __call__
    print _native.get(type(x), _get_ctypes)(x)
  File "C:\Anaconda\lib\site-packages\chainer-1.4.1-py2.7.egg\cupy\cuda\module.py", line 29, in _get_ctypes
    return x.ctypes
AttributeError: 'numpy.int32' object has no attribute 'ctypes'

I try to debug and it seems that _native.get(type(x)) cannot work when type is numpy.int32 ????
Any help is appreciated. Thanks!

**Comment by hengck23** [comment]
Just for your information, my system works fine for the branch "fix-imagenet-for-windows", which is chainer 1.3.2. I suspect the error comes from softmax_cross_entropy.py (and/or accuracy.py) because they use int32 for the label to do computation.

**Comment by delta2323** [comment]
Thank you for trying Chainer. We have already solved this problem in `CuPy` branch. Could you wait until this branch will be merged in `master`?

**Comment by hengck23** [comment]
Thank you very much. I am looking forward to v1.5.0.
