### ISSUE TITLE
Allow broadcasting in basic_math

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#638]
I tried to add two tensors with different but broadcastable shapes, and noticed that Add() has a type check at line 94 of basic_math.py:
in_types[0].shape == in_types[1].shape

Can we support broadcasting in the basic_math functions? We'd have to change the type check as well as the gradient computation.

**Comment by unnonouno** [comment]
Did you try manual broadcast? I mean:
```
x, y = functions.broadcast(x, y)
z = x + y
```
It's enough for me, because I sometimes causes wrong broadcast by mistake ;-(

And, maybe this is the same issue.
https://github.com/pfnet/chainer/issues/228

**Comment by okuta** [comment]
Please see #228
