### ISSUE TITLE
cupy.array cause segmentation fault

### ISSUE THREAD

**Issue by ywatanabex** [pfnet/chainer#639]
Hi, I have been playing with cupy today and find a bug.

The following code result in `Segmentation fault (core dumped)`

```pyton
import cupy
x = cupy.random.rand(100, 10)
cupy.array([x[0], x[1]])
```

thanks.

**Comment by okuta** [comment]
Segmentation fault no longer occurs by fixing #665.
But, it requires to fix #667 in order to be correct behavior.
