### ISSUE TITLE
TestConvolution2D.test_(forward, backward)_gpu_im2col does not check use_cudnn=False case

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#657]
`TestConvolution2D.test_forward_gpu_im2col` and `TestConvolution2D.test_backward_gpu_im2col` are expected to test `Convolution2DFunction.backward_gpu` works correctly when CuDNN is disabled.

To achieve this, these test fixtures set `self.use_cudnn` attribute of the instance of `Convolution2D` to `False` . But what is actually passed to `convoluton_2d` function as `use_cudnn` option is the `use_cudnn` argument of `__init__` , not the attribute `self.use_cudnn` (See [here](https://github.com/pfnet/chainer/blob/af1f11d4e50b322286a041c416eddd4e0ee63d30/chainer/links/connection/convolution_2d.py#L75)).

**Comment by unnonouno** [comment]
Is it true? I think `self` is `TestConvolution2DFunction`, not `Convolution2D`.

**Comment by delta2323** [comment]
Thank you for commenting. I afraid I cannot fully understand your comment. I am considering about  `TestConvolution2D` (in `links_tests`) and do not understand why `TestConvolution2DFunction` (in `functions_tests` ) is involved.

**Comment by unnonouno** [comment]
OK, I understood.
