### ISSUE TITLE
ELU activation function

### ISSUE THREAD

**Issue by tscohen** [pfnet/chainer#694]
Djork-Arné Clevert, Thomas Unterthiner and Sepp Hochreiter propose a new activation function which seems to work well:

Fast and Accurate Deep Network Learning by Exponential Linear Units (ELUs)
http://arxiv.org/abs/1511.07289

The ELU (eq. 16) and its gradient (eq. 17) should be very easy to implement.

**Comment by duschendestroyer** [comment]
somebody already did the work: https://github.com/muupan/chainer-elu
I agree that it should be included.

**Comment by muupan** [comment]
I did the work, but not yet examined its performance. It would be great if anyone can reproduce some of the results in the paper. I'll willingly make a PR if it should be included.
