### ISSUE TITLE
Cannot build on MacOS10 under python3

### ISSUE THREAD

**Issue by DSLituiev** [pfnet/chainer#699]
Thank you very much for this useful package! I have been using `chainer` installed with `pip` under `python3.4` on my MacOS Yosemite machine. Now I need some newer features and I cannot build it with `python3.4` from Anaconda. And it is even hard to debug why:

    $python3 setup.py install
    Unable to find pgen, not compiling formal grammar.
    Killed: 9

It takes quite some time between the second and the last lines.
The machine has  8GB RAM in case.

Under `python2.7` build does work.

**Comment by DSLituiev** [comment]
with pip I get following:

```
$ pip3 install chainer --upgrade
Collecting chainer
  Downloading chainer-1.5.0.2.tar.gz (191kB)
    100% |████████████████████████████████| 192kB 1.0MB/s
    Complete output from command python setup.py egg_info:

    ----------------------------------------
Command "python setup.py egg_info" failed with error code -9 in /private/var/folders/97/527pmsxx5nb7_vfnb8621nqm0000gn/T/pip-build-wbljpv8g/chainer
```

**Comment by unnonouno** [comment]
Thank you for reporting a problem. I'll check it.

**Comment by unnonouno** [comment]
This error message is found in setup script of Cython:
https://github.com/cython/cython/blob/master/setup.py#L127

Could you check if you can install cython correctly?

**Comment by DSLituiev** [comment]
Thank you very much. Upgrading cython helped. It was either a broken installation, or version compatibility. Solved.
