### ISSUE TITLE
Support gradient hard-clipping

### ISSUE THREAD

**Issue by bordingj** [pfnet/chainer#701]
Currently, chainer.optimizer supports gradient clipping by L2-rescaling of all gradients if the L2-norm is above some threshold as described in http://arxiv.org/pdf/1211.5063v2.pdf . 

It is also popular to do hard-clipping as implemented in theano https://github.com/Theano/Theano/blob/7415e2f0f7526cac1a051627e2094cca063ea532/theano/gradient.py#L2012

Ofcourse, you might loose some information in the gradients with hard-clipping, but in practice it works well, and hard-clipping is alot faster on the GPU than norm-rescaling, because hard-clipping is just an elementwise operation. 

I think chainer.optimizer should support hard-clipping. Cupy already supports clipping.

Here is a suggested hook that I quickly made

    class GradientHardClipping(object):
    
        """Optimizer hook function for gradient clipping.
        This hook function clips all gradient arrays to be within a lower and upper bound.
        Args:
            lower_bound (float): The lower bound of the gradient value.
            upper_bound (float): The upper bound of the gradient value.
        Attributes:
            lower_bound (float): The lower bound of the gradient value.
            upper_bound (float): The upper bound of the gradient value.
        """
        name = 'GradientHardClipping'
    
        def __init__(self, lower_bound, upper_bound):
            self.lower_bound = lower_bound
            self.lower_bound = upper_bound
    
        def __call__(self, opt):
            xp = opt.target.xp
            for param in opt.target.params():
                grad = param.grad
                with cuda.get_device(grad):
                    grad = xp.clip(grad, self.lower_bound, self.upper_bound,
                                   out=grad)

**Comment by unnonouno** [comment]
Thank you for suggestion. We'll review this code. Can you make a pull request?
