### ISSUE TITLE
Unnecessary `print` statement in cupy/core/core.pyx

### ISSUE THREAD

**Issue by yuichiro-s** [pfnet/chainer#723]
There seems to be an unnecessary `print` statement in cupy/core/core.pyx
(https://github.com/pfnet/chainer/blob/master/cupy/core/core.pyx#L1692)
This causes what seems to be debug info to be printed whenever you call `cupy.ndarray.repeat()`

**Comment by unnonouno** [comment]
That's right. I'll remove this line. Thank you!
