### ISSUE TITLE
Cannot upgrade Chainer with old cython

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#731]
I installed cython=0.22.1 with pip in python 3 environment, and then tried to install chainer with pip, but it failed. This is install log.
https://gist.github.com/unnonouno/e46d11c05fa59050326a

And, with setuptools=18.3.2 and cython==0.22.1, it causes infinite loop.

**Comment by Fhrozen** [comment]
I also have the same problem but for installing in a new env. Using python 2.7 and cython 0.23.4, I already have installed in a env with python 2.7 but with cython 0.20.1. So i am wondering if is an error of the chainer installer or from cython. But I already uninstalled and installed cython and still the problem.

**Comment by unnonouno** [comment]
This problem is very complicated. Chainer requires Cython (>=0.23) when a user install Chainer. So, we wrote `cython==0.23` in `setup_requires` of Chainer. `setuptools` checks the requirement of Chainer, and tries to install `cython==0.23` if old cython is installed. In this process, `setup.py` of Cython causes infinite loop or a critical error. But, we didn't understand why `setup.py` causes error (maybe reloading problem in `setuptools`).

We decided to distribute `.cpp` files generated by Cython, and remove Cython from requirements of Chainer in the next release. It may solve this problem. We'll release the next version tomorrow. Please wait.

**Comment by unnonouno** [comment]
We remove dependency to Cython, and we tested this situation. I'll close this issue.
