### ISSUE TITLE
Add a dot product function

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#8]
It should handle inner-product, matrix-vector product, and matrix-matrix product functions. It is better if it supports a batch mode.

**Comment by muupan** [comment]
I implemented dot and batchdot functions separately, though currently they don't support GPU computation.

https://github.com/muupan/chainer/commit/6a0863486ebad31455ff2e3dbf69497863c24edb

**Comment by okuta** [comment]
Think you for your code.
I will use this for reference.
