### ISSUE TITLE
Expose cupy.helper.for_dtypes_combination

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#802]
Since `cupy.for_dtypes` is exposed to user (by registering it to `cupy/testing/__init__.py`), I think it is natural that `cupy.helper.for_dtypes_combination`, or corresponding decorator for combination of dtypes is also exposed.

How do you think of it?

**Comment by okuta** [comment]
I agree.

**Comment by delta2323** [comment]
I added feature label because it changes API exposed to users.
