### ISSUE TITLE
Add VAE example

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#806]
As suggested in User Group, it is preferable to add VAE example that utilize functions in `chainer.functions.loss.vae`. One of the candidate is to implement (supervised or unsupervised) VAE that generates MNIST.

**Comment by ywatanabex** [comment]
Hi, I have implemented the simple VAE. It seems to be working correctly.
Do you have any suggestions for improvements?

https://github.com/ywatanabex/chainer/tree/example-vae

I have some questions.
- Are there style guide for docstrings?
- data.py is copied from MNIST example. maybe this is not good.
- I do not well how to send pull request etc.. so could you give me advices?

**Comment by delta2323** [comment]
Thank you for your work!

We do not have guideline for doc string. Could you make the document by referencing other examples?
You should send PR to the master branch of the original repository. I think you can send PR by following the github's UI.

**Comment by ywatanabex** [comment]
I have change the code to pass flake8 test.

**Comment by delta2323** [comment]
This issue is fixed by #1046.
