### ISSUE TITLE
eps is a redundant argument of fixed_batch_normalization

### ISSUE THREAD

**Issue by delta2323** [pfnet/chainer#855]
`eps` is used only when `BatchNormalization.forward` is called with three arguments. So `fixed_batch_normalization` does not need `eps` because it calls forward propagation with five arguments.

**Comment by beam2d** [comment]
See the comment of #2149. `fixed_batch_normalization` should add `eps` to the accumulated variance, so it should be fixed in a different way: do not remove `eps` argument and actually use it instead.
