### ISSUE TITLE
Fail to load_npz optimizer

### ISSUE THREAD

**Issue by tapdo** [pfnet/chainer#895]
When load optimizer by load_npz, it's failed.

KeyError: '/conv5_3/W/m is not a file in the archive'

I think this is numpy bug.
When the follow code is running, the first character of "/" is dropped.
numpy.savez(f, **s.target)

**Comment by beam2d** [comment]
Yes, it seems a bug of np.savez/np.load caused by its zip archive nature. We are trying to avoid this issue in #878.
