### ISSUE TITLE
Facing issue while running the training script on FLIC dataset

### ISSUE THREAD

**Issue by karunaahuja** [pfnet/chainer#897]
Sorry I am a student who is relatively new to this. But while running the training script I am facing the following error. 

File "scripts/train.py", line 206, in <module>
    os.environ['CHAINER_SEED'] = args.seed
  File "/usr/lib/python2.7/os.py", line 471, in __setitem__
    putenv(key, item)

What and how do I set the variable ?

**Comment by delta2323** [comment]
Hi
Are you running the script in [mitmul's deeppose](https://github.com/mitmul/deeppose)? If you are, the author updated the code and wrote the workaround in mitmul/deeppose#12. I recommend you follow the mitmul's instruction.

**Comment by beam2d** [comment]
Close. If you still have a problem, please send a post to [the forum](https://groups.google.com/forum/#!forum/chainer) with details.
