### ISSUE TITLE
Stateless LSTM link

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#911]
I need a stateless-LSTM link like GRU. Stateful-LSTM link makes a code simple, but it is difficult to generate a sequence with beam search because we need to store top-k states to a priority queue.

We also need to design consistency of names.

- Stateful LSTM: `links.LSTM`
- Stateless LSTM: new!
- Stateful GRU: `links.StatefulGRU`
- Stateless GRU: `links.GRU`

**Comment by EdwardRaff** [comment]
Adding the beam-search code too would also be nice! I'm not aware of any libraries that have it available.
