### ISSUE TITLE
Make it easy to write a training code

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#914]
I am planning to introduce some abstractions for typical training loops. I've written a design note, and a prototype implementation in the `trainer` branch.

https://docs.google.com/document/d/1HxRNc0RV7BWUSiQJdTEOBOwx9bNRLVVEysUAcZEMNrU/edit#

This design note includes links to some example codes (in the prototype branch). I am still thinking about the better level of abstraction. Feel free to ask questions on the design, and make requests.

**Comment by oeway** [comment]
+1
