### ISSUE TITLE
Correction of cuDNN library files name

### ISSUE THREAD

**Issue by kndt84** [pfnet/chainer#929]
http://docs.chainer.org/en/stable/install.html#install-chainer-with-cuda-and-cudnn

```
$ cp /path/to/cudnn.h $CUDA_PATH/include
$ cp /path/to/cudnn.so $CUDA_PATH/lib64
```

cuDNN library fine names are libcudnn.so*
I think it would be better to change the file name from cudnn.so to libcudnn.so*

**Comment by unnonouno** [comment]
Oh, that's right. `libcudnn.so*` is correct.
