### ISSUE TITLE
cuda.get_device is too slow

### ISSUE THREAD

**Issue by tapdo** [pfnet/chainer#938]
This is not bug but only a  suggestion for performance improvement.

 I found "__exit__" function of "cupy.cuda.device.Device" spend much time.
"with cuda.get_device ..." statement is used in variable.py, optimizer.py, function.py..., and "**exit**" of Device obujet is called many times in each iteration of the training.　This exacerbated the performance.

After I commnet out some of the "with cuda.get_device ..." statement in  variable.py, optimizer.py, function.py, the iteration time is twice fater than before.

I expect future improvement in this issue.

**Comment by beam2d** [comment]
Sorry for the late replay. I measured the time of MNIST example with and without get_device, and cannot detect significant differences between them (mean over 10 trials: 55.43sec vs 54.46sec). Could you tell me the detail of your script?

**Comment by tapdo** [comment]
I put some scripts. Look my repository.
https://github.com/tapdo/chainer_exp

Replace chainer's files(I' using chainer v1.6.0.) with what I modified in "custom_file" dir. 
After that, you can run my script "cifar-10_train.py". (It need "cifar-10-batches-py/data_batch_*" [https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz])
The network is 54 layer Deep Residual Learning(http://arxiv.org/abs/1512.03385).

My results of first 10 epoch in "result" dir.
" log_mycustom.txt" is result of my modification, " log_original.txt" is reulst of original chainer.
All of them are on enabled GPU
Look at "epoch time" and "duration", that shows almost 40% faster than original.

Below is my environment.
CPU: i7-3770K CPU @ 3.50GHz
DDR3 32GB (8GB x 4)
Mother board: ASUSTeK P8H77-V
GPU: Nvidia GTX970 (ASUSTek)
OS: Windows 7 (64bit), 
Python 2.7.6
chainer v1.6.0.

**Comment by beam2d** [comment]
Thank you for sharing the code. I'll try it.

**Comment by beam2d** [comment]
I tried your code in my environment (Ubuntu14.04, Xeon E5-2630 v3, GeForce TITAN X), though I could not find significant differences (approximately 83sec. vs 82sec.). It might be a difference between Linux and Windows, though I cannot investigate it, since I do not have an environment.

**Comment by tapdo** [comment]
Last result of "log_mycustom.txt" is some parameter wrong, I fixed it now. Sorry.
Now my result is 110sec vs 201sec,  80% faster than original. It may be caused by OS, you say.
