### ISSUE TITLE
Make docker image for easy start

### ISSUE THREAD

**Issue by hido** [pfnet/chainer#94]

**Comment by kazunori279** [comment]
I wonder if Chainer can run inside Docker container, as it uses some native resources such as CUDA/GPU.

**Comment by ixixi** [comment]
I'm using Chainer (and Jupyter) on Docker like [this]( https://gist.github.com/ixixi/e995f8b3a8709c528b4f ).
`--device` option allows you to run devices inside the container .
```
$ docker run -d -it \
  --device /dev/nvidia0:/dev/nvidia0 \
  --device /dev/nvidia1:/dev/nvidia1 \ 
  --device /dev/nvidia2:/dev/nvidia2 \
  --device /dev/nvidiactl:/dev/nvidiactl \
  --device /dev/nvidia-uvm:/dev/nvidia-uvm \
  -p 8888:8888 \
  -v /path/to/notbookedata/:/home/jovyan/notebookdata \
  jupyter_chainer
```

**Comment by unnonouno** [comment]
We have Dockerfiles which are used for CI. Are these enough?
https://github.com/pfnet/chainer-test
