### ISSUE TITLE
NameError: global name 'drv' is not defined

### ISSUE THREAD

**Issue by nishio** [pfnet/chainer#96]
When `Variable#__init__` get an integer as the parameter `data`, the exception `NameError: global name 'drv' is not defined` occurs.

To reproduce:

```
Variable(1) + 1
```

It causes:

```
.../chainer/chainer/cuda.pyc in get_device(arg)
    222             arg = arg.base
    223         return arg.gpudata.device
--> 224     return drv.Device(arg)
    225
    226

NameError: global name 'drv' is not defined
```

Possible solution: to raise AssertionError in `Variable#__init__` if `data` is not an expected type.

**Comment by nishio** [comment]
Here is a blog entry in Japanese: http://d.hatena.ne.jp/nishiohirokazu/20150628/1435471207

**Comment by unnonouno** [comment]
Thank you very much! We need to check types of arguments in `Variable.__init__` and other APIs.

And, maybe it is because infix operators of `Variable` are overrided.

**Comment by nishio** [comment]
Thank you. I didn't aware of `basic_math.install_variable_arithmetics()`.

I understood `+` is overrode by `AddConstant` and calls `Function.__call__` with an argument `Variable(1)` as `inputs`, then it calls `cuda.using_device`.

I don't understand why the behavior depends on `data` yet, but I think it is not important. Should I close the issue?

**Comment by unnonouno** [comment]
I fixed `Vairable.__init__` to check types of arguments in PR #101 . So, I closed this issue, thanks!
